import crypto from "node:crypto";
import express from "express";
import { MOVIE_MENTOR_TURN_ORCHESTRATOR_VERSION, MOVIE_MENTOR_TURN_CONTRACT_VERSION } from "./ai/MovieMentorTurnOrchestrator.js";
import { MOVIE_MENTOR_TURN_RUNTIME_VERSION, buildRequestDigest } from "./ai/MovieMentorTurnRuntime.js";
import { runMovieMentorTurnWithForwardExecutionAuthority } from "./ai/MovieMentorForwardExecutionRuntime.js";
import { getMovieMentorCreatorStateStoreStatus } from "./ai/MovieMentorCreatorStateStore.js";
import { applyMovieMentorCreatorStateTransition, MOVIE_MENTOR_CREATOR_STATE_TRANSITION_VERSION } from "./ai/MovieMentorCreatorStateTransition.js";
import { commitCreatorDecision } from "./ai/MovieMentorCreatorDecisionAuthority.js";
import { createMovieMentorCreatorStateMutationAuthority } from "./ai/MovieMentorCreatorStateMutationAuthority.js";
import { createMovieMentorCreatorStateConsumptionAuthority } from "./ai/MovieMentorCreatorStateConsumptionAuthority.js";
import { createMovieMentorForwardExecutionAuthority } from "./ai/MovieMentorForwardExecutionAuthority.js";

const MOVIE_MENTOR_TURN_GATEWAY_VERSION = "2.8.0";
const cleanString = (value) => (typeof value === "string" ? value.trim() : "");
function canonicalize(value) { if (value === null || typeof value !== "object") return value; if (Array.isArray(value)) return value.map(canonicalize); return Object.fromEntries(Object.keys(value).sort().map((key) => [key, canonicalize(value[key])])); }
function digest(value) { return crypto.createHash("sha256").update(JSON.stringify(canonicalize(value))).digest("hex"); }
function creatorPayloadFromRuntimeResult(result) { const payload = structuredClone(result); if (payload?.metadata && typeof payload.metadata === "object") delete payload.metadata.canonicalResult; return payload; }
function exposureError(code, message, extras = {}) { const error = new Error(message); error.code = code; error.retryable = false; Object.assign(error, extras); return error; }

async function assertCreatorHttpExposureAuthority({ result = null, authorized = null, inferenceExecutionAuthority = null, inferenceSettlementAuthority = null } = {}) {
  const runtimeProof = result?.metadata?.canonicalResult;
  if (!result || typeof result !== "object" || runtimeProof?.creatorResponseAuthorityVerified !== true || !cleanString(runtimeProof?.executionId) || !cleanString(runtimeProof?.resultDigest)) throw exposureError("MOVIE_MENTOR_CREATOR_HTTP_EXPOSURE_AUTHORITY_REQUIRED", "Creator HTTP exposure requires a runtime result that identifies its certified durable response universe.");
  if (typeof inferenceExecutionAuthority?.readCanonicalResult !== "function" || typeof inferenceSettlementAuthority?.reconcile !== "function") throw exposureError("MOVIE_MENTOR_CREATOR_HTTP_EXPOSURE_AUTHORITY_REQUIRED", "Creator HTTP exposure requires its own current canonical-result and settlement authority reads.");
  const canonical = await inferenceExecutionAuthority.readCanonicalResult({ executionId: cleanString(runtimeProof.executionId) });
  if (canonical?.authorized !== true || canonical?.committed !== true || canonical?.currentRealityVerified !== true || canonical?.candidateLineageVerified !== true || canonical?.resultFinalizationVerified !== true || !["finalized", "settled"].includes(cleanString(canonical?.executionPhase)) || !cleanString(canonical?.executionId) || !cleanString(canonical?.creatorTurnId) || !cleanString(canonical?.principalId) || !cleanString(canonical?.projectId) || !cleanString(canonical?.reservationId) || !cleanString(canonical?.requestDigest) || !cleanString(canonical?.resultReference) || !cleanString(canonical?.candidateReference) || !cleanString(canonical?.closureReference) || !cleanString(canonical?.closureCertificateDigest) || !cleanString(canonical?.resultDigest) || canonical?.resultPayload === undefined || !Number.isSafeInteger(canonical?.providerEffectRealityRevision) || canonical.providerEffectRealityRevision < 0) throw exposureError("MOVIE_MENTOR_CREATOR_HTTP_EXPOSURE_CANONICAL_AUTHORITY_REQUIRED", "Creator HTTP exposure could not independently prove current canonical result authority.");
  const body = authorized?.body && typeof authorized.body === "object" ? authorized.body : {}, authority = authorized?.authority;
  const expected = { projectId: cleanString(authority?.projectId), principalId: cleanString(authority?.principalId), creatorTurnId: cleanString(body.creatorTurnId), requestDigest: buildRequestDigest({ creatorMessage: cleanString(body?.input?.message || body?.message || ""), projectId: cleanString(authority?.projectId), options: body?.options || {} }) };
  for (const field of ["projectId", "principalId", "creatorTurnId", "requestDigest"]) if (!expected[field] || cleanString(canonical[field]) !== expected[field]) throw exposureError("MOVIE_MENTOR_CREATOR_HTTP_EXPOSURE_BINDING_INVALID", "Creator HTTP exposure canonical proof does not bind the exact authenticated creator request universe.", { field, expected: expected[field] || null, actual: cleanString(canonical[field]) || null });
  if (cleanString(runtimeProof.executionId) !== cleanString(canonical.executionId) || cleanString(runtimeProof.resultReference) !== cleanString(canonical.resultReference) || cleanString(runtimeProof.resultDigest) !== cleanString(canonical.resultDigest) || cleanString(runtimeProof.reservationId) !== cleanString(canonical.reservationId) || cleanString(runtimeProof.closureCertificateDigest) !== cleanString(canonical.closureCertificateDigest)) throw exposureError("MOVIE_MENTOR_CREATOR_HTTP_EXPOSURE_RUNTIME_BINDING_INVALID", "Creator HTTP exposure runtime result does not bind the current canonical result reread by the gateway.");
  const payload = creatorPayloadFromRuntimeResult(result);
  if (digest(payload) !== cleanString(canonical.resultDigest) || digest(canonical.resultPayload) !== cleanString(canonical.resultDigest)) throw exposureError("MOVIE_MENTOR_CREATOR_HTTP_EXPOSURE_DIGEST_INVALID", "Creator HTTP exposure payload does not match the exact current canonical result digest.");
  const settlement = await inferenceSettlementAuthority.reconcile({ executionId: canonical.executionId });
  if (settlement?.authorized !== true || settlement?.settled !== true || settlement?.outcome !== "consumed" || settlement?.resultFinalizationVerified !== true || cleanString(settlement?.executionPhase) !== "settled" || !Number.isSafeInteger(settlement?.providerEffectRealityRevision) || settlement.providerEffectRealityRevision < 0) throw exposureError("MOVIE_MENTOR_CREATOR_HTTP_EXPOSURE_SETTLEMENT_AUTHORITY_REQUIRED", "Creator HTTP exposure could not independently prove current settled consume authority.");
  for (const field of ["executionId", "principalId", "projectId", "reservationId", "resultReference", "resultDigest", "closureCertificateDigest"]) if (!cleanString(settlement?.[field]) || cleanString(settlement[field]) !== cleanString(canonical[field])) throw exposureError("MOVIE_MENTOR_CREATOR_HTTP_EXPOSURE_SETTLEMENT_BINDING_INVALID", "Creator HTTP exposure settlement does not bind the exact current canonical result universe.", { field });
  if (settlement.providerEffectRealityRevision !== canonical.providerEffectRealityRevision) throw exposureError("MOVIE_MENTOR_CREATOR_HTTP_EXPOSURE_SETTLEMENT_BINDING_INVALID", "Creator HTTP exposure settlement does not preserve the canonical provider-effect reality revision.", { field: "providerEffectRealityRevision" });
  return true;
}

function statusForCode(code) {
  if (code === "MOVIE_MENTOR_INFERENCE_SPEND_RESERVATION_DENIED") return 402;
  if (code === "MOVIE_MENTOR_AUTH_CREDENTIAL_REQUIRED" || code === "MOVIE_MENTOR_AUTH_BEARER_REQUIRED" || code.includes("TOKEN_VERIFICATION_FAILED") || code.includes("AUTH_EXPIRED") || code.includes("AUTH_REVOKED")) return 401;
  if (code === "MOVIE_MENTOR_CREATOR_PROJECT_NOT_AUTHORIZED" || code === "MOVIE_MENTOR_INFERENCE_SERVER_PROJECT_CONFLICT") return 403;
  if (code === "MOVIE_MENTOR_CREATOR_PROJECT_REQUIRED" || code === "MOVIE_MENTOR_TURN_MESSAGE_REQUIRED" || code === "MOVIE_MENTOR_CREATOR_TURN_ID_REQUIRED") return 400;
  if (code === "MOVIE_MENTOR_CREATOR_STATE_NOT_FOUND") return 404;
  if (code === "MOVIE_MENTOR_INFERENCE_EXECUTION_ABORTED" || code === "MOVIE_MENTOR_INFERENCE_EXECUTION_QUARANTINED") return 409;
  if (code.includes("CONFLICT")) return 409;
  if (code.includes("INFERENCE_EXECUTION_UNRESOLVED") || code.includes("SETTLEMENT_RECONCILIATION") || code.includes("RELEASE_RECONCILIATION") || code.includes("REPLAY_PENDING") || code.includes("RECOVERY_REQUIRED")) return 503;
  if (code.includes("CANONICAL_RESULT") || code.includes("RESULT_CANDIDATE") || code.includes("INFERENCE_EXECUTION_CLOSURE")) return 503;
  if (code.includes("NOT_CONFIGURED") || code.includes("UNAVAILABLE") || code.includes("AUTHORITY_REQUIRED") || code.includes("CURRENT_OWNERSHIP_REQUIRED") || code.includes("CURRENT_CONSUMPTION_OWNERSHIP_REQUIRED") || code.includes("OWNERSHIP_CHANGED")) return 503;
  if (code === "MOVIE_MENTOR_TURN_SEMANTIC_CONTRACT_MISSING" || code === "MOVIE_MENTOR_TURN_SYNTHESIS_CONTRACT_MISSING") return 502;
  if (code.includes("TIMEOUT")) return 504;
  if (code.includes("RATE_LIMIT")) return 503;
  if (code.includes("AUTHENTICATION") || code.includes("INVALID_MODEL")) return 502;
  if (code.includes("INVALID") || code.includes("REQUIRED") || code.includes("INJECTION") || code.includes("NOT_AUTHORIZED") || code.includes("EMPTY")) return 422;
  return 502;
}
const authorityFlags = Object.freeze({ authenticatedProjectOwnershipRequired:true,runtimeRevalidatesServerProjectAuthority:true,terminalReplayBeforeMutableStateRead:true,projectIdIsReferenceNotAuthority:true,sessionIdCannotAuthorizeProject:true,sessionIdCannotAuthorizeCreatorStateMutation:true,sessionIdCannotAuthorizeCreatorStateConsumption:true,serverSideDurableContextRequired:true,clientSuppliedAuthorityFieldsRejected:true,creatorStateMutationRequiresFreshRequestAuthority:true,creatorStateTransitionOwnsMutationProof:true,creatorStateStoreOwnsMutationProof:true,creatorStateConsumptionRequiresFreshRequestAuthority:true,creatorStatePromotionOwnsConsumptionProof:true,providerDispatchOwnsConsumptionProof:true,forwardExecutionReacquisitionRequiresFreshOwnership:true,historicalExecutionCannotMintSuccessorAuthority:true,inferenceSpendReservationRequired:true,durableReservationRehydrationRequired:true,creatorTurnConvergenceRequired:true,clientCannotManufactureSpendAuthority:true,durableExecutionLeaseRequired:true,providerCallAdmissionRequired:true,providerUnknownBeforeNetworkRequired:true,providerDispatchFreshFenceRequired:true,providerEffectEvidenceCapabilityRequired:true,durableResultCandidateRequired:true,durableClosureRequired:true,currentProviderRealityRequired:true,canonicalResultRequired:true,resultFinalizationRequired:true,settledExecutionAuthorityRequired:true,settlementTransitionsFinalizedToSettledAtomically:true,deterministicSettlementRequired:true,atomicUnclaimedReleaseRequired:true,atomicUnboundReleaseRequired:true,reservationExecutionBindingRequired:true,processLocalClaimCountCannotAuthorizeRelease:true,processLocalExecutionAbsenceCannotAuthorizeRelease:true,clientCannotManufactureExecutionAuthority:true,quarantinedExecutionIsNonRetryableConflict:true,clientSuppliedMemoryIsNotAuthoritative:true,optimisticRevisionRequired:true,creatorTruthDominates:true,validatedSemanticsOutrankSpecialists:true,specialistsRemainProvisional:true,specialistsMaySpeakDirectlyToCreator:false,singleCreatorFacingMentor:true,creatorHttpExposureAuthorityRequired:true,creatorHttpExposureRereadsCanonicalReality:true,creatorHttpExposureRereconcilesSettlement:true,mayAdvanceJourney:false });
function failure(res,error){const code=cleanString(error?.code)||"MOVIE_MENTOR_TURN_FAILED";return res.status(statusForCode(code)).json({success:false,code,message:error instanceof Error?error.message:"Movie Mentor request failed.",validationIssues:Array.isArray(error?.validationIssues)?error.validationIssues:[],retryable:error?.retryable===true,authority:authorityFlags});}

function createMovieMentorTurnRouter({requestAuthority=null,inferenceSpendAuthority=null,inferenceExecutionAuthority=null,inferenceSettlementAuthority=null,runTurn=runMovieMentorTurnWithForwardExecutionAuthority,applyStateTransition=applyMovieMentorCreatorStateTransition}={}){
  if(typeof requestAuthority?.authorize!=="function"){const e=new Error("Movie Mentor turn gateway requires creator request authority before route construction.");e.code="MOVIE_MENTOR_CREATOR_REQUEST_AUTHORITY_REQUIRED";throw e;}
  if(typeof inferenceSpendAuthority?.reserveTurn!=="function"||typeof inferenceSpendAuthority?.readReservation!=="function"){const e=new Error("Movie Mentor turn gateway requires durable reservation and rehydration authority before route construction.");e.code="MOVIE_MENTOR_INFERENCE_SPEND_AUTHORITY_REQUIRED";throw e;}
  if(typeof inferenceExecutionAuthority?.findExecutionByCreatorTurn!=="function"||typeof inferenceExecutionAuthority?.openExecution!=="function"||typeof inferenceExecutionAuthority?.acquireExecution!=="function"||typeof inferenceExecutionAuthority?.assertFence!=="function"||typeof inferenceExecutionAuthority?.claimProviderCall!=="function"||typeof inferenceExecutionAuthority?.beginProviderDispatch!=="function"||typeof inferenceExecutionAuthority?.assertProviderDispatch!=="function"||typeof inferenceExecutionAuthority?.contributeProviderEffectEvidence!=="function"||typeof inferenceExecutionAuthority?.stageResultCandidate!=="function"||typeof inferenceExecutionAuthority?.readResultCandidate!=="function"||typeof inferenceExecutionAuthority?.beginExecutionClosing!=="function"||typeof inferenceExecutionAuthority?.reconcileExecutionClosure!=="function"||typeof inferenceExecutionAuthority?.assertCurrentExecutionClosure!=="function"||typeof inferenceExecutionAuthority?.commitCanonicalResult!=="function"||typeof inferenceExecutionAuthority?.readCanonicalResult!=="function"){const e=new Error("Movie Mentor turn gateway requires complete lease, provider-effect dispatch, result staging, closure, current-reality and canonical-result authority before route construction.");e.code="MOVIE_MENTOR_PROVIDER_EFFECT_AUTHORITY_REQUIRED";throw e;}
  if(typeof inferenceSettlementAuthority?.reconcile!=="function"||typeof inferenceSettlementAuthority?.releaseUnclaimed!=="function"||typeof inferenceSettlementAuthority?.releaseUnbound!=="function"){const e=new Error("Movie Mentor turn gateway requires deterministic SETTLED consume plus atomic unclaimed and unbound release authority before route construction.");e.code="MOVIE_MENTOR_INFERENCE_SETTLEMENT_RECONCILIATION_AUTHORITY_REQUIRED";throw e;}
  if(typeof runTurn!=="function"||typeof applyStateTransition!=="function"){const e=new Error("Movie Mentor turn gateway requires turn and state-transition handlers.");e.code="MOVIE_MENTOR_TURN_GATEWAY_HANDLERS_REQUIRED";throw e;}
  const router=express.Router();
  const authorize=async req=>{const body=req.body&&typeof req.body==="object"?req.body:{},projectId=cleanString(body.projectId),authority=await requestAuthority.authorize({request:req,projectId});if(authority?.authorized!==true||cleanString(authority.projectId)!==projectId){const e=new Error("Creator request authority did not authorize the requested project.");e.code="MOVIE_MENTOR_CREATOR_PROJECT_NOT_AUTHORIZED";throw e;}return{body:{...body,projectId:authority.projectId},authority};};
  const serverAuthorityFrom=authority=>Object.freeze({authenticated:true,projectAuthorized:true,principalId:cleanString(authority?.principalId),projectId:cleanString(authority?.projectId),ownershipRef:cleanString(authority?.ownershipRef)||null,ownershipRevision:Number.isSafeInteger(authority?.ownershipRevision)?authority.ownershipRevision:null,authorizationSource:cleanString(authority?.authorizationSource)||null});
  const mutationAuthorityFrom=(req,authorized)=>createMovieMentorCreatorStateMutationAuthority({request:req,authorization:authorized.authority,requestAuthority});
  const consumptionAuthorityFrom=(req,authorized)=>createMovieMentorCreatorStateConsumptionAuthority({request:req,authorization:authorized.authority,requestAuthority});
  const forwardExecutionAuthorityFrom=(req,authorized)=>createMovieMentorForwardExecutionAuthority({request:req,authorization:authorized.authority,requestAuthority});
  router.get("/health",(_req,res)=>res.json({success:true,service:"movie-mentor-turn-gateway",version:MOVIE_MENTOR_TURN_GATEWAY_VERSION,runtimeVersion:MOVIE_MENTOR_TURN_RUNTIME_VERSION,creatorStateTransitionVersion:MOVIE_MENTOR_CREATOR_STATE_TRANSITION_VERSION,orchestratorVersion:MOVIE_MENTOR_TURN_ORCHESTRATOR_VERSION,contractVersion:MOVIE_MENTOR_TURN_CONTRACT_VERSION,wiring:{creatorAuthentication:true,projectOwnership:true,runtimeServerAuthorityBinding:true,terminalReplayBeforeMutableStateRead:true,durableCreatorState:true,durableCreatorStateWrites:true,creatorStateMutationCurrentOwnership:true,creatorStateStoreMutationRevalidation:true,creatorStateConsumptionCurrentOwnership:true,creatorStatePromotionReauthorization:true,providerDispatchOwnershipReauthorization:true,forwardExecutionReacquisitionCurrentOwnership:true,historicalExecutionCannotMintSuccessorAuthority:true,authoritativeTurnContext:true,inferenceSpendAuthority:true,durableReservationRehydration:true,creatorTurnConvergence:true,inferenceExecutionLease:true,providerCallAdmission:true,providerUnknownBeforeNetwork:true,providerDispatchFreshFence:true,providerEffectEvidence:true,durableResultCandidate:true,durableClosure:true,currentProviderReality:true,canonicalResult:true,resultFinalization:true,settledExecutionAuthority:true,atomicFinalizedToSettledSettlement:true,deterministicSettlement:true,atomicUnclaimedRelease:true,atomicUnboundRelease:true,reservationExecutionBinding:true,quarantinedExecutionFailClosed:true,creatorHttpExposureAuthority:true,semantic:true,specialists:true,synthesis:true},creatorStateStore:getMovieMentorCreatorStateStoreStatus(),authority:authorityFlags}));
  router.post("/state/sync",async(req,res)=>{try{const authorized=await authorize(req),creatorStateMutationAuthority=mutationAuthorityFrom(req,authorized),state=await applyStateTransition(authorized.body,{creatorStateMutationAuthority});return res.json({success:true,status:"creator-state-synced",state,metadata:{turnGatewayVersion:MOVIE_MENTOR_TURN_GATEWAY_VERSION,creatorStateTransitionVersion:MOVIE_MENTOR_CREATOR_STATE_TRANSITION_VERSION,ownershipRef:authorized.authority.ownershipRef||null}});}catch(error){return failure(res,error);}});
  router.post("/turn",async(req,res)=>{try{const authorized=await authorize(req),creatorStateMutationAuthority=mutationAuthorityFrom(req,authorized),creatorStateConsumptionAuthority=consumptionAuthorityFrom(req,authorized),forwardExecutionAuthority=forwardExecutionAuthorityFrom(req,authorized),commitDecision=(input,deps={})=>commitCreatorDecision(input,{...deps,creatorStateMutationAuthority}),result=await runTurn(authorized.body,{serverAuthority:serverAuthorityFrom(authorized.authority),inferenceSpendAuthority,inferenceExecutionAuthority,inferenceSettlementAuthority,creatorStateMutationAuthority,creatorStateConsumptionAuthority,forwardExecutionAuthority,commitCreatorDecision:commitDecision});await assertCreatorHttpExposureAuthority({result,authorized,inferenceExecutionAuthority,inferenceSettlementAuthority});return res.json({...result,metadata:{...(result.metadata||{}),turnGatewayVersion:MOVIE_MENTOR_TURN_GATEWAY_VERSION,turnRuntimeVersion:MOVIE_MENTOR_TURN_RUNTIME_VERSION,ownershipRef:authorized.authority.ownershipRef||null}});}catch(error){return failure(res,error);}});
  return router;
}
export{MOVIE_MENTOR_TURN_GATEWAY_VERSION,assertCreatorHttpExposureAuthority,createMovieMentorTurnRouter};export default createMovieMentorTurnRouter;
