import express from "express";
import { synthesizeMovieMentorResponse, MOVIE_MENTOR_SYNTHESIS_VERSION, MENTOR_SYNTHESIS_CONTRACT_VERSION } from "./ai/MovieMentorSynthesisEngine.js";
import { getStructuredAIProviderConfig, getStructuredAIProviderConfigurationIssues } from "./ai/StructuredAIProviderClient.js";
const router=express.Router(); const SYNTHESIS_GATEWAY_VERSION="1.0.0";
function cleanString(v){return typeof v==="string"?v.trim():"";}
function statusForCode(code){if(code==="MENTOR_SYNTHESIS_REQUEST_INVALID")return 400;if(code==="MENTOR_SYNTHESIS_BLOCKED_BY_CLARIFICATION")return 409;if(code==="AI_PROVIDER_NOT_CONFIGURED")return 503;if(code==="AI_PROVIDER_TIMEOUT")return 504;if(code==="AI_PROVIDER_RATE_LIMITED"||code==="AI_PROVIDER_UNAVAILABLE")return 503;if(code==="AI_PROVIDER_AUTHENTICATION_FAILED"||code==="AI_PROVIDER_INVALID_MODEL")return 502;if(code==="MENTOR_SYNTHESIS_OUTPUT_INVALID")return 422;return 502;}
router.get("/health",(req,res)=>{const c=getStructuredAIProviderConfig();const issues=getStructuredAIProviderConfigurationIssues(c);return res.json({success:true,service:"movie-mentor-synthesis-gateway",version:SYNTHESIS_GATEWAY_VERSION,synthesisVersion:MOVIE_MENTOR_SYNTHESIS_VERSION,contractVersion:MENTOR_SYNTHESIS_CONTRACT_VERSION,configured:issues.length===0,providerName:c.provider||null,model:c.model||null,configurationIssues:issues,authority:{creatorTruthDominates:true,validatedSemanticsOutrankSpecialists:true,specialistsRemainProvisional:true,specialistContentBecomesCanonicalTruth:false,mayAdvanceJourney:false,singleCreatorFacingMentor:true}});});
router.post("/synthesize",async(req,res)=>{try{const result=await synthesizeMovieMentorResponse(req.body&&typeof req.body==="object"?req.body:{});return res.json({...result,metadata:{...(result.metadata||{}),synthesisGatewayVersion:SYNTHESIS_GATEWAY_VERSION}});}catch(error){const code=cleanString(error?.code)||"MENTOR_SYNTHESIS_FAILED";return res.status(statusForCode(code)).json({success:false,code,message:error instanceof Error?error.message:"Mentor synthesis failed.",validationIssues:Array.isArray(error?.validationIssues)?error.validationIssues:[],retryable:error?.retryable===true,authority:{creatorTruthDominates:true,validatedSemanticsOutrankSpecialists:true,specialistsRemainProvisional:true,specialistContentBecomesCanonicalTruth:false,mayAdvanceJourney:false,singleCreatorFacingMentor:true}});}});
export {SYNTHESIS_GATEWAY_VERSION}; export default router;
