import express from "express";
import { MOVIE_MENTOR_TURN_ORCHESTRATOR_VERSION, MOVIE_MENTOR_TURN_CONTRACT_VERSION } from "./ai/MovieMentorTurnOrchestrator.js";
import { runMovieMentorTurn, MOVIE_MENTOR_TURN_RUNTIME_VERSION } from "./ai/MovieMentorTurnRuntime.js";
import { getMovieMentorCreatorStateStoreStatus } from "./ai/MovieMentorCreatorStateStore.js";
import { applyMovieMentorCreatorStateTransition, MOVIE_MENTOR_CREATOR_STATE_TRANSITION_VERSION } from "./ai/MovieMentorCreatorStateTransition.js";

const MOVIE_MENTOR_TURN_GATEWAY_VERSION="1.5.0";
function cleanString(value){return typeof value==="string"?value.trim():"";}
function statusForCode(code){
 if(code==="MOVIE_MENTOR_INFERENCE_SPEND_RESERVATION_DENIED")return 402;
 if(code==="MOVIE_MENTOR_AUTH_CREDENTIAL_REQUIRED"||code==="MOVIE_MENTOR_AUTH_BEARER_REQUIRED"||code.includes("TOKEN_VERIFICATION_FAILED")||code.includes("AUTH_EXPIRED")||code.includes("AUTH_REVOKED"))return 401;
 if(code==="MOVIE_MENTOR_CREATOR_PROJECT_NOT_AUTHORIZED")return 403;
 if(code==="MOVIE_MENTOR_CREATOR_PROJECT_REQUIRED"||code==="MOVIE_MENTOR_TURN_MESSAGE_REQUIRED"||code==="MOVIE_MENTOR_CREATOR_TURN_ID_REQUIRED")return 400;
 if(code==="MOVIE_MENTOR_CREATOR_STATE_NOT_FOUND")return 404;
 if(code==="MOVIE_MENTOR_CREATOR_STATE_REVISION_CONFLICT"||code==="MOVIE_MENTOR_TURN_CONTEXT_NOT_AUTHORITATIVE"||code==="MOVIE_MENTOR_TURN_CONTEXT_MESSAGE_MISMATCH"||code==="MOVIE_MENTOR_INFERENCE_SPEND_PROJECT_CONFLICT"||code==="MOVIE_MENTOR_INFERENCE_SPEND_RESERVATION_CONFLICT"||code==="MOVIE_MENTOR_INFERENCE_EXECUTION_TURN_IDENTITY_CONFLICT")return 409;
 if(code.includes("INFERENCE_EXECUTION_UNRESOLVED"))return 503;
 if(code==="MOVIE_MENTOR_CREATOR_STATE_STORE_NOT_CONFIGURED"||code==="MOVIE_MENTOR_CREATOR_STATE_STORE_UNAVAILABLE"||code==="MOVIE_MENTOR_INFERENCE_SPEND_AUTHORITY_REQUIRED"||code==="MOVIE_MENTOR_INFERENCE_SPEND_AUTHORITY_NOT_READY"||code==="MOVIE_MENTOR_INFERENCE_SPEND_AUTHORITY_UNAVAILABLE"||code==="MOVIE_MENTOR_INFERENCE_SPEND_STORE_NOT_CONFIGURED"||code==="MOVIE_MENTOR_INFERENCE_EXECUTION_AUTHORITY_REQUIRED")return 503;
 if(code==="MOVIE_MENTOR_TURN_SEMANTIC_CONTRACT_MISSING"||code==="MOVIE_MENTOR_TURN_SYNTHESIS_CONTRACT_MISSING")return 502;
 if(code.includes("TIMEOUT"))return 504;if(code.includes("RATE_LIMIT")||code.includes("UNAVAILABLE")||code.includes("NOT_CONFIGURED"))return 503;if(code.includes("AUTHENTICATION")||code.includes("INVALID_MODEL"))return 502;if(code.includes("INVALID")||code.includes("REQUIRED")||code.includes("INJECTION")||code.includes("NOT_AUTHORIZED")||code.includes("EMPTY"))return 422;return 502;
}
function failure(res,error){const code=cleanString(error?.code)||"MOVIE_MENTOR_TURN_FAILED";return res.status(statusForCode(code)).json({success:false,code,message:error instanceof Error?error.message:"Movie Mentor request failed.",validationIssues:Array.isArray(error?.validationIssues)?error.validationIssues:[],retryable:error?.retryable===true,authority:{authenticatedProjectOwnershipRequired:true,projectIdIsReferenceNotAuthority:true,sessionIdCannotAuthorizeProject:true,serverSideDurableContextRequired:true,clientSuppliedAuthorityFieldsRejected:true,inferenceSpendReservationRequired:true,clientCannotManufactureSpendAuthority:true,durableExecutionLeaseRequired:true,providerCallAdmissionRequired:true,clientCannotManufactureExecutionAuthority:true,clientSuppliedMemoryIsNotAuthoritative:true,optimisticRevisionRequired:true,creatorTruthDominates:true,validatedSemanticsOutrankSpecialists:true,specialistsRemainProvisional:true,specialistsMaySpeakDirectlyToCreator:false,singleCreatorFacingMentor:true,mayAdvanceJourney:false}});}

function createMovieMentorTurnRouter({requestAuthority=null,inferenceSpendAuthority=null,inferenceExecutionAuthority=null,runTurn=runMovieMentorTurn,applyStateTransition=applyMovieMentorCreatorStateTransition}={}){
 if(typeof requestAuthority?.authorize!=="function"){const error=new Error("Movie Mentor turn gateway requires creator request authority before route construction.");error.code="MOVIE_MENTOR_CREATOR_REQUEST_AUTHORITY_REQUIRED";throw error;}
 if(typeof inferenceSpendAuthority?.reserveTurn!=="function"){const error=new Error("Movie Mentor turn gateway requires durable inference spend authority before route construction.");error.code="MOVIE_MENTOR_INFERENCE_SPEND_AUTHORITY_REQUIRED";throw error;}
 if(typeof inferenceExecutionAuthority?.openExecution!=="function"||typeof inferenceExecutionAuthority?.claimProviderCall!=="function"){const error=new Error("Movie Mentor turn gateway requires durable inference execution lease authority before route construction.");error.code="MOVIE_MENTOR_INFERENCE_EXECUTION_AUTHORITY_REQUIRED";throw error;}
 if(typeof runTurn!=="function"||typeof applyStateTransition!=="function"){const error=new Error("Movie Mentor turn gateway requires turn and state-transition handlers.");error.code="MOVIE_MENTOR_TURN_GATEWAY_HANDLERS_REQUIRED";throw error;}
 const router=express.Router();
 const authorize=async(req)=>{const body=req.body&&typeof req.body==="object"?req.body:{};const projectId=cleanString(body.projectId);const authority=await requestAuthority.authorize({request:req,projectId});if(authority?.authorized!==true||cleanString(authority.projectId)!==projectId){const error=new Error("Creator request authority did not authorize the requested project.");error.code="MOVIE_MENTOR_CREATOR_PROJECT_NOT_AUTHORIZED";throw error;}return{body:{...body,projectId:authority.projectId},authority};};
 const serverAuthorityFrom=(authority)=>Object.freeze({authenticated:true,projectAuthorized:true,principalId:cleanString(authority?.principalId),projectId:cleanString(authority?.projectId),ownershipRef:cleanString(authority?.ownershipRef)||null,ownershipRevision:Number.isSafeInteger(authority?.ownershipRevision)?authority.ownershipRevision:null,authorizationSource:cleanString(authority?.authorizationSource)||null});
 router.get("/health",(req,res)=>res.json({success:true,service:"movie-mentor-turn-gateway",version:MOVIE_MENTOR_TURN_GATEWAY_VERSION,runtimeVersion:MOVIE_MENTOR_TURN_RUNTIME_VERSION,creatorStateTransitionVersion:MOVIE_MENTOR_CREATOR_STATE_TRANSITION_VERSION,orchestratorVersion:MOVIE_MENTOR_TURN_ORCHESTRATOR_VERSION,contractVersion:MOVIE_MENTOR_TURN_CONTRACT_VERSION,wiring:{creatorAuthentication:true,projectOwnership:true,durableCreatorState:true,durableCreatorStateWrites:true,authoritativeTurnContext:true,inferenceSpendAuthority:true,inferenceExecutionLease:true,providerCallAdmission:true,semantic:true,specialists:true,synthesis:true},creatorStateStore:getMovieMentorCreatorStateStoreStatus(),authority:{authenticatedProjectOwnershipRequired:true,projectIdIsReferenceNotAuthority:true,sessionIdCannotAuthorizeProject:true,serverSideDurableContextRequired:true,clientSuppliedAuthorityFieldsRejected:true,inferenceSpendReservationRequired:true,clientCannotManufactureSpendAuthority:true,durableExecutionLeaseRequired:true,providerCallAdmissionRequired:true,clientCannotManufactureExecutionAuthority:true,optimisticRevisionRequired:true,creatorTruthDominates:true,validatedSemanticsOutrankSpecialists:true,specialistsRemainProvisional:true,specialistsMaySpeakDirectlyToCreator:false,singleCreatorFacingMentor:true,mayAdvanceJourney:false}}));
 router.post("/state/sync",async(req,res)=>{try{const authorized=await authorize(req);const state=await applyStateTransition(authorized.body);return res.json({success:true,status:"creator-state-synced",state,metadata:{turnGatewayVersion:MOVIE_MENTOR_TURN_GATEWAY_VERSION,creatorStateTransitionVersion:MOVIE_MENTOR_CREATOR_STATE_TRANSITION_VERSION,ownershipRef:authorized.authority.ownershipRef||null}});}catch(error){return failure(res,error);}});
 router.post("/turn",async(req,res)=>{try{const authorized=await authorize(req);const result=await runTurn(authorized.body,{serverAuthority:serverAuthorityFrom(authorized.authority),inferenceSpendAuthority,inferenceExecutionAuthority});return res.json({...result,metadata:{...(result.metadata||{}),turnGatewayVersion:MOVIE_MENTOR_TURN_GATEWAY_VERSION,turnRuntimeVersion:MOVIE_MENTOR_TURN_RUNTIME_VERSION,ownershipRef:authorized.authority.ownershipRef||null}});}catch(error){return failure(res,error);}});
 return router;
}

export {MOVIE_MENTOR_TURN_GATEWAY_VERSION,createMovieMentorTurnRouter};
export default createMovieMentorTurnRouter;
