import express from "express";
import { MOVIE_MENTOR_SEMANTIC_CONTRACT_VERSION, getMovieMentorSemanticProviderStatus, interpretMovieMentorSemantics } from "./ai/MovieMentorSemanticInterpreter.js";

const router = express.Router();
const SEMANTIC_GATEWAY_VERSION = "2.1.0";
const SEMANTIC_CONTRACT_VERSION = MOVIE_MENTOR_SEMANTIC_CONTRACT_VERSION;
function cleanString(value){return typeof value === "string" ? value.trim() : "";}
function extractCreatorMessage(r){return cleanString(r?.input?.message||r?.message||r?.context?.activeIdea||"");}
function safeProviderStatus(){const p=getMovieMentorSemanticProviderStatus();return {configured:p.configured,readiness:p.readiness,configurationIssues:p.configurationIssues,providerName:p.provider,modelConfigured:p.modelConfigured,model:p.model,baseUrlConfigured:p.baseUrlConfigured,apiKeyConfigured:p.apiKeyConfigured,timeoutMs:p.timeoutMs,requiresKey:p.requiresKey,requiresModel:p.requiresModel,interpreterVersion:p.interpreterVersion,contractVersion:p.contractVersion};}
function statusForCode(code){if(code==="CREATOR_MESSAGE_REQUIRED")return 400;if(code==="SEMANTIC_PROVIDER_NOT_CONFIGURED")return 503;if(code==="SEMANTIC_PROVIDER_AUTHENTICATION_FAILED")return 502;if(code==="SEMANTIC_PROVIDER_INVALID_MODEL")return 502;if(code==="SEMANTIC_PROVIDER_RATE_LIMITED")return 503;if(code==="SEMANTIC_PROVIDER_TIMEOUT")return 504;if(code==="SEMANTIC_PROVIDER_UNAVAILABLE")return 503;if(code==="SEMANTIC_STRUCTURED_OUTPUT_INVALID"||code==="SEMANTIC_INTELLIGENCE_INVALID")return 422;return 502;}
router.get("/health",(req,res)=>res.json({success:true,service:"movie-mentor-semantic-gateway",version:SEMANTIC_GATEWAY_VERSION,...safeProviderStatus(),safety:{preserveCreatorLanguage:true,creatorConfirmedMeaningOutranksInference:true,provisionalInferenceIsNotCreatorTruth:true,unfamiliarTerminologyRequiresClarification:true,doNotGuessMeaning:true,materialAmbiguityBlocksProgression:true,deterministicPlanningIsNotSemanticUnderstanding:true,structuredSemanticIntelligenceRequiredForAdvance:true}}));
router.post("/interpret",async(req,res)=>{const providerRequest=req.body&&typeof req.body==="object"?req.body:{};if(!extractCreatorMessage(providerRequest))return res.status(400).json({success:false,code:"CREATOR_MESSAGE_REQUIRED",message:"A creator message is required for semantic interpretation.",semanticIntelligenceAvailable:false,safety:{mayAdvanceJourney:false}});try{const result=await interpretMovieMentorSemantics(providerRequest);if(!result?.structured?.movieJourneyIntelligence)return res.status(422).json({success:false,code:"SEMANTIC_INTELLIGENCE_MISSING",message:"The semantic interpreter did not return the required structured Movie Journey intelligence contract.",semanticIntelligenceAvailable:false,safety:{doNotGuessMeaning:true,mayAdvanceJourney:false}});return res.json({...result,metadata:{...(result.metadata||{}),semanticGatewayVersion:SEMANTIC_GATEWAY_VERSION,semanticContractVersion:SEMANTIC_CONTRACT_VERSION,semanticIntelligenceAvailable:true}});}catch(error){const code=cleanString(error?.code)||(error?.name==="AbortError"?"SEMANTIC_PROVIDER_TIMEOUT":"SEMANTIC_PROVIDER_FAILED");return res.status(statusForCode(code)).json({success:false,code,message:error instanceof Error?error.message:"Semantic provider failed.",providerFailureCategory:cleanString(error?.providerFailureCategory)||null,retryable:error?.retryable===true,configurationIssues:Array.isArray(error?.configurationIssues)?error.configurationIssues:[],validationIssues:Array.isArray(error?.validationIssues)?error.validationIssues:[],semanticIntelligenceAvailable:false,safety:{preserveCreatorLanguage:true,creatorConfirmedMeaningOutranksInference:true,provisionalInferenceIsNotCreatorTruth:true,unfamiliarTerminologyRequiresClarification:true,doNotGuessMeaning:true,materialAmbiguityBlocksProgression:true,deterministicPlanningIsNotSemanticUnderstanding:true,structuredSemanticIntelligenceRequiredForAdvance:true,mayAdvanceJourney:false}});}});
export { SEMANTIC_GATEWAY_VERSION, SEMANTIC_CONTRACT_VERSION };
export default router;
