const express = require('express');
const cors = require('cors');
const morgan = require('morgan');
require('dotenv').config();
const app = express();
app.use(express.json());
app.use(morgan('dev'));
const allowedOrigin = process.env.CORS_ORIGIN || 'http://localhost:3000';
app.use(cors({ origin: allowedOrigin, credentials: true }));
app.get('/health', (req, res) => res.json({ ok: true, service: 'iband-backend', time: new Date().toISOString() }));
app.use('/api/artists', require('./src/routes/artists'));
app.use('/api/votes', require('./src/routes/votes'));
app.use('/api/comments', require('./src/routes/comments'));
app.use('/api/admin', require('./src/routes/admin'));
app.use((req, res) => res.status(404).json({ error: 'Not Found' }));
app.use((err, req, res, next) => { console.error(err); res.status(500).json({ error: 'Server Error', details: err.message }); });
const PORT = process.env.PORT || 4000;
app.listen(PORT, () => console.log('iBand backend running on port ' + PORT));
