const VERSION="1.0.0",DOMAIN="iband.movie-mentor.commercial-checkout-initiation-authority";
function text(v){return typeof v==="string"?v.trim():"";}
function fail(code,message,extras={}){const e=new Error(message);e.code=code;Object.assign(e,extras);throw e;}
function createMovieMentorCommercialCheckoutInitiationAuthority({resolvePurchaseIntent,createProviderCheckout}={}){
 if(typeof resolvePurchaseIntent!=="function"||typeof createProviderCheckout!=="function")fail("MOVIE_MENTOR_CHECKOUT_AUTHORITY_REQUIRED","Checkout initiation requires durable purchase-intent resolution and explicit provider checkout composition.");
 async function initiateCheckout({principalId,commercialIntentId}={}){const principal=text(principalId),intentId=text(commercialIntentId);if(!principal||!intentId)fail("MOVIE_MENTOR_CHECKOUT_REQUEST_INVALID","Authenticated principal and commercial intent are required.");const intent=await resolvePurchaseIntent({commercialIntentId:intentId});if(!intent||text(intent.commercialIntentId)!==intentId)fail("MOVIE_MENTOR_CHECKOUT_INTENT_NOT_FOUND","Durable commercial purchase intent was not found.");if(text(intent.principalId)!==principal)fail("MOVIE_MENTOR_CHECKOUT_PRINCIPAL_MISMATCH","Authenticated principal does not own this commercial intent.");if(text(intent.status)!=="created")fail("MOVIE_MENTOR_CHECKOUT_INTENT_NOT_CHECKOUT_ELIGIBLE","Commercial intent is not eligible for checkout initiation.");const request=Object.freeze({commercialIntentId:intentId,principalId:principal,packageId:text(intent.packageId),provider:text(intent.provider),providerProductId:text(intent.providerProductId),amountMinor:intent.amountMinor,currency:text(intent.currency).toUpperCase(),environment:text(intent.environment),units:intent.units,policyVersion:text(intent.policyVersion),policyDigest:text(intent.policyDigest)});if(!request.provider||!request.providerProductId||!Number.isSafeInteger(request.amountMinor)||request.amountMinor<0||!request.currency||!request.environment||!Number.isSafeInteger(request.units)||request.units<=0||!request.policyVersion||!request.policyDigest)fail("MOVIE_MENTOR_CHECKOUT_INTENT_INVALID","Durable commercial intent is incomplete.");const checkout=await createProviderCheckout({intent:request});if(!checkout||checkout.authorized!==true||text(checkout.commercialIntentId)!==intentId||text(checkout.provider)!==request.provider||!text(checkout.checkoutReference)||!text(checkout.checkoutUrl))fail("MOVIE_MENTOR_CHECKOUT_PROVIDER_RESPONSE_INVALID","Provider checkout did not return a valid authority-bound session.");return Object.freeze({authorized:true,commercialIntentId:intentId,provider:request.provider,checkoutReference:text(checkout.checkoutReference),checkoutUrl:text(checkout.checkoutUrl),expiresAt:text(checkout.expiresAt)||null});}
 return Object.freeze({initiateCheckout});
}
export{VERSION as MOVIE_MENTOR_COMMERCIAL_CHECKOUT_INITIATION_AUTHORITY_VERSION,DOMAIN as MOVIE_MENTOR_COMMERCIAL_CHECKOUT_INITIATION_AUTHORITY_DOMAIN,createMovieMentorCommercialCheckoutInitiationAuthority};export default createMovieMentorCommercialCheckoutInitiationAuthority;
