import { createHash, randomUUID } from "node:crypto";
import { applyMovieMentorCreatorStateTransition } from "./MovieMentorCreatorStateTransition.js";
import { readAuthoritativeTurnSource } from "./MovieMentorCreatorStateStore.js";

const MOVIE_MENTOR_CREATOR_DECISION_AUTHORITY_VERSION="1.0.0";
const CREATOR_DECISION_DOMAIN="iband.movie-mentor.creator-decision";
const CREATOR_DECISION_SCHEMA=1;
function s(v){return typeof v==="string"?v.trim():"";}
function a(v){return Array.isArray(v)?v:[];}
function clone(v){if(v===undefined)return undefined;try{return JSON.parse(JSON.stringify(v));}catch{return v;}}
function stable(v){if(v===null||typeof v!=="object")return JSON.stringify(v);if(Array.isArray(v))return `[${v.map(stable).join(",")}]`;return `{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${stable(v[k])}`).join(",")}}`;}
function digest(v){return createHash("sha256").update(stable(v)).digest("hex");}
function error(code,message,issues=[]){const e=new Error(message);e.code=code;e.validationIssues=issues;return e;}
function commitmentIntent(message){const m=s(message);if(!m)return null;if(/\b(?:maybe|perhaps|might|could|thinking about|let me think|not sure)\b/i.test(m))return null;if(/\b(?:actually\s+)?(?:scrap|drop|remove|replace|change)\b/i.test(m))return "correction";if(/\b(?:yes[,. ]*)?(?:let['’]?s|we(?:'ll| will)|i(?:'ll| will)|definitely)\s+(?:use|go with|choose|keep|make|set|adopt)\b/i.test(m))return "adoption";if(/^\s*(?:yes|yeah|yep)[.!]?\s*(?:do|use|go with)\s+that\b/i.test(m))return "adoption";return null;}
function resolvedReferences(semantic={}){return a(semantic?.continuationReferences).filter(r=>r?.status==="resolved"&&s(r?.expression));}
function explicitCreatorItems(semantic={}){return a(semantic?.understoodContext).filter(i=>i?.confidenceSource==="creator-explicit"&&s(i?.key));}
function decisionKeyFor({reference,item,intent}){if(reference)return `continuation.${s(reference.type)||"reference"}`;if(item)return `semantic.${s(item.key)}`;return `creator.${intent||"decision"}`;}
function buildCreatorDecisionCandidate({creatorMessage,semanticIntelligence={},projectId=null,actorRole="creator"}={}){
 const message=s(creatorMessage);if(actorRole!=="creator")return {status:"rejected",reason:"creator_origin_required"};const intent=commitmentIntent(message);if(!intent)return {status:"none",reason:"no_explicit_creator_commitment"};
 const refs=resolvedReferences(semanticIntelligence);const explicit=explicitCreatorItems(semanticIntelligence);let reference=null,item=null,value=null,evidenceSource=null;
 if(refs.length===1){reference=clone(refs[0]);value=clone(reference.resolvedValue);evidenceSource="validated-continuation-reference";}
 else if(refs.length>1)return {status:"rejected",reason:"multiple_resolved_references_require_specificity"};
 else if(explicit.length===1){item=clone(explicit[0]);value=clone(item.value);evidenceSource="creator-explicit-semantic";}
 else if(explicit.length>1)return {status:"rejected",reason:"multiple_creator_explicit_items_require_specificity"};
 else return {status:"rejected",reason:"explicit_commitment_lacks_resolved_value"};
 const decisionKey=decisionKeyFor({reference,item,intent});const decisionId=randomUUID();const candidate={domain:CREATOR_DECISION_DOMAIN,schema:CREATOR_DECISION_SCHEMA,decisionId,projectId:s(projectId)||null,decisionKey,intent,value,creatorMessage:message,evidenceSource,reference:reference?{expression:reference.expression,type:reference.type,resolvedValue:clone(reference.resolvedValue),source:reference.source||null}:null,semanticKey:item?.key||null,authority:"creator-explicit",createdAt:new Date().toISOString()};candidate.fingerprint=digest(candidate);return {status:"candidate",candidate};
}
function mergeDecisionIntoCreatorContext(current=[],candidate){const retained=[];for(const item of a(current)){if(s(item?.decisionKey)===candidate.decisionKey)retained.push({...clone(item),current:false,supersededByDecisionId:candidate.decisionId});else retained.push(clone(item));}retained.push({key:`creatorDecision.${candidate.decisionKey}`,value:clone(candidate.value),authority:"creator",confidenceSource:"creator-confirmed",decisionKey:candidate.decisionKey,decisionId:candidate.decisionId,decisionFingerprint:candidate.fingerprint,decisionIntent:candidate.intent,evidence:candidate.creatorMessage,evidenceSource:candidate.evidenceSource,current:true,createdAt:candidate.createdAt});return retained;}
async function commitCreatorDecision({candidate,expectedRevision,projectId,creatorSessionId=null}={},deps={}){if(!candidate||candidate.domain!==CREATOR_DECISION_DOMAIN||candidate.schema!==CREATOR_DECISION_SCHEMA||candidate.authority!=="creator-explicit")throw error("MOVIE_MENTOR_CREATOR_DECISION_INVALID","Creator decision candidate is not authoritative.");if(s(candidate.projectId)&&s(projectId)&&s(candidate.projectId)!==s(projectId))throw error("MOVIE_MENTOR_CREATOR_DECISION_PROJECT_MISMATCH","Creator decision belongs to another project.");const read=deps.readAuthoritativeTurnSource||readAuthoritativeTurnSource;const transition=deps.applyMovieMentorCreatorStateTransition||applyMovieMentorCreatorStateTransition;const identity={projectId:s(projectId)||s(candidate.projectId)||null,creatorSessionId:s(creatorSessionId)||null};const before=await read(identity);if(before.revision!==expectedRevision)throw error("MOVIE_MENTOR_CREATOR_DECISION_REVISION_CONFLICT","Creator decision was based on stale creator reality.");const merged=mergeDecisionIntoCreatorContext(before.creatorConfirmedContext,candidate);const written=await transition({projectId:identity.projectId,creatorSessionId:identity.creatorSessionId,source:"creator-decision",expectedRevision,state:{creatorConfirmedContext:merged}},{readAuthoritativeTurnSource:read,writeAuthoritativeCreatorState:deps.writeAuthoritativeCreatorState});const after=await read(identity);const committed=a(after.creatorConfirmedContext).find(i=>i?.decisionId===candidate.decisionId&&i?.current===true);if(!committed||committed.decisionFingerprint!==candidate.fingerprint||after.revision!==written.revision)throw error("MOVIE_MENTOR_CREATOR_DECISION_READBACK_FAILED","Durable creator decision readback did not prove the committed decision.");return {status:"committed",candidate:clone(candidate),revision:after.revision,creatorStateGeneration:after.creatorStateGeneration,committedContext:clone(committed)};}

export{MOVIE_MENTOR_CREATOR_DECISION_AUTHORITY_VERSION,CREATOR_DECISION_DOMAIN,CREATOR_DECISION_SCHEMA,commitmentIntent,buildCreatorDecisionCandidate,mergeDecisionIntoCreatorContext,commitCreatorDecision};
export default buildCreatorDecisionCandidate;
