const MOVIE_MENTOR_SEMANTIC_INTERPRETER_VERSION = "1.3.2";
const MOVIE_MENTOR_SEMANTIC_CONTRACT_VERSION = "1.3.2";

function cleanString(value) { return typeof value === "string" ? value.trim() : ""; }
function asArray(value) { return Array.isArray(value) ? value : []; }
function cloneValue(value) { if (value === undefined) return undefined; try { return JSON.parse(JSON.stringify(value)); } catch { return value; } }
function stableValue(value) { try { return JSON.stringify(value); } catch { return String(value); } }

const CONTEXT_ITEM_SCHEMA = { type:"object", additionalProperties:false, properties:{ key:{type:["string","null"]}, value:{type:["string","null"]}, evidence:{type:["string","null"]}, confidenceSource:{type:"string",enum:["creator-confirmed","creator-explicit","model-provisional"]}}, required:["key","value","evidence","confidenceSource"] };
const MOVIE_JOURNEY_INTELLIGENCE_SCHEMA = { type:"object", additionalProperties:false, properties:{ understoodContext:{type:"array",items:CONTEXT_ITEM_SCHEMA}, provisionalContext:{type:"array",items:CONTEXT_ITEM_SCHEMA}, unresolvedContext:{type:"array",items:CONTEXT_ITEM_SCHEMA}, clarificationNeeded:{type:"array",items:{type:"object",additionalProperties:false,properties:{key:{type:["string","null"]},expression:{type:["string","null"]},question:{type:["string","null"]},reason:{type:["string","null"]},material:{type:"boolean"}},required:["key","expression","question","reason","material"]}}, readyToAdvance:{type:"boolean"}, recommendedStageId:{type:["string","null"]}, recommendedTaskId:{type:["string","null"]}, nextAction:{anyOf:[{type:"object",additionalProperties:false,properties:{type:{type:["string","null"]},label:{type:["string","null"]},reason:{type:["string","null"]}},required:["type","label","reason"]},{type:"null"}]}, resumeNote:{type:["string","null"]}}, required:["understoodContext","provisionalContext","unresolvedContext","clarificationNeeded","readyToAdvance","recommendedStageId","recommendedTaskId","nextAction","resumeNote"] };

const SYSTEM_INSTRUCTIONS = `You are iBand Movie Mentor's Semantic Interpreter. Your job is interpretation, not creative authorship, story completion, or journey planning.
1. Current creator wording is authoritative.
2. Existing creator-confirmed meanings remain authoritative unless explicitly corrected now.
3. Never silently replace creator terminology.
4. Distinguish SEMANTIC AMBIGUITY from MISSING CREATIVE DETAIL. A creator does not need to specify every story detail for their sentence to be semantically understood.
5. Do NOT ask clarifying questions merely because backstory, mechanics, motivations, chronology, message format, worldbuilding, or other creative specifics have not yet been supplied. Those are future creative-development questions, not semantic failures.
6. clarificationNeeded is only for cases where proceeding would risk misunderstanding what the creator actually meant: unfamiliar/invented terminology, genuinely ambiguous references or relationships, contradictory meaning, unclear intent, or an explicit creator uncertainty that materially changes interpretation.
7. Common dialect, regional language and slang should be understood when the meaning is conventional and contextually clear. Do not ask the creator to define familiar UK expressions merely because they are informal. In this contract, examples such as "bare vexed" (very annoyed), "moving booky" / "booky" (suspicious or dodgy in context), and "clocks the rival crew" (notices/spots them) are semantically clear when used naturally.
8. Invented or genuinely unfamiliar expressions, such as "glorp-coded" with no established meaning, still require clarification rather than guessing.
9. unresolvedContext may contain only meaning/reference/intent that is explicitly present in the creator's language but genuinely unresolved. Never use unresolvedContext as a list of missing story information.
10. Inference belongs only in provisionalContext with confidenceSource=model-provisional. Every item in provisionalContext MUST use confidenceSource=model-provisional.
11. Creator meaning outranks inference, memory and deterministic planning.
12. Material semantic ambiguity forces readyToAdvance=false.
13. readyToAdvance answers one question only: is the creator's CURRENT LANGUAGE understood well enough to hand safely back to the journey/planning layer? It does NOT mean the movie idea is complete.
14. Adaptive Mentor planning is not evidence of semantic understanding.
15. Preserve uncertainty when uncertainty is genuinely semantic.
16. understoodContext may contain only creator-confirmed or creator-explicit meaning.
17. Current explicit creator correction may supersede older confirmed meaning.
18. Example of semantically clear language: "A retired astronaut discovers that the lighthouse in her coastal town is sending messages from her missing daughter." Do not ask what format the messages use, why the lighthouse can send them, or details of the daughter's disappearance. Those are unspecified creative details, not semantic ambiguity.
19. Return only the required structured intelligence.`;

function extractCreatorMessage(r){return cleanString(r?.input?.message||r?.message||r?.context?.activeIdea||"");}
function normalizeCreatorConfirmedContext(r){return asArray(r?.context?.creatorConfirmedContext||r?.context?.confirmedMeaning||r?.context?.confirmedMeanings||[]).filter(i=>i&&typeof i==="object"&&cleanString(i.key)).map(i=>({key:cleanString(i.key),value:cloneValue(i.value),authority:"creator",stageId:cleanString(i.stageId)||null,sceneId:cleanString(i.sceneId)||null,reason:cleanString(i.reason)||null,createdAt:i.createdAt||null}));}
function buildSemanticInput(r){return {creatorMessage:extractCreatorMessage(r),creatorConfirmedContext:normalizeCreatorConfirmedContext(r),movieJourneyContext:cloneValue(r?.context||{}),requestMetadata:cloneValue(r?.options?.metadata||{}),instruction:"Interpret meaning conservatively but do not confuse unspecified creative detail with semantic ambiguity. Understand conventional UK slang when context makes the meaning clear; unfamiliar or invented terminology still requires clarification. Current explicit corrections may supersede prior creator-confirmed context; model inference may never do so. Every provisionalContext item must use confidenceSource=model-provisional."};}
function normalizeContextItem(i){if(!i||typeof i!=="object")return null;return {key:cleanString(i.key)||null,value:i.value==null?null:String(i.value),evidence:cleanString(i.evidence)||null,confidenceSource:cleanString(i.confidenceSource)||""};}
function normalizeIntelligence(c){if(!c||typeof c!=="object")return null;const ni=v=>asArray(v).map(normalizeContextItem).filter(Boolean);const provisionalContext=ni(c.provisionalContext).map(i=>({...i,confidenceSource:"model-provisional"}));return {understoodContext:ni(c.understoodContext),provisionalContext,unresolvedContext:ni(c.unresolvedContext),clarificationNeeded:asArray(c.clarificationNeeded).map(i=>({key:cleanString(i?.key)||null,expression:cleanString(i?.expression)||null,question:cleanString(i?.question)||null,reason:cleanString(i?.reason)||null,material:i?.material!==false})),readyToAdvance:c.readyToAdvance===true,recommendedStageId:cleanString(c.recommendedStageId)||null,recommendedTaskId:cleanString(c.recommendedTaskId)||null,nextAction:c.nextAction&&typeof c.nextAction==="object"?cloneValue(c.nextAction):null,resumeNote:cleanString(c.resumeNote)||null};}
function applyCreatorAuthority(n,cc=[]){const intelligence=cloneValue(n),safetyCorrections=[],fatalIssues=[],confirmedByKey=new Map(asArray(cc).filter(i=>cleanString(i?.key)).map(i=>[cleanString(i.key),i])),explicitCurrentKeys=new Set(intelligence.understoodContext.filter(i=>i.confidenceSource==="creator-explicit"&&i.key).map(i=>i.key));for(const i of intelligence.understoodContext){if(!i.key)continue;const c=confirmedByKey.get(i.key);if(!c)continue;if(i.confidenceSource==="creator-confirmed"&&stableValue(i.value)!==stableValue(c.value))fatalIssues.push(`creator_confirmed_conflict:${i.key}`);else if(i.confidenceSource==="creator-explicit"&&stableValue(i.value)!==stableValue(c.value))safetyCorrections.push(`current_creator_correction_supersedes_prior:${i.key}`);} intelligence.provisionalContext=intelligence.provisionalContext.filter(i=>{if(!i.key||!confirmedByKey.has(i.key)||explicitCurrentKeys.has(i.key))return true;safetyCorrections.push(`removed_provisional_conflict_with_creator_truth:${i.key}`);return false;});return {intelligence,safetyCorrections,fatalIssues};}
function validateIntelligence(c,{creatorConfirmedContext=[]}={}){const rawProvisional=asArray(c?.provisionalContext).map(normalizeContextItem).filter(Boolean);const n=normalizeIntelligence(c),fatalIssues=[],safetyCorrections=[];if(!n)return {valid:false,intelligence:null,issues:["missing_structured_intelligence"],fatalIssues:["missing_structured_intelligence"],safetyCorrections:[]};if(n.understoodContext.some(i=>!["creator-confirmed","creator-explicit"].includes(i.confidenceSource)))fatalIssues.push("understood_context_requires_creator_authority");if(rawProvisional.some(i=>i.confidenceSource!=="model-provisional"))safetyCorrections.push("normalized_provisional_context_to_model_provisional");for(const i of n.clarificationNeeded)if(i.material&&(!i.question||!i.reason))fatalIssues.push("material_clarification_requires_question_and_reason");const a=applyCreatorAuthority(n,creatorConfirmedContext);fatalIssues.push(...a.fatalIssues);safetyCorrections.push(...a.safetyCorrections);const intelligence=a.intelligence;if(intelligence.unresolvedContext.length&&intelligence.readyToAdvance){intelligence.readyToAdvance=false;safetyCorrections.push("unresolved_context_forced_ready_to_advance_false");}if(intelligence.clarificationNeeded.some(i=>i.material)&&intelligence.readyToAdvance){intelligence.readyToAdvance=false;safetyCorrections.push("material_clarification_forced_ready_to_advance_false");}if(fatalIssues.length)intelligence.readyToAdvance=false;return {valid:fatalIssues.length===0,intelligence,issues:[...fatalIssues,...safetyCorrections],fatalIssues,safetyCorrections};}
function parseJsonText(t){const v=cleanString(t);if(!v)return null;try{return JSON.parse(v);}catch{return null;}}
function extractOpenAIOutputText(p){if(cleanString(p?.output_text))return p.output_text;for(const i of asArray(p?.output))for(const c of asArray(i?.content))if(cleanString(c?.text))return c.text;return "";}

function getProviderConfig(){const provider=cleanString(process.env.IBAND_AI_PROVIDER||"openai").toLowerCase(),model=cleanString(process.env.IBAND_AI_MODEL),timeoutMs=Math.max(1000,Number(process.env.IBAND_AI_TIMEOUT_MS||30000)||30000);if(provider==="openai")return {provider,model,url:cleanString(process.env.IBAND_AI_BASE_URL)||"https://api.openai.com/v1/responses",key:cleanString(process.env.IBAND_AI_API_KEY||process.env.OPENAI_API_KEY),requiresKey:true,requiresModel:true,timeoutMs};if(provider==="generic-http")return {provider,model,url:cleanString(process.env.IBAND_AI_BASE_URL),key:cleanString(process.env.IBAND_AI_API_KEY),requiresKey:false,requiresModel:false,timeoutMs};return {provider,model,url:"",key:"",requiresKey:false,requiresModel:false,timeoutMs};}
function getConfigurationIssues(c){const issues=[];if(!["openai","generic-http"].includes(c?.provider))issues.push("unsupported_provider");if(!c?.url)issues.push("missing_base_url");if(c?.requiresKey&&!c?.key)issues.push("missing_api_key");if(c?.requiresModel&&!c?.model)issues.push("missing_model");return issues;}
function isProviderConfigured(c){return getConfigurationIssues(c).length===0;}
function classifyProviderFailure(error){if(error?.name==="AbortError")return {code:"SEMANTIC_PROVIDER_TIMEOUT",category:"timeout",retryable:true};const status=Number(error?.status||0),providerCode=cleanString(error?.data?.error?.code||error?.data?.code).toLowerCase(),message=cleanString(error?.message).toLowerCase();if(status===401||status===403||/api.?key|auth|credential|permission/.test(providerCode+" "+message))return {code:"SEMANTIC_PROVIDER_AUTHENTICATION_FAILED",category:"authentication",retryable:false};if(status===404||/model.*(not found|does not exist|invalid)|invalid.*model/.test(providerCode+" "+message))return {code:"SEMANTIC_PROVIDER_INVALID_MODEL",category:"invalid-model",retryable:false};if(status===429)return {code:"SEMANTIC_PROVIDER_RATE_LIMITED",category:"rate-limit",retryable:true};if(status>=500)return {code:"SEMANTIC_PROVIDER_UNAVAILABLE",category:"unavailable",retryable:true};if(status>=400)return {code:"SEMANTIC_PROVIDER_REQUEST_REJECTED",category:"request",retryable:false};return {code:"SEMANTIC_PROVIDER_FAILED",category:"unknown",retryable:true};}
async function postJson(url,body,{key,timeoutMs,headers={}}){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeoutMs);try{const response=await fetch(url,{method:"POST",headers:{Accept:"application/json","Content-Type":"application/json",...(key?{Authorization:`Bearer ${key}`}:{ }),...headers},body:JSON.stringify(body),signal:controller.signal});const text=await response.text();let payload=null;try{payload=text?JSON.parse(text):null;}catch{payload={raw:text};}if(!response.ok){const e=new Error(cleanString(payload?.error?.message)||cleanString(payload?.message)||`AI provider failed (${response.status}).`);e.status=response.status;e.data=payload;throw e;}return payload;}finally{clearTimeout(timer);}}
async function interpretWithOpenAI(r,c){const p=await postJson(c.url,{model:c.model,instructions:SYSTEM_INSTRUCTIONS,input:JSON.stringify(buildSemanticInput(r)),text:{format:{type:"json_schema",name:"movie_journey_intelligence",strict:true,schema:MOVIE_JOURNEY_INTELLIGENCE_SCHEMA}}},c);return {candidate:parseJsonText(extractOpenAIOutputText(p)),usage:p?.usage||null,providerMetadata:{provider:"openai",model:p?.model||c.model,responseId:p?.id||null}};}
async function interpretWithGenericHttp(r,c){const p=await postJson(c.url,{task:"movie-mentor-semantic-interpretation",contractVersion:MOVIE_MENTOR_SEMANTIC_CONTRACT_VERSION,systemInstructions:SYSTEM_INSTRUCTIONS,schema:MOVIE_JOURNEY_INTELLIGENCE_SCHEMA,input:buildSemanticInput(r)},c);return {candidate:p?.movieJourneyIntelligence||p?.structured?.movieJourneyIntelligence||p?.structured||p?.data||parseJsonText(p?.text),usage:p?.usage||null,providerMetadata:{provider:"generic-http",model:p?.model||c.model||null,responseId:p?.id||null}};}
async function interpretMovieMentorSemantics(r={}){if(!extractCreatorMessage(r)){const e=new Error("A creator message is required for semantic interpretation.");e.code="CREATOR_MESSAGE_REQUIRED";throw e;}const c=getProviderConfig(),configurationIssues=getConfigurationIssues(c);if(configurationIssues.length){const e=new Error("Movie Mentor semantic AI provider is not ready. Check the selected provider's required IBAND_AI_* environment variables.");e.code="SEMANTIC_PROVIDER_NOT_CONFIGURED";e.configurationIssues=configurationIssues;throw e;}let raw;try{if(c.provider==="openai")raw=await interpretWithOpenAI(r,c);else if(c.provider==="generic-http")raw=await interpretWithGenericHttp(r,c);else{const e=new Error(`Unsupported semantic AI provider: ${c.provider}`);e.code="SEMANTIC_PROVIDER_UNSUPPORTED";throw e;}}catch(error){if(error?.code)throw error;const classification=classifyProviderFailure(error);error.code=classification.code;error.providerFailureCategory=classification.category;error.retryable=classification.retryable;throw error;}if(!raw?.candidate){const e=new Error("Semantic provider response did not contain parseable structured output.");e.code="SEMANTIC_STRUCTURED_OUTPUT_INVALID";throw e;}const validation=validateIntelligence(raw.candidate,{creatorConfirmedContext:normalizeCreatorConfirmedContext(r)});if(!validation.intelligence||!validation.valid){const e=new Error("Semantic AI provider returned intelligence that failed iBand's authority/safety validation.");e.code="SEMANTIC_INTELLIGENCE_INVALID";e.validationIssues=validation.issues;throw e;}return {text:"",structured:{movieJourneyIntelligence:{...validation.intelligence,metadata:{semanticInterpreterVersion:MOVIE_MENTOR_SEMANTIC_INTERPRETER_VERSION,semanticContractVersion:MOVIE_MENTOR_SEMANTIC_CONTRACT_VERSION,creatorLanguageAuthoritative:true,creatorConfirmedMeaningAuthoritative:true,currentCreatorCorrectionMaySupersedePriorTruth:true,provisionalInferenceIsNotCreatorTruth:true,materialAmbiguityBlocksProgression:true,validationIssues:validation.issues,safetyCorrections:validation.safetyCorrections}}},usage:raw.usage,metadata:raw.providerMetadata};}
function getMovieMentorSemanticProviderStatus(){const c=getProviderConfig(),configurationIssues=getConfigurationIssues(c);return {configured:configurationIssues.length===0,readiness:configurationIssues.length===0?"ready":"configuration-required",configurationIssues,provider:c.provider||null,modelConfigured:Boolean(c.model),model:c.model||null,baseUrlConfigured:Boolean(c.url),apiKeyConfigured:Boolean(c.key),timeoutMs:c.timeoutMs,interpreterVersion:MOVIE_MENTOR_SEMANTIC_INTERPRETER_VERSION,contractVersion:MOVIE_MENTOR_SEMANTIC_CONTRACT_VERSION,requiresKey:Boolean(c.requiresKey),requiresModel:Boolean(c.requiresModel)};}
export {MOVIE_MENTOR_SEMANTIC_INTERPRETER_VERSION,MOVIE_MENTOR_SEMANTIC_CONTRACT_VERSION,MOVIE_JOURNEY_INTELLIGENCE_SCHEMA,SYSTEM_INSTRUCTIONS,buildSemanticInput,normalizeCreatorConfirmedContext,normalizeIntelligence,applyCreatorAuthority,validateIntelligence,getProviderConfig,getConfigurationIssues,isProviderConfigured,classifyProviderFailure,getMovieMentorSemanticProviderStatus,interpretMovieMentorSemantics};
export default interpretMovieMentorSemantics;
