const VERSION="2.1.0",DOMAIN="iband.movie-mentor.commercial-checkout-initiation-authority";
function text(v){return typeof v==="string"?v.trim():"";}
function fail(code,message,extras={}){const e=new Error(message);e.code=code;Object.assign(e,extras);throw e;}
function instant(v){const value=text(v);if(!value)return null;const ms=Date.parse(value);return Number.isFinite(ms)?ms:null;}
function currentInstant(now){const current=now();const ms=current instanceof Date?current.getTime():Date.parse(current);if(!Number.isFinite(ms))fail("MOVIE_MENTOR_CHECKOUT_TIME_AUTHORITY_INVALID","Checkout authority requires a valid current authority time.");return ms;}
function createMovieMentorCommercialCheckoutInitiationAuthority({resolvePurchaseIntent,resolveCurrentEntitlement=null,createProviderCheckout,revokeProviderCheckout=null,checkoutBindingStore,now=()=>new Date()}={}){
 if(typeof resolvePurchaseIntent!=="function"||typeof createProviderCheckout!=="function")fail("MOVIE_MENTOR_CHECKOUT_AUTHORITY_REQUIRED","Checkout initiation requires durable purchase-intent resolution and explicit provider checkout composition.");
 if(resolveCurrentEntitlement!==null&&typeof resolveCurrentEntitlement!=="function")fail("MOVIE_MENTOR_CHECKOUT_ENTITLEMENT_AUTHORITY_INVALID","Current entitlement authority must be a resolver when supplied.");
 if(revokeProviderCheckout!==null&&typeof revokeProviderCheckout!=="function")fail("MOVIE_MENTOR_CHECKOUT_REVOCATION_AUTHORITY_INVALID","Provider checkout revocation authority must be a function when supplied.");
 if(typeof checkoutBindingStore?.begin!=="function"||typeof checkoutBindingStore?.complete!=="function"||typeof checkoutBindingStore?.resolve!=="function")fail("MOVIE_MENTOR_CHECKOUT_BINDING_AUTHORITY_REQUIRED","Checkout initiation requires durable checkout binding authority; process-local recovery is forbidden.");
 async function requireCurrentEntitlementAuthority(principal){if(!resolveCurrentEntitlement)return null;const entitlement=await resolveCurrentEntitlement({principalId:principal});if(!entitlement)return null;if(text(entitlement.principalId)!==principal||!["active","suspended"].includes(text(entitlement.status))||!Number.isSafeInteger(entitlement.entitlementRevision)||entitlement.entitlementRevision<1)fail("MOVIE_MENTOR_CHECKOUT_ENTITLEMENT_INVALID","Current durable entitlement is malformed or belongs to another principal.");if(text(entitlement.status)==="suspended")fail("MOVIE_MENTOR_CHECKOUT_ENTITLEMENT_SUSPENDED","Current durable entitlement is suspended; checkout cannot create or recover charge-capable authority without explicit reactivation.",{retryable:false,principalId:principal,entitlementRevision:entitlement.entitlementRevision});return entitlement;}
 async function revokeOwnedCheckout(principal,checkout,cause,phase){if(!revokeProviderCheckout)fail("MOVIE_MENTOR_CHECKOUT_ORPHAN_REVOCATION_AUTHORITY_REQUIRED",`${phase} left a charge-capable checkout that requires explicit provider revocation authority.`,{cause,retryable:false,principalId:principal,provider:text(checkout?.provider),checkoutReference:text(checkout?.checkoutReference),phase});await revokeProviderCheckout({provider:text(checkout?.provider),checkoutReference:text(checkout?.checkoutReference)});}
 async function revokeOwnedCheckoutAfterSuspension(principal,checkout,error,phase){if(error?.code!=="MOVIE_MENTOR_CHECKOUT_ENTITLEMENT_SUSPENDED")throw error;await revokeOwnedCheckout(principal,checkout,error,phase);throw error;}
 async function requireOwnedCheckoutEntitlementAuthority(principal,checkout,phase){try{return await requireCurrentEntitlementAuthority(principal);}catch(error){return revokeOwnedCheckoutAfterSuspension(principal,checkout,error,phase);}}
 async function completeOwnedCheckoutBinding(principal,intentId,request,idempotencyKey,checkout){try{return await checkoutBindingStore.complete({commercialIntentId:intentId,provider:request.provider,idempotencyKey,checkoutReference:text(checkout.checkoutReference),checkoutUrl:text(checkout.checkoutUrl),expiresAt:text(checkout.expiresAt)||null});}catch(error){let reality=null;try{reality=await checkoutBindingStore.resolve({commercialIntentId:intentId});}catch(resolveError){fail("MOVIE_MENTOR_CHECKOUT_BINDING_COMPLETION_REALITY_UNCERTAIN","Durable checkout binding completion failed and exact local reality could not be recovered.",{cause:resolveError,completionCause:error,retryable:true,commercialIntentId:intentId,provider:request.provider,checkoutReference:text(checkout.checkoutReference)});}if(reality?.status==="completed"&&reality.provider===request.provider&&reality.idempotencyKey===idempotencyKey&&text(reality.checkoutReference)===text(checkout.checkoutReference)&&text(reality.checkoutUrl)===text(checkout.checkoutUrl))return reality;if(reality?.status==="pending"&&reality.provider===request.provider&&reality.idempotencyKey===idempotencyKey&&!text(reality.checkoutReference)){await revokeOwnedCheckout(principal,checkout,error,"binding-completion-failure");throw error;}fail("MOVIE_MENTOR_CHECKOUT_BINDING_COMPLETION_REALITY_UNCERTAIN","Durable checkout binding completion failed and recovered local reality does not certify either the exact completed checkout or a safe pending pre-write state.",{cause:error,retryable:true,commercialIntentId:intentId,provider:request.provider,checkoutReference:text(checkout.checkoutReference),recoveredStatus:text(reality?.status)||null,recoveredCheckoutReference:text(reality?.checkoutReference)||null});}}
 async function initiateCheckout({principalId,commercialIntentId}={}){const principal=text(principalId),intentId=text(commercialIntentId);if(!principal||!intentId)fail("MOVIE_MENTOR_CHECKOUT_REQUEST_INVALID","Authenticated principal and commercial intent are required.");const intent=await resolvePurchaseIntent({commercialIntentId:intentId});if(!intent||text(intent.commercialIntentId)!==intentId)fail("MOVIE_MENTOR_CHECKOUT_INTENT_NOT_FOUND","Durable commercial purchase intent was not found.");if(text(intent.principalId)!==principal)fail("MOVIE_MENTOR_CHECKOUT_PRINCIPAL_MISMATCH","Authenticated principal does not own this commercial intent.");if(text(intent.status)!=="created")fail("MOVIE_MENTOR_CHECKOUT_INTENT_NOT_CHECKOUT_ELIGIBLE","Commercial intent is not eligible for checkout initiation.");await requireCurrentEntitlementAuthority(principal);const request=Object.freeze({commercialIntentId:intentId,principalId:principal,packageId:text(intent.packageId),provider:text(intent.provider),providerProductId:text(intent.providerProductId),amountMinor:intent.amountMinor,currency:text(intent.currency).toUpperCase(),environment:text(intent.environment),units:intent.units,policyVersion:text(intent.policyVersion),policyDigest:text(intent.policyDigest)});if(!request.provider||!request.providerProductId||!Number.isSafeInteger(request.amountMinor)||request.amountMinor<0||!request.currency||!request.environment||!Number.isSafeInteger(request.units)||request.units<=0||!request.policyVersion||!request.policyDigest)fail("MOVIE_MENTOR_CHECKOUT_INTENT_INVALID","Durable commercial intent is incomplete.");
 const idempotencyKey=`movie-mentor:${intentId}`;const binding=await checkoutBindingStore.begin({commercialIntentId:intentId,provider:request.provider,idempotencyKey});await requireCurrentEntitlementAuthority(principal);if(binding?.status==="completed"){if(binding.provider!==request.provider||binding.idempotencyKey!==idempotencyKey||!text(binding.checkoutReference)||!text(binding.checkoutUrl))fail("MOVIE_MENTOR_CHECKOUT_BINDING_INVALID","Completed durable checkout binding is malformed or conflicts with purchase intent.");const expiry=instant(binding.expiresAt);if(text(binding.expiresAt)&&expiry===null)fail("MOVIE_MENTOR_CHECKOUT_BINDING_INVALID","Completed durable checkout binding carries an invalid provider-session expiry.");if(expiry!==null&&expiry<=currentInstant(now))fail("MOVIE_MENTOR_CHECKOUT_RECOVERY_EXPIRED","Expired provider checkout history cannot regain creator-facing checkout authority.",{retryable:false,commercialIntentId:intentId,checkoutReference:text(binding.checkoutReference)});return Object.freeze({authorized:true,commercialIntentId:intentId,provider:request.provider,checkoutReference:text(binding.checkoutReference),checkoutUrl:text(binding.checkoutUrl),expiresAt:text(binding.expiresAt)||null,recovered:true});}
 const checkout=await createProviderCheckout({intent:request,idempotencyKey});if(!checkout||checkout.authorized!==true||text(checkout.commercialIntentId)!==intentId||text(checkout.provider)!==request.provider||!text(checkout.checkoutReference)||!text(checkout.checkoutUrl))fail("MOVIE_MENTOR_CHECKOUT_PROVIDER_RESPONSE_INVALID","Provider checkout did not return a valid authority-bound session.");const providerExpiry=instant(checkout.expiresAt);if(text(checkout.expiresAt)&&providerExpiry===null)fail("MOVIE_MENTOR_CHECKOUT_PROVIDER_RESPONSE_INVALID","Provider checkout returned an invalid session expiry.");if(providerExpiry!==null&&providerExpiry<=currentInstant(now))fail("MOVIE_MENTOR_CHECKOUT_PROVIDER_SESSION_EXPIRED","Provider checkout session expired before durable checkout authority could be established.",{retryable:true,commercialIntentId:intentId,checkoutReference:text(checkout.checkoutReference)});await requireOwnedCheckoutEntitlementAuthority(principal,checkout,"post-provider");const completed=await completeOwnedCheckoutBinding(principal,intentId,request,idempotencyKey,checkout);if(completed?.status!=="completed"||completed.checkoutReference!==text(checkout.checkoutReference))fail("MOVIE_MENTOR_CHECKOUT_BINDING_COMPLETION_INVALID","Provider checkout exists but durable local binding did not certify completion.");if(providerExpiry!==null&&providerExpiry<=currentInstant(now))fail("MOVIE_MENTOR_CHECKOUT_POST_BINDING_EXPIRED","Provider checkout session expired across durable binding I/O before creator-facing authority could be returned.",{retryable:true,commercialIntentId:intentId,checkoutReference:text(checkout.checkoutReference)});await requireOwnedCheckoutEntitlementAuthority(principal,checkout,"post-binding");return Object.freeze({authorized:true,commercialIntentId:intentId,provider:request.provider,checkoutReference:completed.checkoutReference,checkoutUrl:completed.checkoutUrl,expiresAt:completed.expiresAt,recovered:false});}
 return Object.freeze({initiateCheckout});
}
export{VERSION as MOVIE_MENTOR_COMMERCIAL_CHECKOUT_INITIATION_AUTHORITY_VERSION,DOMAIN as MOVIE_MENTOR_COMMERCIAL_CHECKOUT_INITIATION_AUTHORITY_DOMAIN,createMovieMentorCommercialCheckoutInitiationAuthority};export default createMovieMentorCommercialCheckoutInitiationAuthority;
