const DOMAIN="iband.movie-mentor.journey-authority-recovery-envelope";
const SCHEMA=1;
const AUTHORITY_DOMAIN="iband.movie-mentor.journey-authority";
const AUTHORITY_SCHEMA=1;
function s(v){return typeof v==="string"?v.trim():"";}
function n(v){return Number.isSafeInteger(v)&&v>=0?v:null;}
function clone(v){if(v===undefined)return undefined;try{return JSON.parse(JSON.stringify(v));}catch{return v;}}
function stable(v){if(Array.isArray(v))return v.map(stable);if(!v||typeof v!=="object")return v;return Object.keys(v).sort().reduce((o,k)=>(o[k]=stable(v[k]),o),{});}
function stringify(v){return JSON.stringify(stable(v));}
function fingerprint(v){const text=stringify(v);let hash=2166136261;for(let i=0;i<text.length;i+=1){hash^=text.charCodeAt(i);hash=Math.imul(hash,16777619);}return `fnv1a32:${(hash>>>0).toString(16).padStart(8,"0")}`;}
function payload(e){return{domain:e.domain,schema:e.schema,lineageId:e.lineageId,project:clone(e.project),authorityGeneration:e.authorityGeneration,progressionRevision:e.progressionRevision,journeyFingerprint:e.journeyFingerprint,authoritySnapshotFingerprint:e.authoritySnapshotFingerprint,authorityRecord:clone(e.authorityRecord)};}
function fail(code,message,extras={}){const e=new Error(message);e.code=code;Object.assign(e,extras);throw e;}
function inspectAuthority(a){if(!a||typeof a!=="object"||Array.isArray(a))return{valid:false,reason:"authority-not-object"};if(a.domain!==AUTHORITY_DOMAIN||a.schema!==AUTHORITY_SCHEMA)return{valid:false,reason:"authority-domain-or-schema-invalid"};const generation=n(a?.authority?.generation),revision=n(a?.journey?.progression?.revision??0);if(generation===null||revision===null)return{valid:false,reason:"authority-coordinate-invalid"};if(!Array.isArray(a.recommendations))return{valid:false,reason:"recommendation-lifecycle-missing"};if(!a.projection||typeof a.projection!=="object"||Array.isArray(a.projection))return{valid:false,reason:"creator-truth-projection-missing"};const jf=fingerprint(a.journey);if(s(a.journeyFingerprint)!==jf)return{valid:false,reason:"journey-fingerprint-invalid"};return{valid:true,generation,revision,journeyFingerprint:jf};}
function inspectMovieMentorJourneyRecoveryEnvelope(e,{projectId=null}={}){if(!e||typeof e!=="object"||Array.isArray(e))return{valid:false,status:"malformed",reason:"record-not-object"};if(e.domain!==DOMAIN||e.schema!==SCHEMA)return{valid:false,status:"malformed",reason:"domain-or-schema-invalid"};const lineageId=s(e.lineageId),generation=n(e.authorityGeneration),revision=n(e.progressionRevision),project=s(e?.project?.projectId),jf=s(e.journeyFingerprint),sf=s(e.authoritySnapshotFingerprint),ef=s(e.envelopeFingerprint);if(!lineageId||generation===null||revision===null||!project||!jf||!sf||!ef)return{valid:false,status:"malformed",reason:"required-field-invalid"};if(projectId&&project!==s(projectId))return{valid:false,status:"identity-conflict",reason:"project-id-conflict"};const ai=inspectAuthority(e.authorityRecord);if(!ai.valid)return{valid:false,status:"malformed",reason:ai.reason};if(s(e?.authorityRecord?.project?.projectId)!==project)return{valid:false,status:"identity-conflict",reason:"authority-project-conflict"};if(ai.generation!==generation||ai.revision!==revision||ai.journeyFingerprint!==jf)return{valid:false,status:"malformed",reason:"authority-coordinate-mismatch"};if(fingerprint(e.authorityRecord)!==sf)return{valid:false,status:"tampered",reason:"authority-snapshot-fingerprint-mismatch"};if(fingerprint(payload(e))!==ef)return{valid:false,status:"tampered",reason:"envelope-fingerprint-mismatch"};return{valid:true,status:"eligible-evidence",projectId:project,lineageId,authorityGeneration:generation,progressionRevision:revision,journeyFingerprint:jf,authoritySnapshotFingerprint:sf,envelopeFingerprint:ef};}
function assertMovieMentorJourneyRecoveryEnvelope(e,options={}){const i=inspectMovieMentorJourneyRecoveryEnvelope(e,options);if(!i.valid)fail("MOVIE_MENTOR_JOURNEY_RECOVERY_ENVELOPE_INVALID","Journey recovery envelope failed server verification.",{reason:i.reason,status:i.status});return i;}
export{DOMAIN as MOVIE_MENTOR_JOURNEY_RECOVERY_ENVELOPE_DOMAIN,SCHEMA as MOVIE_MENTOR_JOURNEY_RECOVERY_ENVELOPE_SCHEMA,fingerprint,inspectMovieMentorJourneyRecoveryEnvelope,assertMovieMentorJourneyRecoveryEnvelope};
export default assertMovieMentorJourneyRecoveryEnvelope;
