import mongoose from "mongoose";
import {
  CONTINUITY_CACHE_AUTHORITY,
  CONTINUITY_CACHE_DOMAIN,
  CONTINUITY_CACHE_SCHEMA,
  validateContinuityDerivedCacheRecord,
} from "./MovieMentorContinuityDerivedCacheControl.js";

const MOVIE_MENTOR_CONTINUITY_DERIVED_CACHE_STORE_VERSION="1.0.0";
const COLLECTION_NAME="movie_mentor_continuity_derived_cache";
let connectionPromise=null;
let model=null;
function s(v){return typeof v==="string"?v.trim():"";}
function clone(v){if(v===undefined)return undefined;try{return JSON.parse(JSON.stringify(v));}catch{return v;}}
function mongoUri(){return s(process.env.MONGO_URI||process.env.MONGODB_URI||"");}
function storeError(code,message,{retryable=false,reasons=[]}={}){const error=new Error(message);error.code=code;error.retryable=retryable;error.reasons=reasons;return error;}
function getMovieMentorContinuityDerivedCacheStoreStatus(){const configured=Boolean(mongoUri());return{version:MOVIE_MENTOR_CONTINUITY_DERIVED_CACHE_STORE_VERSION,configured,readiness:configured?"configured":"configuration-required",collection:COLLECTION_NAME,authority:CONTINUITY_CACHE_AUTHORITY,canonical:false,mayCreateCanon:false,mutatesCreatorState:false};}
function getModel(){if(model)return model;const schema=new mongoose.Schema({cacheKey:{type:String,trim:true,required:true,unique:true,index:true},cacheFingerprint:{type:String,trim:true,required:true},domain:{type:String,trim:true,required:true},schema:{type:Number,required:true},version:{type:String,trim:true,required:true},authority:{type:String,trim:true,required:true},projectId:{type:String,trim:true,required:true,index:true},sourceRevision:{type:Number,min:0,required:true},sourceCreatorStateGeneration:{type:Number,min:0,required:true},sourceCreatorStateFingerprint:{type:String,trim:true,required:true,index:true},sourceSnapshotReference:{type:String,trim:true,required:true},dependencyDigest:{type:String,trim:true,required:true},constraints:{type:[mongoose.Schema.Types.Mixed],default:[]},creatorConfirmed:{type:Boolean,required:true},mayCreateCanon:{type:Boolean,required:true},createdAt:{type:Date,required:true}},{collection:COLLECTION_NAME,timestamps:true,minimize:false,strict:true});schema.index({projectId:1,sourceCreatorStateFingerprint:1},{unique:true});model=mongoose.models.MovieMentorContinuityDerivedCache||mongoose.model("MovieMentorContinuityDerivedCache",schema);return model;}
async function ensureConnection(){const uri=mongoUri();if(!uri)throw storeError("MOVIE_MENTOR_CONTINUITY_CACHE_STORE_NOT_CONFIGURED","Movie Mentor continuity derived cache store requires MONGO_URI or MONGODB_URI.");if(mongoose.connection.readyState===1)return mongoose.connection;if(!connectionPromise){connectionPromise=mongoose.connect(uri,{serverSelectionTimeoutMS:5000,maxPoolSize:10}).catch(error=>{connectionPromise=null;throw storeError("MOVIE_MENTOR_CONTINUITY_CACHE_STORE_UNAVAILABLE",`Movie Mentor continuity derived cache store is unavailable: ${error instanceof Error?error.message:"Mongo connection failed."}`,{retryable:true});});}await connectionPromise;return mongoose.connection;}
function normalize(doc){if(!doc)return null;return{cacheKey:s(doc.cacheKey),cacheFingerprint:s(doc.cacheFingerprint),domain:s(doc.domain),schema:doc.schema,version:s(doc.version),authority:s(doc.authority),projectId:s(doc.projectId),sourceRevision:doc.sourceRevision,sourceCreatorStateGeneration:doc.sourceCreatorStateGeneration,sourceCreatorStateFingerprint:s(doc.sourceCreatorStateFingerprint),sourceSnapshotReference:s(doc.sourceSnapshotReference),dependencyDigest:s(doc.dependencyDigest),constraints:clone(Array.isArray(doc.constraints)?doc.constraints:[]),creatorConfirmed:doc.creatorConfirmed,mayCreateCanon:doc.mayCreateCanon,createdAt:new Date(doc.createdAt).toISOString(),updatedAt:doc.updatedAt?new Date(doc.updatedAt).toISOString():null};}
function assertStoreable(record={}){if(record?.domain!==CONTINUITY_CACHE_DOMAIN||record?.schema!==CONTINUITY_CACHE_SCHEMA||record?.authority!==CONTINUITY_CACHE_AUTHORITY||record?.creatorConfirmed!==false||record?.mayCreateCanon!==false||!s(record?.projectId)||!s(record?.sourceCreatorStateFingerprint)||!s(record?.cacheKey)||!s(record?.cacheFingerprint))throw storeError("MOVIE_MENTOR_CONTINUITY_CACHE_RECORD_INVALID","Only non-canonical authority-bound continuity cache records may be persisted.");return record;}
async function writeContinuityDerivedCache(record={},currentState={},currentCreatorTruth=[]){assertStoreable(record);const validation=validateContinuityDerivedCacheRecord(record,currentState,currentCreatorTruth);if(!validation.valid)throw storeError("MOVIE_MENTOR_CONTINUITY_CACHE_RECORD_STALE","Stale or invalid continuity cache records may not be persisted.",{reasons:validation.reasons});await ensureConnection();const doc={...clone(record),createdAt:new Date(record.createdAt)};const result=await getModel().findOneAndUpdate({cacheKey:record.cacheKey},{$set:doc},{upsert:true,new:true,runValidators:true,setDefaultsOnInsert:true}).lean().exec();return normalize(result);}
async function readReusableContinuityDerivedCache(currentState={},currentCreatorTruth=[]){const projectId=s(currentState?.projectId),fingerprint=s(currentState?.creatorStateFingerprint);if(!projectId||!fingerprint)throw storeError("MOVIE_MENTOR_CONTINUITY_CACHE_AUTHORITY_REQUIRED","Current canonical project identity and creator-state fingerprint are required for a cache read.");await ensureConnection();const doc=await getModel().findOne({projectId,sourceCreatorStateFingerprint:fingerprint}).lean().exec();if(!doc)return{hit:false,stale:false,constraints:[],record:null};const record=normalize(doc),validation=validateContinuityDerivedCacheRecord(record,currentState,currentCreatorTruth);if(!validation.valid)return{hit:false,stale:true,constraints:[],record:null,reasons:validation.reasons};return{hit:true,stale:false,constraints:validation.constraints,record};}
async function deleteProjectContinuityDerivedCache(projectId){const project=s(projectId);if(!project)throw storeError("MOVIE_MENTOR_CONTINUITY_CACHE_PROJECT_REQUIRED","projectId is required to delete continuity derived cache.");await ensureConnection();const result=await getModel().deleteMany({projectId:project}).exec();return{projectId:project,deletedCount:Number(result?.deletedCount||0)};}
export{MOVIE_MENTOR_CONTINUITY_DERIVED_CACHE_STORE_VERSION,COLLECTION_NAME,getMovieMentorContinuityDerivedCacheStoreStatus,readReusableContinuityDerivedCache,writeContinuityDerivedCache,deleteProjectContinuityDerivedCache};
export default readReusableContinuityDerivedCache;
