import mongoose from "mongoose";
import {createMovieMentorInferenceSettlementMongoStore,getMovieMentorInferenceSettlementMongoStoreStatus} from "./MovieMentorInferenceSettlementMongoStore.js";
import {createMovieMentorInferenceSettlementReconciliationAuthority} from "./MovieMentorInferenceSettlementReconciliationAuthority.js";
import {createMovieMentorInferenceSettlementPhysicalAuthority} from "./MovieMentorInferenceSettlementPhysicalAuthority.js";

const VERSION="1.5.0",DOMAIN="iband.movie-mentor.production-inference-settlement-composition";
const ownedCompositionProofs=new WeakMap();
let readinessConnectionPromise=null;
const text=v=>typeof v==="string"?v.trim():"";
function mongoUri(){return text(process.env.MONGO_URI||process.env.MONGODB_URI||"");}
async function ensurePhysicalReadConnection(){const uri=mongoUri();if(!uri){const error=new Error("Inference settlement physical readiness requires MONGO_URI or MONGODB_URI.");error.code="MOVIE_MENTOR_INFERENCE_SETTLEMENT_PHYSICAL_AUTHORITY_UNAVAILABLE";error.retryable=true;throw error;}if(mongoose.connection.readyState===1)return mongoose.connection;if(!readinessConnectionPromise)readinessConnectionPromise=mongoose.connect(uri,{serverSelectionTimeoutMS:5000,maxPoolSize:10}).catch(error=>{readinessConnectionPromise=null;const wrapped=new Error(`Inference settlement physical readiness unavailable: ${error instanceof Error?error.message:"Mongo connection failed."}`);wrapped.code="MOVIE_MENTOR_INFERENCE_SETTLEMENT_PHYSICAL_AUTHORITY_UNAVAILABLE";wrapped.retryable=true;throw wrapped;});await readinessConnectionPromise;return mongoose.connection;}
async function readPhysicalIndexes(collectionName){const connection=await ensurePhysicalReadConnection(),database=connection?.db;if(!database){const error=new Error("Inference settlement physical readiness has no connected Mongo database.");error.code="MOVIE_MENTOR_INFERENCE_SETTLEMENT_PHYSICAL_AUTHORITY_UNAVAILABLE";error.retryable=true;throw error;}return database.collection(collectionName).indexes();}
function isMovieMentorProductionInferenceSettlementOwnerProof(composition,status){return Boolean(composition&&status&&ownedCompositionProofs.get(composition)===status&&composition.status===status&&typeof composition.getStatus==="function"&&composition.getStatus()===status);}
function rejected(reason,status=null){return Object.freeze({ready:false,reason,version:VERSION,authority:null,storeStatus:status,status:null,getStatus:()=>null,settledExecutionAuthority:false,atomicFinalizedToSettledDebit:false,explicitDebitBinding:false,proofTimeFailClosed:false,uniquenessReadinessRequired:false,physicalUniqueIndexReadiness:false});}
function createMovieMentorProductionInferenceSettlementComposition({store=null}={}){const injected=Boolean(store),storeStatus=injected?(typeof store?.getStatus==="function"?store.getStatus():null):getMovieMentorInferenceSettlementMongoStoreStatus();if(injected&&!storeStatus)return rejected("inference-settlement-injected-capability-not-proven");if(storeStatus?.configured!==true)return rejected("inference-settlement-store-not-configured",storeStatus||null);if(storeStatus.settledExecutionAuthority!==true||storeStatus.atomicFinalizedToSettledDebit!==true||storeStatus.explicitDebitBinding!==true||storeStatus.proofTimeFailClosed!==true)return rejected("inference-settlement-settled-capability-not-proven",storeStatus);try{const durableStore=store||createMovieMentorInferenceSettlementMongoStore(),productionStore=injected?durableStore:createMovieMentorInferenceSettlementPhysicalAuthority({store:durableStore,readIndexes:readPhysicalIndexes}),physicalStoreStatus=injected?null:productionStore.getStatus(),authority=createMovieMentorInferenceSettlementReconciliationAuthority({store:productionStore});const status=Object.freeze({domain:DOMAIN,production:true,ready:true,settledExecutionAuthority:true,atomicFinalizedToSettledDebit:true,explicitDebitBinding:true,proofTimeFailClosed:true,durableStoreProvenanceRequired:true,uniquenessReadinessRequired:!injected,physicalUniqueIndexReadiness:!injected,physicalReadinessBoundary:physicalStoreStatus?.readinessBoundary||null,authority,storeStatus,physicalStoreStatus,processLocalFallback:false});const getStatus=()=>status;const composition=Object.freeze({ready:true,reason:"atomic-finalized-to-settled-current-reality-debit-authority-composed",version:VERSION,authority,storeStatus,physicalStoreStatus,status,getStatus,settledExecutionAuthority:true,atomicFinalizedToSettledDebit:true,explicitDebitBinding:true,proofTimeFailClosed:true,uniquenessReadinessRequired:!injected,physicalUniqueIndexReadiness:!injected});ownedCompositionProofs.set(composition,status);return composition;}catch(error){return rejected(error?.code||"inference-settlement-composition-failed",storeStatus);}}
export{VERSION as MOVIE_MENTOR_PRODUCTION_INFERENCE_SETTLEMENT_COMPOSITION_VERSION,createMovieMentorProductionInferenceSettlementComposition,isMovieMentorProductionInferenceSettlementOwnerProof};export default createMovieMentorProductionInferenceSettlementComposition;
