import crypto from "node:crypto";
const VERSION="1.1.0",DOMAIN="iband.movie-mentor.inference-spend-authority",OPERATION="movie-mentor-turn",DEFAULT_TURN_UNITS=1;
function text(v){return typeof v==="string"?v.trim():"";} function fail(code,message,extras={}){const e=new Error(message);e.code=code;Object.assign(e,extras);throw e;}
function createMovieMentorInferenceSpendAuthority({store=null,createReservationId=()=>crypto.randomUUID()}={}){
 if(typeof store?.reserve!=="function"||typeof store?.settle!=="function")fail("MOVIE_MENTOR_INFERENCE_SPEND_AUTHORITY_REQUIRED","Inference spend authority requires durable atomic reservation and settlement.");
 async function reserveTurn({serverAuthority=null,projectId=null,units=DEFAULT_TURN_UNITS}={}){const principalId=text(serverAuthority?.principalId),authorizedProjectId=text(serverAuthority?.projectId),durableProjectId=text(projectId);if(!principalId)fail("MOVIE_MENTOR_INFERENCE_SPEND_PRINCIPAL_REQUIRED","Authenticated principal authority is required before paid inference.");if(!authorizedProjectId||!durableProjectId)fail("MOVIE_MENTOR_INFERENCE_SPEND_PROJECT_REQUIRED","Authorized and durable project identity are required before paid inference.");if(authorizedProjectId!==durableProjectId)fail("MOVIE_MENTOR_INFERENCE_SPEND_PROJECT_CONFLICT","Authenticated project authority does not match durable creator state.");if(serverAuthority?.authenticated!==true||serverAuthority?.projectAuthorized!==true)fail("MOVIE_MENTOR_INFERENCE_SPEND_AUTHORITY_REQUIRED","Paid inference requires server-created authenticated project authority.");if(!Number.isSafeInteger(units)||units<1)fail("MOVIE_MENTOR_INFERENCE_SPEND_RESERVATION_INVALID","Inference spend units must be a positive safe integer.");const reservationId=text(createReservationId());if(!reservationId)fail("MOVIE_MENTOR_INFERENCE_SPEND_RESERVATION_INVALID","Server reservation identity could not be created.");const decision=await store.reserve({reservationId,principalId,projectId:durableProjectId,operation:OPERATION,units});if(decision?.granted!==true)fail("MOVIE_MENTOR_INFERENCE_SPEND_RESERVATION_DENIED","Creator has no active inference entitlement with sufficient reserved capacity.",{retryable:false,reason:decision?.reason||"reservation-denied"});const r=decision.reservation;if(!r||text(r.reservationId)!==reservationId||text(r.principalId)!==principalId||text(r.projectId)!==durableProjectId||text(r.operation)!==OPERATION||r.units!==units||text(r.status)!=="reserved")fail("MOVIE_MENTOR_INFERENCE_SPEND_RESERVATION_INVALID","Durable inference spend reservation does not bind the requested creator, project and operation.");return Object.freeze({authorized:true,domain:DOMAIN,reservationId,principalId,projectId:durableProjectId,operation:OPERATION,units,entitlementRevision:r.entitlementRevision??null,idempotent:decision.idempotent===true});}
 async function settleTurn({reservation=null,outcome=null,reason=null}={}){const reservationId=text(reservation?.reservationId),principalId=text(reservation?.principalId),settlement=text(outcome);if(reservation?.authorized!==true||!reservationId||!principalId||!["consumed","released"].includes(settlement))fail("MOVIE_MENTOR_INFERENCE_SPEND_SETTLEMENT_INVALID","Only an authoritative reservation may be consumed or released.");const decision=await store.settle({reservationId,principalId,outcome:settlement,reason:text(reason)});const r=decision?.reservation;if(decision?.settled!==true||!r||text(r.reservationId)!==reservationId||text(r.principalId)!==principalId||text(r.status)!==settlement)fail("MOVIE_MENTOR_INFERENCE_SPEND_SETTLEMENT_INVALID","Durable settlement does not bind the authoritative reservation outcome.");return Object.freeze({settled:true,reservationId,principalId,outcome:settlement,units:r.units,idempotent:decision.idempotent===true});}
 return Object.freeze({reserveTurn,settleTurn});
}
export{VERSION as MOVIE_MENTOR_INFERENCE_SPEND_AUTHORITY_VERSION,DOMAIN as MOVIE_MENTOR_INFERENCE_SPEND_AUTHORITY_DOMAIN,OPERATION as MOVIE_MENTOR_INFERENCE_SPEND_OPERATION,DEFAULT_TURN_UNITS as MOVIE_MENTOR_INFERENCE_SPEND_DEFAULT_TURN_UNITS,createMovieMentorInferenceSpendAuthority};export default createMovieMentorInferenceSpendAuthority;
