const VERSION="1.2.0";
const ADAPTER_DOMAIN="iband.movie-mentor.commercial-provider-adapter";
function text(v){return typeof v==="string"?v.trim():"";}
function fail(code,message){const e=new Error(message);e.code=code;throw e;}
function ownedStatus(adapter){if(typeof adapter?.getStatus!=="function")return null;try{const status=adapter.getStatus();return status&&typeof status==="object"?status:null;}catch{return null;}}
function checkoutCapabilityProven(name,status){return status?.domain===ADAPTER_DOMAIN&&text(status?.provider)===name&&status?.productionCommercialProviderAdapter===true&&status?.checkoutTransport===true&&status?.serverOwnedIdempotencyRequired===true&&status?.creatorPayloadIsNotPaymentAuthority===true&&status?.processLocalFallback===false;}
function createMovieMentorCommercialCheckoutProviderRegistry({providers={}}={}){const entries=new Map();for(const [name,adapter] of Object.entries(providers||{})){const key=text(name),status=ownedStatus(adapter);if(!key||!adapter||typeof adapter.createCheckout!=="function"||!checkoutCapabilityProven(key,status))fail("MOVIE_MENTOR_CHECKOUT_PROVIDER_INVALID","Every configured checkout provider must own the production checkout transport and server-idempotency capability contract.");entries.set(key,Object.freeze({createCheckout:adapter.createCheckout,status}));}
 async function createProviderCheckout({intent,idempotencyKey}={}){const provider=text(intent?.provider),entry=entries.get(provider),key=text(idempotencyKey);if(!provider||!entry)fail("MOVIE_MENTOR_CHECKOUT_PROVIDER_NOT_CONFIGURED","Purchase intent names a checkout provider that is not explicitly configured.");if(!key)fail("MOVIE_MENTOR_CHECKOUT_IDEMPOTENCY_AUTHORITY_REQUIRED","Provider checkout requires a server-owned durable idempotency key.");return entry.createCheckout({intent:Object.freeze({...intent}),idempotencyKey:key});}
 return Object.freeze({createProviderCheckout,configuredProviders:Object.freeze([...entries.keys()]),providerStatuses:Object.freeze(Object.fromEntries([...entries].map(([name,entry])=>[name,entry.status])))});}
export{VERSION as MOVIE_MENTOR_COMMERCIAL_CHECKOUT_PROVIDER_REGISTRY_VERSION,createMovieMentorCommercialCheckoutProviderRegistry};export default createMovieMentorCommercialCheckoutProviderRegistry;
