import crypto from "node:crypto";
const VERSION="1.1.0",DOMAIN="iband.movie-mentor.canonical-result-authority",POLICY_VERSION="5A.24-canonical-result-v2";
const text=v=>typeof v==="string"?v.trim():"";const freeze=Object.freeze;function fail(code,message,extras={}){const e=new Error(message);e.code=code;Object.assign(e,extras);throw e;}function canonicalize(value){if(value===null||typeof value!=="object")return value;if(Array.isArray(value))return value.map(canonicalize);return Object.fromEntries(Object.keys(value).sort().map(k=>[k,canonicalize(value[k])]));}function digest(value){return crypto.createHash("sha256").update(JSON.stringify(canonicalize(value))).digest("hex");}
function createMovieMentorCanonicalResultAuthority({store=null,assertCurrentClosure=null,now=()=>new Date(),randomId=()=>crypto.randomUUID()}={}){if(typeof store?.commit!=="function"||typeof store?.readByExecution!=="function")fail("MOVIE_MENTOR_CANONICAL_RESULT_STORE_REQUIRED","Canonical result authority requires a durable immutable result store.");if(typeof assertCurrentClosure!=="function")fail("MOVIE_MENTOR_CANONICAL_RESULT_CLOSURE_VALIDATOR_REQUIRED","Canonical result authority requires current closed execution and provider-effect reality validation.");
 async function currentClosure(record){const current=await assertCurrentClosure({executionId:record.executionId,closureReference:record.closureReference,closureCertificateDigest:record.closureCertificateDigest});if(current?.authorized!==true||current?.closed!==true||current?.currentRealityVerified!==true)return null;return current;}
 async function commitResult({closure=null,result=null}={}){if(closure?.closed!==true||closure?.authorized!==true)fail("MOVIE_MENTOR_CANONICAL_RESULT_CLOSURE_REQUIRED","Canonical result commit requires authoritative CLOSED execution evidence.");const executionId=text(closure.executionId);const current=await assertCurrentClosure({executionId,closureReference:closure.closureReference,closureCertificateDigest:closure.closureCertificateDigest});if(current?.authorized!==true||current?.closed!==true||current?.currentRealityVerified!==true)fail("MOVIE_MENTOR_CANONICAL_RESULT_CLOSURE_STALE","Canonical result commit requires current matching CLOSED execution and provider-effect reality authority.",{retryable:true,reason:current?.reason||"closure-current-reality-invalid"});if(result===undefined)fail("MOVIE_MENTOR_CANONICAL_RESULT_PAYLOAD_REQUIRED","Canonical result payload is required.");const resultDigest=digest(result),existing=await store.readByExecution(executionId);if(existing){if(existing.resultDigest!==resultDigest||existing.closureCertificateDigest!==current.closureCertificateDigest)fail("MOVIE_MENTOR_CANONICAL_RESULT_CONFLICT","Execution is already bound to a different immutable canonical result.");return freeze({authorized:true,committed:true,idempotent:true,currentRealityVerified:true,domain:DOMAIN,policyVersion:POLICY_VERSION,...existing});}const committedAt=new Date(now()).toISOString(),record=await store.commit({resultReference:`canonical-result-${randomId()}`,executionId,creatorTurnId:current.creatorTurnId,principalId:current.principalId,projectId:current.projectId,reservationId:current.reservationId,requestDigest:current.requestDigest,closureReference:current.closureReference,closureCertificateDigest:current.closureCertificateDigest,resultDigest,resultPayload:canonicalize(result),committedAt});return freeze({authorized:true,committed:true,idempotent:false,currentRealityVerified:true,domain:DOMAIN,policyVersion:POLICY_VERSION,...record});}
 async function readResult({executionId}={}){const record=await store.readByExecution(text(executionId));if(!record)return freeze({authorized:false,committed:false,reason:"canonical-result-not-found"});const current=await currentClosure(record);if(!current)return freeze({authorized:false,committed:true,reason:"canonical-result-current-closure-invalid",resultReference:record.resultReference,reservationId:record.reservationId});return freeze({authorized:true,committed:true,idempotent:true,currentRealityVerified:true,domain:DOMAIN,policyVersion:POLICY_VERSION,...record});}
 return freeze({commitResult,readResult,digestResult:digest});}
export{VERSION as MOVIE_MENTOR_CANONICAL_RESULT_AUTHORITY_VERSION,DOMAIN as MOVIE_MENTOR_CANONICAL_RESULT_AUTHORITY_DOMAIN,POLICY_VERSION as MOVIE_MENTOR_CANONICAL_RESULT_POLICY_VERSION,createMovieMentorCanonicalResultAuthority};export default createMovieMentorCanonicalResultAuthority;
