import mongoose from "mongoose";

const VERSION="1.0.0",DOMAIN="iband.movie-mentor.canonical-result-store",SCHEMA=1,COLLECTION="movie_mentor_canonical_result";
let connectionPromise=null,model=null;
const text=v=>typeof v==="string"?v.trim():"";const plain=v=>v&&typeof v.toObject==="function"?v.toObject():v;const iso=v=>{const d=v instanceof Date?new Date(v):new Date(v);return Number.isNaN(d.getTime())?"":d.toISOString();};
function fail(code,message,extras={}){const e=new Error(message);e.code=code;Object.assign(e,extras);throw e;}
function mongoUri(){return text(process.env.MONGO_URI||process.env.MONGODB_URI||"");}
function getModel(){if(model)return model;const schema=new mongoose.Schema({domain:{type:String,required:true,immutable:true},schema:{type:Number,required:true,immutable:true},resultReference:{type:String,required:true,immutable:true,trim:true},executionId:{type:String,required:true,immutable:true,trim:true},creatorTurnId:{type:String,required:true,immutable:true,trim:true},principalId:{type:String,required:true,immutable:true,trim:true},projectId:{type:String,required:true,immutable:true,trim:true},reservationId:{type:String,required:true,immutable:true,trim:true},requestDigest:{type:String,required:true,immutable:true,trim:true},closureReference:{type:String,required:true,immutable:true,trim:true},closureCertificateDigest:{type:String,required:true,immutable:true,trim:true},resultDigest:{type:String,required:true,immutable:true,trim:true},resultPayload:{type:mongoose.Schema.Types.Mixed,required:true,immutable:true},committedAt:{type:Date,required:true,immutable:true}},{collection:COLLECTION,timestamps:true,minimize:false,strict:true});schema.index({resultReference:1},{unique:true});schema.index({executionId:1},{unique:true});schema.index({principalId:1,projectId:1,creatorTurnId:1},{unique:true});schema.index({reservationId:1},{unique:true});model=mongoose.models.MovieMentorCanonicalResult||mongoose.model("MovieMentorCanonicalResult",schema);return model;}
async function ensureConnection(){const uri=mongoUri();if(!uri)fail("MOVIE_MENTOR_CANONICAL_RESULT_MONGO_NOT_CONFIGURED","Canonical result Mongo store requires MONGO_URI or MONGODB_URI.");if(mongoose.connection.readyState===1)return mongoose.connection;if(!connectionPromise)connectionPromise=mongoose.connect(uri,{serverSelectionTimeoutMS:5000,maxPoolSize:10}).catch(error=>{connectionPromise=null;fail("MOVIE_MENTOR_CANONICAL_RESULT_MONGO_UNAVAILABLE",`Canonical result Mongo store unavailable: ${error instanceof Error?error.message:"Mongo connection failed."}`,{retryable:true});});await connectionPromise;return mongoose.connection;}
function normalize(record){if(!record)return null;const v=plain(record),required=[v.resultReference,v.executionId,v.creatorTurnId,v.principalId,v.projectId,v.reservationId,v.requestDigest,v.closureReference,v.closureCertificateDigest,v.resultDigest];if(v.domain!==DOMAIN||v.schema!==SCHEMA||required.some(x=>!text(x))||v.resultPayload===undefined||!iso(v.committedAt))fail("MOVIE_MENTOR_CANONICAL_RESULT_RECORD_INVALID","Durable canonical result record is malformed.");return Object.freeze({resultReference:text(v.resultReference),executionId:text(v.executionId),creatorTurnId:text(v.creatorTurnId),principalId:text(v.principalId),projectId:text(v.projectId),reservationId:text(v.reservationId),requestDigest:text(v.requestDigest),closureReference:text(v.closureReference),closureCertificateDigest:text(v.closureCertificateDigest),resultDigest:text(v.resultDigest),resultPayload:v.resultPayload,committedAt:iso(v.committedAt)});}
function sameBinding(a,b){return ["executionId","creatorTurnId","principalId","projectId","reservationId","requestDigest","closureReference","closureCertificateDigest","resultDigest"].every(k=>text(a?.[k])===text(b?.[k]));}
function createMovieMentorCanonicalResultMongoStore({mongoModel=null,connect=ensureConnection}={}){const storeModel=()=>mongoModel||getModel();async function ready(){if(!mongoModel)await connect();}async function readByExecution(executionId){await ready();const r=await storeModel().findOne({executionId:text(executionId)}).lean().exec();return r?normalize(r):null;}async function readByCreatorTurn({principalId,projectId,creatorTurnId}={}){await ready();const r=await storeModel().findOne({principalId:text(principalId),projectId:text(projectId),creatorTurnId:text(creatorTurnId)}).lean().exec();return r?normalize(r):null;}async function commit(record={}){await ready();const next={domain:DOMAIN,schema:SCHEMA,...record,committedAt:new Date(record.committedAt)};try{return normalize(await storeModel().create(next));}catch(error){if(error?.code!==11000)throw error;const existing=await readByExecution(record.executionId)||await readByCreatorTurn(record);if(existing&&sameBinding(existing,record))return existing;fail("MOVIE_MENTOR_CANONICAL_RESULT_CONFLICT","Canonical result identity is already bound to different immutable result authority.",{retryable:false});}}return Object.freeze({readByExecution,readByCreatorTurn,commit});}
function getMovieMentorCanonicalResultMongoStoreStatus(){const configured=Boolean(mongoUri());return Object.freeze({configured,readiness:configured?"configured":"not-configured",domain:DOMAIN,schema:SCHEMA,collection:COLLECTION,version:VERSION});}
export{VERSION as MOVIE_MENTOR_CANONICAL_RESULT_MONGO_STORE_VERSION,DOMAIN as MOVIE_MENTOR_CANONICAL_RESULT_MONGO_STORE_DOMAIN,createMovieMentorCanonicalResultMongoStore,getMovieMentorCanonicalResultMongoStoreStatus};export default createMovieMentorCanonicalResultMongoStore;
