const VERSION="1.0.0";
const DOMAIN="iband.movie-mentor.provider-effect-authority";
function text(value){return typeof value==="string"?value.trim():"";}
function freeze(value){return Object.freeze(value);}
function fail(code,message,extras={}){const error=new Error(message);error.code=code;Object.assign(error,extras);throw error;}
function instant(value){const parsed=value instanceof Date?new Date(value):new Date(value);if(Number.isNaN(parsed.getTime()))fail("MOVIE_MENTOR_PROVIDER_EFFECT_TIME_INVALID","Provider effect time is invalid.");return parsed;}
function createMovieMentorProviderEffectAuthority({store=null,now=()=>new Date()}={}){
 if(typeof store?.readEffect!=="function"||typeof store?.beginUnknown!=="function"||typeof store?.appendEvidence!=="function")fail("MOVIE_MENTOR_PROVIDER_EFFECT_STORE_REQUIRED","Provider effect authority requires a durable effect reality store.");
 async function beginDispatch({providerCall=null}={}){if(providerCall?.dispatchAuthorized!==true)fail("MOVIE_MENTOR_PROVIDER_DISPATCH_AUTHORITY_REQUIRED","Irreversible provider dispatch requires a successful durable provider-call claim.");const binding={providerCallId:text(providerCall.providerCallId),executionId:text(providerCall.executionId),slotId:text(providerCall.slotId),task:text(providerCall.task),dispatchUnknownAt:instant(now()).toISOString()};if(Object.values(binding).some(value=>!value))fail("MOVIE_MENTOR_PROVIDER_EFFECT_BINDING_REQUIRED","Provider dispatch UNKNOWN requires complete durable call binding.");let reality;try{reality=await store.beginUnknown(binding);}catch(error){const reread=await store.readEffect(binding.providerCallId);if(reread&&reread.executionId===binding.executionId&&reread.slotId===binding.slotId&&reread.task===binding.task)reality=reread;else throw error;}if(!reality)fail("MOVIE_MENTOR_PROVIDER_EFFECT_UNKNOWN_NOT_DURABLE","Provider dispatch is forbidden until UNKNOWN reality is durable.");if(reality.executionId!==binding.executionId||reality.slotId!==binding.slotId||reality.task!==binding.task)fail("MOVIE_MENTOR_PROVIDER_EFFECT_IDENTITY_CONFLICT","Durable effect reality is bound to a different provider call.");if(reality.state!=="unknown")return freeze({dispatchAuthorized:false,reason:"provider-effect-already-observed",reality});return freeze({dispatchAuthorized:true,providerCallId:binding.providerCallId,executionId:binding.executionId,slotId:binding.slotId,task:binding.task,effectState:"unknown",dispatchUnknownAt:reality.dispatchUnknownAt});}
 async function contributeEvidence({providerCallId,externalEffectId,provider,source="provider-response"}={}){const callId=text(providerCallId),effectId=text(externalEffectId),providerName=text(provider);if(!callId||!effectId||!providerName)fail("MOVIE_MENTOR_PROVIDER_EFFECT_EVIDENCE_REQUIRED","Effect evidence requires provider-call ID, external effect ID and provider.");const before=await store.readEffect(callId);if(!before)return freeze({accepted:false,reason:"provider-call-effect-reality-not-found"});let after;try{after=await store.appendEvidence({providerCallId:callId,externalEffectId:effectId,provider:providerName,observedAt:instant(now()).toISOString(),source:text(source)||"provider-response"});}catch(error){after=await store.readEffect(callId);if(!after)throw error;}if(!after)return freeze({accepted:false,reason:"provider-effect-evidence-not-durable"});return freeze({accepted:true,idempotent:before.evidence?.some(item=>item.externalEffectId===effectId)===true,state:after.state,providerCallId:callId,externalEffectIds:Object.freeze((after.evidence||[]).map(item=>item.externalEffectId)),conflict:after.state==="conflict",reality:after});}
 async function readReality(providerCallId){return store.readEffect(text(providerCallId));}
 return freeze({beginDispatch,contributeEvidence,readReality});
}
export{VERSION as MOVIE_MENTOR_PROVIDER_EFFECT_AUTHORITY_VERSION,DOMAIN as MOVIE_MENTOR_PROVIDER_EFFECT_AUTHORITY_DOMAIN,createMovieMentorProviderEffectAuthority};
export default createMovieMentorProviderEffectAuthority;
