import mongoose from "mongoose";

const VERSION="1.1.0",DOMAIN="iband.movie-mentor.terminal-disposition-decision",SCHEMA=1,COLLECTION="movie_mentor_terminal_disposition_decision";
let connectionPromise=null,model=null;
const text=v=>typeof v==="string"?v.trim():"";
function fail(code,message,extras={}){const e=new Error(message);e.code=code;Object.assign(e,extras);throw e;}
function uri(){return text(process.env.MONGO_URI||process.env.MONGODB_URI||"");}
function plain(v){return v&&typeof v.toObject==="function"?v.toObject():v;}
function getModel(){if(model)return model;const schema=new mongoose.Schema({
 domain:{type:String,required:true,immutable:true},schema:{type:Number,required:true,immutable:true},
 decisionId:{type:String,required:true,trim:true,immutable:true},principalId:{type:String,required:true,trim:true,immutable:true},
 reservationId:{type:String,required:true,trim:true,immutable:true},executionId:{type:String,required:true,trim:true,immutable:true},
 decisionSource:{type:String,required:true,trim:true,immutable:true},decisionKind:{type:String,required:true,trim:true,immutable:true},
 decidedBy:{type:String,required:true,trim:true,immutable:true},policyVersion:{type:String,required:true,trim:true,immutable:true},
 caseReference:{type:String,required:true,trim:true,immutable:true},entitlementRevision:{type:Number,required:true,min:1,immutable:true},decidedAt:{type:Date,required:true,immutable:true}
},{collection:COLLECTION,timestamps:true,minimize:false,strict:true});schema.index({decisionId:1},{unique:true});model=mongoose.models.MovieMentorTerminalDispositionDecision||mongoose.model("MovieMentorTerminalDispositionDecision",schema);return model;}
async function connect(){const u=uri();if(!u)fail("MOVIE_MENTOR_TERMINAL_DISPOSITION_DECISION_STORE_NOT_CONFIGURED","Terminal disposition decision store requires MONGO_URI or MONGODB_URI.");if(mongoose.connection.readyState===1)return;if(!connectionPromise)connectionPromise=mongoose.connect(u,{serverSelectionTimeoutMS:5000,maxPoolSize:10}).catch(error=>{connectionPromise=null;fail("MOVIE_MENTOR_TERMINAL_DISPOSITION_DECISION_AUTHORITY_UNAVAILABLE",`Terminal disposition decision store unavailable: ${error instanceof Error?error.message:"Mongo connection failed."}`,{retryable:true});});await connectionPromise;}
function normalize(v){v=plain(v);if(!v||v.domain!==DOMAIN||v.schema!==SCHEMA||!text(v.decisionId)||!text(v.principalId)||!text(v.reservationId)||!text(v.executionId)||text(v.decisionKind)!=="policy-approved-terminal-reservation-release"||!text(v.decisionSource)||!text(v.decidedBy)||!text(v.policyVersion)||!text(v.caseReference)||!Number.isSafeInteger(v.entitlementRevision)||v.entitlementRevision<1||!v.decidedAt)fail("MOVIE_MENTOR_TERMINAL_DISPOSITION_DECISION_INVALID","Durable terminal disposition decision is malformed.");return Object.freeze({decisionId:text(v.decisionId),principalId:text(v.principalId),reservationId:text(v.reservationId),executionId:text(v.executionId),decisionSource:text(v.decisionSource),decisionKind:text(v.decisionKind),decidedBy:text(v.decidedBy),policyVersion:text(v.policyVersion),caseReference:text(v.caseReference),entitlementRevision:v.entitlementRevision,decidedAt:new Date(v.decidedAt).toISOString(),durableAuthority:true});}
function same(a,b){return["decisionId","principalId","reservationId","executionId","decisionSource","decisionKind","decidedBy","policyVersion","caseReference","entitlementRevision","decidedAt"].every(k=>a[k]===b[k]);}
function createMovieMentorTerminalDispositionDecisionMongoStore({modelRef=null,connectStore=connect}={}){const M=()=>modelRef||getModel();let readinessPromise=null;
 async function ready(){if(!readinessPromise)readinessPromise=(async()=>{if(!modelRef)await connectStore();const active=M();if(typeof active?.createIndexes==="function")await active.createIndexes();else if(typeof active?.init==="function")await active.init();else fail("MOVIE_MENTOR_TERMINAL_DISPOSITION_DECISION_INDEX_AUTHORITY_UNAVAILABLE","Terminal disposition decision store cannot initialize its durable unique index.");let indexes;try{indexes=await active.collection.indexes();}catch(error){fail("MOVIE_MENTOR_TERMINAL_DISPOSITION_DECISION_PHYSICAL_AUTHORITY_UNAVAILABLE",`Terminal disposition decision physical index reality unavailable: ${error instanceof Error?error.message:"index inspection failed"}`,{retryable:true});}const unique=Array.isArray(indexes)&&indexes.some(index=>index?.unique===true&&index?.key&&Object.keys(index.key).length===1&&index.key.decisionId===1);if(!unique)fail("MOVIE_MENTOR_TERMINAL_DISPOSITION_DECISION_PHYSICAL_AUTHORITY_UNAVAILABLE","Terminal disposition decision authority requires an observed physical unique decisionId index.",{retryable:true});})().catch(error=>{readinessPromise=null;throw error;});await readinessPromise;}
 function requested(d={}){const n={decisionId:text(d.decisionId),principalId:text(d.principalId),reservationId:text(d.reservationId),executionId:text(d.executionId),decisionSource:text(d.decisionSource),decisionKind:text(d.decisionKind),decidedBy:text(d.decidedBy),policyVersion:text(d.policyVersion),caseReference:text(d.caseReference),entitlementRevision:d.entitlementRevision,decidedAt:text(d.decidedAt)};if(!n.decisionId||!n.principalId||!n.reservationId||!n.executionId||!n.decisionSource||n.decisionKind!=="policy-approved-terminal-reservation-release"||!n.decidedBy||!n.policyVersion||!n.caseReference||!Number.isSafeInteger(n.entitlementRevision)||n.entitlementRevision<1||!n.decidedAt||Number.isNaN(Date.parse(n.decidedAt)))fail("MOVIE_MENTOR_TERMINAL_DISPOSITION_DECISION_INVALID","Authorized terminal disposition requires complete durable policy coordinates.");n.decidedAt=new Date(n.decidedAt).toISOString();return n;}
 async function recordAuthorizedDecision({decision}={}){const n=requested(decision);await ready();const existing=await M().findOne({domain:DOMAIN,schema:SCHEMA,decisionId:n.decisionId}).lean().exec();if(existing){const resolved=normalize(existing);if(!same(resolved,n))fail("MOVIE_MENTOR_TERMINAL_DISPOSITION_DECISION_CONFLICT","Terminal disposition decision identity is already bound to different authority evidence.");return Object.freeze({authorized:true,idempotent:true,decision:resolved});}try{const created=await M().create({domain:DOMAIN,schema:SCHEMA,...n,decidedAt:new Date(n.decidedAt)});return Object.freeze({authorized:true,idempotent:false,decision:normalize(created)});}catch(error){if(error?.code===11000)return recordAuthorizedDecision({decision:n});if(error?.code?.startsWith?.("MOVIE_MENTOR_TERMINAL_DISPOSITION_"))throw error;fail("MOVIE_MENTOR_TERMINAL_DISPOSITION_DECISION_AUTHORITY_UNAVAILABLE",`Terminal disposition decision write failed: ${error instanceof Error?error.message:"write failed"}`,{retryable:true});}}
 async function resolveAuthorizedDecision({decisionId,principalId}={}){const id=text(decisionId),principal=text(principalId);if(!id||!principal)return null;await ready();const found=await M().findOne({domain:DOMAIN,schema:SCHEMA,decisionId:id,principalId:principal}).lean().exec();return found?normalize(found):null;}
 return Object.freeze({recordAuthorizedDecision,resolveAuthorizedDecision,getStatus:()=>Object.freeze({version:VERSION,domain:DOMAIN,configured:Boolean(modelRef)||Boolean(uri()),durable:true,decisionIdentityUnique:true,processLocalFallback:false})});}
export{VERSION as MOVIE_MENTOR_TERMINAL_DISPOSITION_DECISION_MONGO_STORE_VERSION,DOMAIN as MOVIE_MENTOR_TERMINAL_DISPOSITION_DECISION_DOMAIN,COLLECTION as MOVIE_MENTOR_TERMINAL_DISPOSITION_DECISION_COLLECTION,createMovieMentorTerminalDispositionDecisionMongoStore};export default createMovieMentorTerminalDispositionDecisionMongoStore;
