import { executeStructuredAI } from "./StructuredAIProviderClient.js";

const MOVIE_MENTOR_SPECIALIST_EXECUTOR_VERSION = "1.0.1";
const SPECIALIST_CONTRACT_VERSION = "1.0.0";
const LIVE_AGENT_IDS = new Set(["story","character"]);

function cleanString(value){return typeof value === "string" ? value.trim() : "";}
function asArray(value){return Array.isArray(value) ? value : [];}
function cloneValue(value){if(value===undefined)return undefined;try{return JSON.parse(JSON.stringify(value));}catch{return value;}}

const CONTRIBUTION_ITEM_SCHEMA={type:"object",additionalProperties:false,properties:{key:{type:["string","null"]},value:{type:["string","null"]},reason:{type:["string","null"]},confidence:{type:"number",minimum:0,maximum:1}},required:["key","value","reason","confidence"]};
function createSpecialistContributionSchema(agentId){return {type:"object",additionalProperties:false,properties:{agentId:{type:"string",enum:[agentId]},observations:{type:"array",items:CONTRIBUTION_ITEM_SCHEMA},provisionalSuggestions:{type:"array",items:CONTRIBUTION_ITEM_SCHEMA},risksAndConflicts:{type:"array",items:CONTRIBUTION_ITEM_SCHEMA},creatorConfirmedDependencies:{type:"array",items:{type:"object",additionalProperties:false,properties:{key:{type:"string"},value:{type:["string","null"]}},required:["key","value"]}},confidence:{type:"number",minimum:0,maximum:1},provenance:{type:"object",additionalProperties:false,properties:{source:{type:"string"},model:{type:["string","null"]},contractVersion:{type:"string"}},required:["source","model","contractVersion"]}},required:["agentId","observations","provisionalSuggestions","risksAndConflicts","creatorConfirmedDependencies","confidence","provenance"]};}
const SPECIALIST_CONTRIBUTION_SCHEMA=createSpecialistContributionSchema("story");

const BASE_RULES=`You are an internal iBand Movie Mentor specialist. You never speak directly to the creator. You provide advisory intelligence for Mentor synthesis only. Creator-confirmed truth is authoritative and cannot be overwritten. Do not claim that the creator decided anything they did not explicitly decide. creatorConfirmedDependencies may contain ONLY exact key/value pairs copied from the supplied creatorConfirmedContext; if none are directly relevant, return an empty array. Do not advance or recommend advancing CreatorJourneyEngine. Do not resolve semantic uncertainty yourself. If the supplied semantic intelligence contains unresolved or material ambiguity, do not invent meaning. All suggestions are provisional until the Mentor/creator confirms them. Return only the required structured contribution and use the exact agentId supplied in the input.`;
const AGENT_INSTRUCTIONS={
  story:`${BASE_RULES}\nYour specialty is story structure, dramatic direction, stakes, premise coherence and narrative possibilities. Focus on useful observations and a small number of provisional story options grounded in creator-confirmed context.`,
  character:`${BASE_RULES}\nYour specialty is character goals, relationships, arcs, motivation, emotional logic and character-driven conflict. Focus on useful observations and provisional character possibilities grounded in creator-confirmed context.`
};

function validateWorkOrder(workOrder){const agentId=cleanString(workOrder?.agentId);const issues=[];if(!LIVE_AGENT_IDS.has(agentId))issues.push("agent_not_live");if(workOrder?.creatorFacing!==false)issues.push("creator_facing_forbidden");if(workOrder?.mayAdvanceJourney!==false)issues.push("journey_advance_forbidden");if(workOrder?.mayOverwriteCreatorTruth!==false)issues.push("creator_truth_overwrite_forbidden");if(workOrder?.authority!=="mentor-provisional")issues.push("specialist_authority_must_be_mentor_provisional");return {valid:issues.length===0,issues,agentId};}

function validateContribution(candidate,workOrder){const issues=[];if(!candidate||typeof candidate!=="object")return {valid:false,issues:["missing_structured_contribution"],contribution:null};if(cleanString(candidate.agentId)!==cleanString(workOrder.agentId))issues.push("agent_identity_mismatch");const creatorTruth=new Map(asArray(workOrder?.input?.creatorConfirmedContext).filter(i=>cleanString(i?.key)).map(i=>[cleanString(i.key),String(i.value??"")]));for(const dep of asArray(candidate.creatorConfirmedDependencies)){const key=cleanString(dep?.key);if(!key||!creatorTruth.has(key)||String(dep?.value??"")!==creatorTruth.get(key))issues.push(`creator_dependency_not_confirmed:${key||"missing"}`);}return {valid:issues.length===0,issues,contribution:{agentId:cleanString(candidate.agentId),observations:asArray(candidate.observations),provisionalSuggestions:asArray(candidate.provisionalSuggestions),risksAndConflicts:asArray(candidate.risksAndConflicts),creatorConfirmedDependencies:asArray(candidate.creatorConfirmedDependencies),confidence:Number(candidate.confidence||0),provenance:{...(candidate.provenance||{}),source:"movie-mentor-specialist-agent",contractVersion:SPECIALIST_CONTRACT_VERSION},authority:"mentor-provisional",creatorFacing:false,mayAdvanceJourney:false,mayOverwriteCreatorTruth:false,requiresMentorSynthesis:true}};}

async function executeMovieMentorSpecialistWorkOrder(workOrder={}){const preflight=validateWorkOrder(workOrder);if(!preflight.valid){const error=new Error("Specialist work order failed iBand authority preflight.");error.code="SPECIALIST_WORK_ORDER_INVALID";error.validationIssues=preflight.issues;throw error;}const raw=await executeStructuredAI({task:`movie-mentor-specialist:${preflight.agentId}`,systemInstructions:AGENT_INSTRUCTIONS[preflight.agentId],input:{agentId:preflight.agentId,purpose:workOrder?.purpose||null,stageId:workOrder?.input?.stageId||null,taskId:workOrder?.input?.taskId||null,creatorMessage:workOrder?.input?.creatorMessage||null,semanticIntelligence:cloneValue(workOrder?.input?.semanticIntelligence||{}),creatorConfirmedContext:cloneValue(workOrder?.input?.creatorConfirmedContext||[]),projectJourney:cloneValue(workOrder?.input?.projectJourney||null)},schema:createSpecialistContributionSchema(preflight.agentId),schemaName:`movie_mentor_${preflight.agentId}_contribution`,metadata:{specialistExecutorVersion:MOVIE_MENTOR_SPECIALIST_EXECUTOR_VERSION,contractVersion:SPECIALIST_CONTRACT_VERSION}});if(!raw?.structured){const error=new Error("Specialist provider did not return structured contribution.");error.code="SPECIALIST_STRUCTURED_OUTPUT_INVALID";throw error;}raw.structured.provenance={source:"movie-mentor-specialist-agent",model:raw?.metadata?.model||null,contractVersion:SPECIALIST_CONTRACT_VERSION};const validation=validateContribution(raw.structured,workOrder);if(!validation.valid){const error=new Error("Specialist contribution failed iBand authority validation.");error.code="SPECIALIST_CONTRIBUTION_INVALID";error.validationIssues=validation.issues;throw error;}return {success:true,contribution:validation.contribution,usage:raw.usage||null,metadata:{...(raw.metadata||{}),specialistExecutorVersion:MOVIE_MENTOR_SPECIALIST_EXECUTOR_VERSION,specialistContractVersion:SPECIALIST_CONTRACT_VERSION}};}

async function executeMovieMentorSpecialistPlan(plan={}){const contributions=[];const skipped=[];const failures=[];for(const workOrder of asArray(plan?.workOrders)){if(!LIVE_AGENT_IDS.has(cleanString(workOrder?.agentId))){skipped.push({agentId:workOrder?.agentId||null,reason:"agent-not-live-yet"});continue;}try{const result=await executeMovieMentorSpecialistWorkOrder(workOrder);contributions.push(result.contribution);}catch(error){failures.push({agentId:workOrder?.agentId||null,code:error?.code||"SPECIALIST_EXECUTION_FAILED",message:error instanceof Error?error.message:"Specialist execution failed.",validationIssues:asArray(error?.validationIssues)});}}return {version:MOVIE_MENTOR_SPECIALIST_EXECUTOR_VERSION,contractVersion:SPECIALIST_CONTRACT_VERSION,status:failures.length?"partial":"completed",contributions,skipped,failures,authority:{creatorTruthDominates:true,contributionsAreMentorProvisional:true,specialistsMayAdvanceJourney:false,specialistsMaySpeakDirectlyToCreator:false,mentorMustSynthesize:true},liveAgents:[...LIVE_AGENT_IDS],extensionAgents:["scene","cinematography","continuity","sound-music","production"]};}

export {MOVIE_MENTOR_SPECIALIST_EXECUTOR_VERSION,SPECIALIST_CONTRACT_VERSION,SPECIALIST_CONTRIBUTION_SCHEMA,createSpecialistContributionSchema,LIVE_AGENT_IDS,validateWorkOrder,validateContribution,executeMovieMentorSpecialistWorkOrder,executeMovieMentorSpecialistPlan};
export default executeMovieMentorSpecialistPlan;
