import crypto from "crypto";

const VERSION="1.0.0",DOMAIN="iband.movie-mentor.commercial-purchase-intent-authority";
function text(v){return typeof v==="string"?v.trim():"";}
function fail(code,message,extras={}){const e=new Error(message);e.code=code;Object.assign(e,extras);throw e;}
function digest(v){return crypto.createHash("sha256").update(JSON.stringify(v)).digest("hex");}
function createMovieMentorCommercialPurchaseIntentAuthority({store,resolveCommercialPolicy,createCommercialIntentId=()=>crypto.randomUUID()}={}){
 if(!store||typeof store.create!=="function"||typeof store.resolve!=="function"||typeof resolveCommercialPolicy!=="function")fail("MOVIE_MENTOR_PURCHASE_INTENT_AUTHORITY_REQUIRED","Purchase-intent authority requires durable store and server-owned commercial policy resolver.");
 async function createPurchaseIntent({principalId,packageId}={}){const principal=text(principalId),pkg=text(packageId);if(!principal||!pkg)fail("MOVIE_MENTOR_PURCHASE_INTENT_REQUEST_INVALID","Authenticated principal and requested package are required.");const policy=await resolveCommercialPolicy({packageId:pkg});const snapshot={packageId:text(policy?.packageId),provider:text(policy?.provider),providerProductId:text(policy?.providerProductId),amountMinor:policy?.amountMinor,currency:text(policy?.currency).toUpperCase(),environment:text(policy?.environment),units:policy?.units,policyVersion:text(policy?.policyVersion)};if(snapshot.packageId!==pkg||!snapshot.provider||!snapshot.providerProductId||!Number.isSafeInteger(snapshot.amountMinor)||snapshot.amountMinor<0||!snapshot.currency||!snapshot.environment||!Number.isSafeInteger(snapshot.units)||snapshot.units<=0||!snapshot.policyVersion)fail("MOVIE_MENTOR_PURCHASE_INTENT_POLICY_INVALID","Server-owned commercial policy cannot authorize this package.");snapshot.policyDigest=digest(snapshot);const commercialIntentId=text(createCommercialIntentId());if(!commercialIntentId)fail("MOVIE_MENTOR_PURCHASE_INTENT_ID_INVALID","Purchase-intent identity could not be created.");const record=await store.create({commercialIntentId,principalId:principal,...snapshot});if(record?.commercialIntentId!==commercialIntentId||record?.principalId!==principal||record?.packageId!==pkg||record?.policyDigest!==snapshot.policyDigest)fail("MOVIE_MENTOR_PURCHASE_INTENT_RECORD_INVALID","Durable purchase-intent receipt does not preserve authoritative commercial binding.");return Object.freeze(record);}
 async function resolvePurchaseIntent({commercialIntentId}={}){return store.resolve({commercialIntentId});}
 return Object.freeze({createPurchaseIntent,resolvePurchaseIntent});
}
export{VERSION as MOVIE_MENTOR_COMMERCIAL_PURCHASE_INTENT_AUTHORITY_VERSION,DOMAIN as MOVIE_MENTOR_COMMERCIAL_PURCHASE_INTENT_AUTHORITY_DOMAIN,createMovieMentorCommercialPurchaseIntentAuthority};export default createMovieMentorCommercialPurchaseIntentAuthority;
