import { createHash, randomUUID } from "node:crypto";
import { applyMovieMentorCreatorStateTransition } from "./MovieMentorCreatorStateTransition.js";
import { readAuthoritativeTurnSource } from "./MovieMentorCreatorStateStore.js";
import { classifyCreatorTruth, assertCurrentCreatorTruthOnly } from "./MovieMentorCreatorTruthViewControl.js";

const MOVIE_MENTOR_CREATOR_DECISION_AUTHORITY_VERSION="1.4.0";
const CREATOR_DECISION_DOMAIN="iband.movie-mentor.creator-decision";
const CREATOR_DECISION_SCHEMA=1;
const POST_COMMIT_CREATOR_AUTHORITY_DOMAIN="iband.movie-mentor.post-commit-creator-authority";
const POST_COMMIT_CREATOR_AUTHORITY_SCHEMA=1;
function s(v){return typeof v==="string"?v.trim():"";}
function a(v){return Array.isArray(v)?v:[];}
function clone(v){if(v===undefined)return undefined;try{return JSON.parse(JSON.stringify(v));}catch{return v;}}
function stable(v){if(v===null||typeof v!=="object")return JSON.stringify(v);if(Array.isArray(v))return `[${v.map(stable).join(",")}]`;return `{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${stable(v[k])}`).join(",")}}`;}
function digest(v){return createHash("sha256").update(stable(v)).digest("hex");}
function error(code,message,issues=[]){const e=new Error(message);e.code=code;e.validationIssues=issues;return e;}
function commitmentIntent(message){const m=s(message);if(!m)return null;if(/\b(?:maybe|perhaps|might|could|thinking about|let me think|not sure)\b/i.test(m))return null;if(/\b(?:actually\s+)?(?:scrap|drop|remove|replace|change)\b/i.test(m))return "correction";if(/\b(?:yes[,.! ]*)?(?:(?:let['’]?s|we(?:'ll| will)|i(?:'ll| will)|definitely)\s+)?(?:use|go with|choose|keep|make|set|adopt)\b/i.test(m))return "adoption";if(/^\s*(?:yes|yeah|yep)[,.!]?\s*(?:do|use|go with)\s+that\b/i.test(m))return "adoption";return null;}
function resolvedReferences(semantic={}){return a(semantic?.continuationReferences).filter(r=>r?.status==="resolved"&&s(r?.expression));}
function explicitCreatorItems(semantic={}){return a(semantic?.understoodContext).filter(i=>i?.confidenceSource==="creator-explicit"&&s(i?.key));}
function decisionKeyFor({reference,item,intent}){if(reference)return `continuation.${s(reference.type)||"reference"}`;if(item)return `semantic.${s(item.key)}`;return `creator.${intent||"decision"}`;}
function stableTurnDecisionId(payload={}){const hex=digest(payload);return `${hex.slice(0,8)}-${hex.slice(8,12)}-4${hex.slice(13,16)}-8${hex.slice(17,20)}-${hex.slice(20,32)}`;}
function decisionIdentityPayload(candidate={},creatorTurnId=null){return{creatorTurnId:s(creatorTurnId||candidate.creatorTurnId)||null,projectId:s(candidate.projectId)||null,decisionKey:s(candidate.decisionKey),intent:s(candidate.intent),value:clone(candidate.value),creatorMessage:s(candidate.creatorMessage),evidenceSource:s(candidate.evidenceSource),reference:clone(candidate.reference),semanticKey:s(candidate.semanticKey)||null,authority:s(candidate.authority)};}
function decisionFingerprintPayload(candidate={}){return{domain:candidate.domain,schema:candidate.schema,decisionId:candidate.decisionId,creatorTurnId:candidate.creatorTurnId||null,projectId:candidate.projectId,decisionKey:candidate.decisionKey,intent:candidate.intent,value:clone(candidate.value),creatorMessage:candidate.creatorMessage,evidenceSource:candidate.evidenceSource,reference:clone(candidate.reference),semanticKey:candidate.semanticKey,authority:candidate.authority};}
function bindCandidateToCreatorTurn(candidate={},creatorTurnId=null){const turnId=s(creatorTurnId||candidate.creatorTurnId);if(!turnId)return clone(candidate);if(s(candidate.creatorTurnId)&&s(candidate.creatorTurnId)!==turnId)throw error("MOVIE_MENTOR_CREATOR_DECISION_TURN_MISMATCH","Creator decision belongs to another creator turn.");const bound=clone(candidate);bound.creatorTurnId=turnId;bound.decisionId=stableTurnDecisionId(decisionIdentityPayload(bound,turnId));bound.fingerprint=digest(decisionFingerprintPayload(bound));return bound;}
function buildCreatorDecisionCandidate({creatorMessage,semanticIntelligence={},projectId=null,actorRole="creator",creatorTurnId=null}={}){
 const message=s(creatorMessage);if(actorRole!=="creator")return {status:"rejected",reason:"creator_origin_required"};const intent=commitmentIntent(message);if(!intent)return {status:"none",reason:"no_explicit_creator_commitment"};
 const refs=resolvedReferences(semanticIntelligence);const explicit=explicitCreatorItems(semanticIntelligence);let reference=null,item=null,value=null,evidenceSource=null;
 if(refs.length===1){reference=clone(refs[0]);value=clone(reference.resolvedValue);evidenceSource="validated-continuation-reference";}else if(refs.length>1)return {status:"rejected",reason:"multiple_resolved_references_require_specificity"};else if(explicit.length===1){item=clone(explicit[0]);value=clone(item.value);evidenceSource="creator-explicit-semantic";}else if(explicit.length>1)return {status:"rejected",reason:"multiple_creator_explicit_items_require_specificity"};else return {status:"rejected",reason:"explicit_commitment_lacks_resolved_value"};
 const decisionKey=decisionKeyFor({reference,item,intent});const candidate={domain:CREATOR_DECISION_DOMAIN,schema:CREATOR_DECISION_SCHEMA,decisionId:randomUUID(),creatorTurnId:null,projectId:s(projectId)||null,decisionKey,intent,value,creatorMessage:message,evidenceSource,reference:reference?{expression:reference.expression,type:reference.type,resolvedValue:clone(reference.resolvedValue),source:reference.source||null}:null,semanticKey:item?.key||null,authority:"creator-explicit",createdAt:new Date().toISOString()};const bound=bindCandidateToCreatorTurn(candidate,creatorTurnId);if(!s(bound.creatorTurnId))bound.fingerprint=digest(decisionFingerprintPayload(bound));return {status:"candidate",candidate:bound};
}
function mergeDecisionIntoCreatorContext(current=[],candidate){const retained=[];for(const item of a(current)){if(s(item?.decisionKey)===candidate.decisionKey)retained.push({...clone(item),current:false,supersededByDecisionId:candidate.decisionId});else retained.push(clone(item));}retained.push({key:`creatorDecision.${candidate.decisionKey}`,value:clone(candidate.value),authority:"creator",confidenceSource:"creator-confirmed",decisionKey:candidate.decisionKey,decisionId:candidate.decisionId,creatorTurnId:s(candidate.creatorTurnId)||null,decisionFingerprint:candidate.fingerprint,decisionIntent:candidate.intent,evidence:candidate.creatorMessage,evidenceSource:candidate.evidenceSource,current:true,createdAt:candidate.createdAt});return retained;}
function buildPostCommitCreatorAuthority(after={}){const classified=classifyCreatorTruth(a(after.creatorConfirmedContext));if(classified.rejected.length){throw error("MOVIE_MENTOR_POST_COMMIT_AUTHORITY_INVALID","Post-commit creator authority readback contains malformed live creator truth.",classified.rejected.map(item=>item.reason||"invalid_creator_truth_item"));}const currentCreatorTruth=classified.active;assertCurrentCreatorTruthOnly(currentCreatorTruth);const revision=Number(after.revision),generation=Number(after.creatorStateGeneration);if(!Number.isSafeInteger(revision)||revision<0||!Number.isSafeInteger(generation)||generation<0||!s(after.revisionAuthorityReference)||!s(after.creatorStateFingerprint)||!s(after.creatorAuthorityReference)||!s(after.snapshotReference))throw error("MOVIE_MENTOR_POST_COMMIT_AUTHORITY_INVALID","Post-commit creator authority readback is missing required durable authority fields.");return Object.freeze({domain:POST_COMMIT_CREATOR_AUTHORITY_DOMAIN,schema:POST_COMMIT_CREATOR_AUTHORITY_SCHEMA,authority:"durable-post-commit-creator-state",projectId:s(after.projectId)||null,creatorSessionId:s(after.creatorSessionId)||null,revision,revisionAuthorityReference:s(after.revisionAuthorityReference),creatorState:Object.freeze({generation,fingerprint:s(after.creatorStateFingerprint),authorityReference:s(after.creatorAuthorityReference)}),snapshotReference:s(after.snapshotReference),capturedAt:s(after.capturedAt)||null,currentCreatorTruth:Object.freeze(clone(currentCreatorTruth))});}
function sameTurnCommitted(before={},candidate={}){const turnId=s(candidate.creatorTurnId);if(!turnId)return null;return a(before.creatorConfirmedContext).find(item=>s(item?.creatorTurnId)===turnId)||null;}
function idempotentDecisionResult(before,candidate,prior){if(prior.decisionId!==candidate.decisionId||prior.decisionFingerprint!==candidate.fingerprint||prior.decisionKey!==candidate.decisionKey)throw error("MOVIE_MENTOR_CREATOR_DECISION_TURN_CONFLICT","Stable creator turn already committed a different durable creator decision.");const postCommitCreatorAuthority=buildPostCommitCreatorAuthority(before);return{status:"committed",idempotent:true,recovered:true,candidate:clone(candidate),revision:before.revision,creatorStateGeneration:before.creatorStateGeneration,committedContext:clone(prior),postCommitCreatorAuthority};}
async function commitCreatorDecision({candidate,expectedRevision,projectId,creatorSessionId=null,creatorTurnId=null}={},deps={}){
 if(!candidate||candidate.domain!==CREATOR_DECISION_DOMAIN||candidate.schema!==CREATOR_DECISION_SCHEMA||candidate.authority!=="creator-explicit")throw error("MOVIE_MENTOR_CREATOR_DECISION_INVALID","Creator decision candidate is not authoritative.");if(s(candidate.projectId)&&s(projectId)&&s(candidate.projectId)!==s(projectId))throw error("MOVIE_MENTOR_CREATOR_DECISION_PROJECT_MISMATCH","Creator decision belongs to another project.");const boundCandidate=bindCandidateToCreatorTurn(candidate,creatorTurnId);if(s(creatorTurnId)&&!s(boundCandidate.creatorTurnId))throw error("MOVIE_MENTOR_CREATOR_DECISION_TURN_REQUIRED","Stable creator turn authority could not bind the creator decision.");
 const read=deps.readAuthoritativeTurnSource||readAuthoritativeTurnSource;const transition=deps.applyMovieMentorCreatorStateTransition||applyMovieMentorCreatorStateTransition;const identity={projectId:s(projectId)||s(boundCandidate.projectId)||null,creatorSessionId:s(creatorSessionId)||null};const before=await read(identity);const prior=sameTurnCommitted(before,boundCandidate);if(prior)return idempotentDecisionResult(before,boundCandidate,prior);
 if(before.revision!==expectedRevision)throw error("MOVIE_MENTOR_CREATOR_DECISION_REVISION_CONFLICT","Creator decision was based on stale creator reality.");const merged=mergeDecisionIntoCreatorContext(before.creatorConfirmedContext,boundCandidate);let written;try{written=await transition({projectId:identity.projectId,creatorSessionId:identity.creatorSessionId,source:"creator-decision",expectedRevision,state:{creatorConfirmedContext:merged}},{readAuthoritativeTurnSource:read,writeAuthoritativeCreatorState:deps.writeAuthoritativeCreatorState,creatorStateMutationAuthority:deps.creatorStateMutationAuthority});}catch(writeError){if(s(boundCandidate.creatorTurnId)){const raced=await read(identity);const racedPrior=sameTurnCommitted(raced,boundCandidate);if(racedPrior)return idempotentDecisionResult(raced,boundCandidate,racedPrior);}throw writeError;}
 const after=await read(identity);const committed=a(after.creatorConfirmedContext).find(i=>i?.decisionId===boundCandidate.decisionId&&i?.current===true);if(!committed||committed.decisionFingerprint!==boundCandidate.fingerprint||after.revision!==written.revision)throw error("MOVIE_MENTOR_CREATOR_DECISION_READBACK_FAILED","Durable creator decision readback did not prove the committed decision.");const postCommitCreatorAuthority=buildPostCommitCreatorAuthority(after);return {status:"committed",idempotent:false,candidate:clone(boundCandidate),revision:after.revision,creatorStateGeneration:after.creatorStateGeneration,committedContext:clone(committed),postCommitCreatorAuthority};
}

export{MOVIE_MENTOR_CREATOR_DECISION_AUTHORITY_VERSION,CREATOR_DECISION_DOMAIN,CREATOR_DECISION_SCHEMA,POST_COMMIT_CREATOR_AUTHORITY_DOMAIN,POST_COMMIT_CREATOR_AUTHORITY_SCHEMA,commitmentIntent,buildCreatorDecisionCandidate,mergeDecisionIntoCreatorContext,buildPostCommitCreatorAuthority,commitCreatorDecision};
export default buildCreatorDecisionCandidate;
