import {createMovieMentorCommercialReversalAuthority} from "./MovieMentorCommercialReversalAuthority.js";
import {createMovieMentorCommercialReversalMongoStore,getMovieMentorCommercialReversalMongoStoreStatus} from "./MovieMentorCommercialReversalMongoStore.js";
const VERSION="1.3.0",STORE_DOMAIN="iband.movie-mentor.commercial-reversal-store",SOURCE_DOMAIN="iband.movie-mentor.commercial-reversal-authority",AUTHORITY_DOMAIN="iband.movie-mentor.production-commercial-reversal-authority";
const productionAuthorityProofs=new WeakMap();
function ownedStatus(target){if(typeof target?.getStatus!=="function")return null;try{const s=target.getStatus();return s&&typeof s==="object"?s:null;}catch{return null;}}
function storeProven(s){return s?.domain===STORE_DOMAIN&&s?.configured===true&&s?.atomicity==="mongo-transaction"&&s?.reversalIdentityUnique===true&&s?.currentEntitlementSuspension===true&&s?.reversalReceiptDurable===true&&s?.pendingReversalHistoryDurable===true&&s?.pendingReversalIdentityUnique===true&&s?.pendingReversalReconciliation===true&&s?.processLocalFallback===false;}
function sourceProven(s){return s?.domain===SOURCE_DOMAIN&&s?.durableAtomicSuspension===true&&s?.reversalIdentityUnique===true&&s?.currentEntitlementSuspension===true&&s?.reversalReceiptDurable===true&&s?.pendingReversalHistoryDurable===true&&s?.pendingReversalIdentityUnique===true&&s?.pendingReversalReconciliation===true&&s?.pendingReversalAcknowledgement===true&&s?.pendingHistorySurvivesUntilRevocationAcknowledgement===true&&s?.storeCapabilityProven===true&&s?.storeStatus?.domain===STORE_DOMAIN&&s?.processLocalFallback===false;}
function authorityStatus(sourceAuthorityStatus){return Object.freeze({version:VERSION,domain:AUTHORITY_DOMAIN,production:true,durableAtomicSuspension:true,reversalIdentityUnique:true,currentEntitlementSuspension:true,reversalReceiptDurable:true,pendingReversalHistoryDurable:true,pendingReversalIdentityUnique:true,pendingReversalReconciliation:true,pendingReversalAcknowledgement:true,pendingHistorySurvivesUntilRevocationAcknowledgement:true,sourceAuthorityProvenanceRequired:true,sourceAuthorityStatus,ownerBoundProof:true,processLocalFallback:false});}
function getMovieMentorProductionCommercialReversalAuthorityOwnedStatus(authority){const expected=productionAuthorityProofs.get(authority)||null;if(!expected)return null;const actual=ownedStatus(authority);return actual===expected?expected:null;}
function isMovieMentorProductionCommercialReversalAuthorityOwnedProof(authority,status=null){const expected=getMovieMentorProductionCommercialReversalAuthorityOwnedStatus(authority);return expected!==null&&(status===null||status===expected);}
function createMovieMentorProductionCommercialReversalComposition({store=null,allowedEvidenceSources=null,allowedEvidenceKinds=null}={}){const injected=Boolean(store),storeStatus=injected?ownedStatus(store):getMovieMentorCommercialReversalMongoStoreStatus();if(!storeProven(storeStatus))return Object.freeze({ready:false,reason:storeStatus?.configured===true?"commercial-reversal-capability-not-proven":"commercial-reversal-store-not-configured",authority:null,storeStatus});try{const durableStore=store||createMovieMentorCommercialReversalMongoStore();const raw=createMovieMentorCommercialReversalAuthority({store:durableStore,allowedEvidenceSources,allowedEvidenceKinds});const sourceStatus=ownedStatus(raw);if(!sourceProven(sourceStatus))return Object.freeze({ready:false,reason:"commercial-reversal-source-authority-not-proven",authority:null,storeStatus,sourceAuthorityStatus:sourceStatus});const status=authorityStatus(sourceStatus);const authority=Object.freeze({suspendVerifiedReversal:raw.suspendVerifiedReversal,preserveVerifiedReversalHistory:raw.preserveVerifiedReversalHistory,reconcilePendingReversals:raw.reconcilePendingReversals,acknowledgePendingReversals:raw.acknowledgePendingReversals,getStatus:()=>status});productionAuthorityProofs.set(authority,status);return Object.freeze({ready:true,reason:"durable-commercial-reversal-authority-composed",authority,authorityStatus:status,sourceAuthorityStatus:sourceStatus,storeStatus});}catch(error){return Object.freeze({ready:false,reason:error?.code||"commercial-reversal-composition-failed",authority:null,storeStatus});}}
export{VERSION as MOVIE_MENTOR_PRODUCTION_COMMERCIAL_REVERSAL_COMPOSITION_VERSION,AUTHORITY_DOMAIN as MOVIE_MENTOR_PRODUCTION_COMMERCIAL_REVERSAL_AUTHORITY_DOMAIN,createMovieMentorProductionCommercialReversalComposition,getMovieMentorProductionCommercialReversalAuthorityOwnedStatus,isMovieMentorProductionCommercialReversalAuthorityOwnedProof};export default createMovieMentorProductionCommercialReversalComposition;
