/** Movie Mentor Recovery Finalization Reconciliation Control v1.3.0 — reconcile only the complete Recovery Authority Digest v2 envelope and, when supplied, the exact recovery-reality digest. */
import{proveDistributedFinalizationAbsence}from"./MovieMentorRecoveryDistributedAbsenceControl.js";
import{RECOVERY_AUTHORITY_BINDING_HASH_DOMAIN as DOMAIN,RECOVERY_AUTHORITY_BINDING_HASH_SCHEMA as SCHEMA}from"./MovieMentorRecoveryAuthority.js";
const VERSION="1.3.0",CONTROL_ID="recovery-finalization-reconciliation-control",AUTHORITY="recovery-finalization-reconciliation-contract-only",s=v=>typeof v==="string"?v.trim():"",i=v=>Number.isSafeInteger(v)&&v>=0?v:null;
const valid=(v,{domainKey="bindingFingerprintDomain",schemaKey="bindingFingerprintSchema",fingerprintKey="bindingFingerprint"}={})=>v?.[domainKey]===DOMAIN&&v?.[schemaKey]===SCHEMA&&/^[a-f0-9]{64}$/i.test(s(v?.[fingerprintKey]));
const validReality=v=>/^[a-f0-9]{64}$/i.test(s(v));
async function reconcileFinalRecovery({incidentId,recoveryEpoch,authorityDecision,stateTransition,expectedStateReference,reconciliationRealityHash}={},d={}){
 const expectedReality=s(reconciliationRealityHash);
 if(!s(incidentId)||i(recoveryEpoch)===null)return{reconciled:false,reasons:["incident_and_recovery_epoch_required"]};
 if(expectedReality&&!validReality(expectedReality))return{reconciled:false,reasons:["reconciliation_recovery_reality_hash_invalid"]};
 if(authorityDecision?.authorized!==true||!s(authorityDecision.reference)||!s(authorityDecision.authorityReference)||!s(authorityDecision.bindingFingerprint))return{reconciled:false,reasons:["authorized_recovery_decision_required"]};
 if(!valid(authorityDecision))return{reconciled:false,reasons:["recovery_authority_binding_digest_protocol_mismatch"]};
 if(stateTransition?.applied!==true||stateTransition?.to!=="globally_recovered"||stateTransition.recoveryEpoch!==recoveryEpoch||!s(stateTransition.transitionReference)||s(stateTransition.recoveryAuthorityReference)!==s(authorityDecision.reference)||s(stateTransition.recoveryAuthorityBindingFingerprint)!==s(authorityDecision.bindingFingerprint))return{reconciled:false,reasons:["exact_state_transition_required"]};
 if(!valid(stateTransition,{domainKey:"recoveryAuthorityBindingFingerprintDomain",schemaKey:"recoveryAuthorityBindingFingerprintSchema",fingerprintKey:"recoveryAuthorityBindingFingerprint"}))return{reconciled:false,reasons:["recovery_state_authority_digest_protocol_mismatch"]};
 if(stateTransition.recoveryAuthorityBindingFingerprintDomain!==authorityDecision.bindingFingerprintDomain||stateTransition.recoveryAuthorityBindingFingerprintSchema!==authorityDecision.bindingFingerprintSchema)return{reconciled:false,reasons:["authority_state_triangle_binding_mismatch"]};
 if(!s(expectedStateReference))return{reconciled:false,reasons:["expected_state_reference_required"]};
 if(typeof d.readFinalRecoveryByIdentity!=="function")return{reconciled:false,reasons:["durable_identity_read_adapter_required"]};
 const identity={incidentId:s(incidentId),recoveryEpoch,authorityDecisionReference:s(authorityDecision.reference),authorityReference:s(authorityDecision.authorityReference),bindingFingerprint:s(authorityDecision.bindingFingerprint),bindingFingerprintDomain:DOMAIN,bindingFingerprintSchema:SCHEMA,previousStateReference:s(expectedStateReference),transitionReference:s(stateTransition.transitionReference)};
 let durable;try{durable=await d.readFinalRecoveryByIdentity({identity})}catch{return{reconciled:false,indeterminate:true,reasons:["final_recovery_identity_read_failed"]}};
 if(durable?.found!==true){const absence=await proveDistributedFinalizationAbsence({identity},{readAbsenceViews:d.readAbsenceViews,verifyAbsenceAuthority:d.verifyAbsenceAuthority,requiredQuorum:d.requiredAbsenceQuorum??2});if(absence?.valid!==true)return{reconciled:false,indeterminate:true,status:"distributed_absence_unproven",safeToRetry:false,reasons:["final_recovery_absence_not_quorum_proven",...(absence?.reasons||[])],identity};return{reconciled:true,committed:false,status:"distributed_reconciling",safeToRetry:true,retryMustUseSameIdentity:true,absenceReference:s(absence.reference),reasons:["no_matching_final_commit_quorum_proven"],identity}};
 if(durable?.durable!==true||durable?.sameAtomicTransaction!==true||!s(durable?.commitReference))return{reconciled:false,indeterminate:true,reasons:["matching_final_commit_not_proven_durable"]};
 if(expectedReality&&(!validReality(durable?.reconciliationRealityHash)||s(durable.reconciliationRealityHash)!==expectedReality))return{reconciled:false,indeterminate:true,reasons:["durable_final_commit_recovery_reality_mismatch"]};
 const h=durable.authorityHighWatermark,g=durable.globalState;if(!h||!g)return{reconciled:false,indeterminate:true,reasons:["partial_final_commit_view_denied"]};
 if(!valid(h)||!valid(g))return{reconciled:false,indeterminate:true,reasons:["durable_final_commit_authority_digest_protocol_mismatch"]};
 if(h.recoveryEpoch!==recoveryEpoch||s(h.decisionReference)!==identity.authorityDecisionReference||s(h.bindingFingerprint)!==identity.bindingFingerprint||h.bindingFingerprintDomain!==identity.bindingFingerprintDomain||h.bindingFingerprintSchema!==identity.bindingFingerprintSchema||s(g.state)!=="globally_recovered"||g.recoveryEpoch!==recoveryEpoch||s(g.authorityDecisionReference)!==identity.authorityDecisionReference||s(g.bindingFingerprint)!==identity.bindingFingerprint||g.bindingFingerprintDomain!==identity.bindingFingerprintDomain||g.bindingFingerprintSchema!==identity.bindingFingerprintSchema||s(g.transitionReference)!==identity.transitionReference)return{reconciled:false,indeterminate:true,reasons:["durable_final_commit_identity_mismatch"]};
 return{reconciled:true,committed:true,finalized:true,status:"globally_recovered",scope:"global",incidentId:identity.incidentId,recoveryEpoch,commitReference:s(durable.commitReference),durableReference:s(durable.reference),authorityDecisionReference:identity.authorityDecisionReference,bindingFingerprint:identity.bindingFingerprint,bindingFingerprintDomain:identity.bindingFingerprintDomain,bindingFingerprintSchema:identity.bindingFingerprintSchema,transitionReference:identity.transitionReference,reconciliationRealityHash:expectedReality||s(durable.reconciliationRealityHash),safeToRetry:false,reasons:[]};
}
function getRecoveryFinalizationReconciliationManifest(){return{id:CONTROL_ID,name:"Movie Mentor Recovery Finalization Reconciliation Control",version:VERSION,status:"standalone-dormant-not-wired",authority:AUTHORITY,deterministicControl:true,aiAgent:false,failClosed:true,purpose:"After crash/ACK loss, resolve only an exact durable Recovery Authority Digest v2 identity and, when present, the exact recovery-reality digest; absence permits retry only after authoritative distributed quorum proof.",restrictions:["no-blind-final-cas-retry","authority-v2-domain-and-schema-required","legacy-cross-protocol-and-wrong-schema-identities-denied","supplied-recovery-reality-must-match-durable-readback","single-reader-absence-never-authorizes-retry","distributed-authoritative-absence-quorum-required","matching-durable-atomic-tuple-may-be-adopted","partial-conflicting-or-wrong-universe-view-remains-indeterminate"]}}
export{VERSION as RECOVERY_FINALIZATION_RECONCILIATION_VERSION,CONTROL_ID as RECOVERY_FINALIZATION_RECONCILIATION_ID,AUTHORITY as RECOVERY_FINALIZATION_RECONCILIATION_AUTHORITY,reconcileFinalRecovery,getRecoveryFinalizationReconciliationManifest};export default reconcileFinalRecovery;
