import { executeStructuredAI } from "./StructuredAIProviderClient.js";
import { assertCurrentCreatorTruthOnly } from "./MovieMentorCreatorTruthViewControl.js";
import { DERIVED_CONTINUITY_AUTHORITY, createDerivedContinuityConstraint, buildContinuityConsequenceEnvelope } from "./MovieMentorContinuityConsequenceAuthority.js";

const MOVIE_MENTOR_CONTINUITY_AGENT_VERSION="2.0.0";
const CONTINUITY_CONTRACT_VERSION="2.0.0";
const CONTINUITY_AGENT_ID="continuity";
const CONTINUITY_AUTHORITY="mentor-provisional";
const CONTINUITY_CATEGORIES=["character","relationship","knowledge","location","timeline","event","injury","appearance","costume","prop","object-state","environment","story-thread","cause-effect","other"];
const s=v=>typeof v==="string"?v.trim():""; const a=v=>Array.isArray(v)?v:[]; const clone=v=>{if(v===undefined)return undefined;try{return JSON.parse(JSON.stringify(v));}catch{return v;}};
const DEP={type:"object",additionalProperties:false,properties:{key:{type:"string"},value:{type:["string","null"]}},required:["key","value"]};
const DER={type:"object",additionalProperties:false,properties:{category:{type:"string",enum:CONTINUITY_CATEGORIES},key:{type:["string","null"]},value:{type:["string","null"]},reason:{type:["string","null"]},confidence:{type:"number",minimum:0,maximum:1},dependencies:{type:"array",items:DEP}},required:["category","key","value","reason","confidence","dependencies"]};
const CONFLICT={type:"object",additionalProperties:false,properties:{key:{type:["string","null"]},category:{type:"string",enum:CONTINUITY_CATEGORIES},existingValue:{type:["string","null"]},proposedValue:{type:["string","null"]},severity:{type:"string",enum:["low","medium","high","critical"]},reason:{type:["string","null"]},requiresCreatorDecision:{type:"boolean"},confidence:{type:"number",minimum:0,maximum:1}},required:["key","category","existingValue","proposedValue","severity","reason","requiresCreatorDecision","confidence"]};
const QUESTION={type:"object",additionalProperties:false,properties:{key:{type:["string","null"]},category:{type:"string",enum:CONTINUITY_CATEGORIES},question:{type:["string","null"]},reason:{type:["string","null"]},confidence:{type:"number",minimum:0,maximum:1}},required:["key","category","question","reason","confidence"]};
const CONTINUITY_OUTPUT_SCHEMA={type:"object",additionalProperties:false,properties:{agentId:{type:"string",enum:[CONTINUITY_AGENT_ID]},derivedConstraints:{type:"array",items:DER},continuityConflicts:{type:"array",items:CONFLICT},unresolvedContinuityQuestions:{type:"array",items:QUESTION},provisionalSuggestions:{type:"array",items:QUESTION},confidence:{type:"number",minimum:0,maximum:1},provenance:{type:"object",additionalProperties:false,properties:{source:{type:"string"},model:{type:["string","null"]},contractVersion:{type:"string"}},required:["source","model","contractVersion"]}},required:["agentId","derivedConstraints","continuityConflicts","unresolvedContinuityQuestions","provisionalSuggestions","confidence","provenance"]};
const CONTINUITY_INSTRUCTIONS=`You are the internal iBand Movie Mentor Continuity Agent. Never speak directly to the creator. THE AI CANNOT CREATE CANON; THE CREATOR CREATES CANON. Only CURRENT creator-confirmed truth supplied in currentCreatorTruth is canon. Superseded decisions are history and must never be live canon. Derive continuity consequences only when they logically follow from current creator truth and list exact key/value dependencies. Derived constraints are authority=derived-continuity, never creator-confirmed, never canon. Ambiguous or underdetermined consequences belong in unresolvedContinuityQuestions. Contradictions must be reported, never silently repaired. High/critical conflicts or conflicts requiring creator decision block advancement. Never overwrite creator truth or advance CreatorJourneyEngine. Specialties include timeline/age, character knowledge, relationship, location, object state, prop, injury, cause/effect and story-thread continuity. Return only the required structured contract.`;
function validateContinuityWorkOrder(w={}){const issues=[];if(s(w.agentId)!==CONTINUITY_AGENT_ID)issues.push("continuity_agent_identity_required");if(w.creatorFacing!==false)issues.push("creator_facing_forbidden");if(w.mayAdvanceJourney!==false)issues.push("journey_advance_forbidden");if(w.mayOverwriteCreatorTruth!==false)issues.push("creator_truth_overwrite_forbidden");if(w.mayCreateCanon!==false)issues.push("canon_creation_forbidden");if(w.authority!==CONTINUITY_AUTHORITY)issues.push("continuity_authority_must_be_mentor_provisional");try{assertCurrentCreatorTruthOnly(w?.input?.currentCreatorTruth||[]);}catch(e){issues.push(...a(e?.validationIssues));}return{valid:!issues.length,issues};}
function createContinuityWorkOrder({creatorMessage=null,semanticIntelligence={},currentCreatorTruth=[],projectJourney=null,memoryContext=null,currentScene=null,previousScenes=[],stageId=null,taskId=null,metadata={}}={}){assertCurrentCreatorTruthOnly(currentCreatorTruth);return{agentId:CONTINUITY_AGENT_ID,purpose:"Protect current creator reality and derive non-canonical continuity consequences.",authority:CONTINUITY_AUTHORITY,creatorFacing:false,mayAdvanceJourney:false,mayOverwriteCreatorTruth:false,mayCreateCanon:false,requiresMentorSynthesis:true,input:{creatorMessage:s(creatorMessage)||null,semanticIntelligence:clone(semanticIntelligence),currentCreatorTruth:clone(a(currentCreatorTruth)),projectJourney:clone(projectJourney),memoryContext:clone(memoryContext),currentScene:clone(currentScene),previousScenes:clone(a(previousScenes)),stageId:s(stageId)||null,taskId:s(taskId)||null,metadata:clone(metadata||{})}};}
function validateAndBuildContribution(c={},w={}){const issues=[];if(!c||typeof c!=="object")return{valid:false,issues:["missing_continuity_contribution"],contribution:null};if(s(c.agentId)!==CONTINUITY_AGENT_ID)issues.push("continuity_agent_identity_mismatch");const truth=a(w?.input?.currentCreatorTruth);const constraints=[];for(const raw of a(c.derivedConstraints)){try{constraints.push(createDerivedContinuityConstraint(raw,truth));}catch(e){issues.push(...(a(e?.validationIssues).length?a(e.validationIssues):[e?.code||"continuity_derivation_invalid"]));}}let envelope=null;if(!issues.length){try{envelope=buildContinuityConsequenceEnvelope({creatorConfirmedContext:truth,constraints,conflicts:a(c.continuityConflicts),unresolvedQuestions:a(c.unresolvedContinuityQuestions)});}catch(e){issues.push(...(a(e?.validationIssues).length?a(e.validationIssues):[e?.code||"continuity_envelope_invalid"]));}}return{valid:!issues.length,issues,contribution:{agentId:CONTINUITY_AGENT_ID,derivedConstraints:constraints,continuityConflicts:a(c.continuityConflicts),unresolvedContinuityQuestions:a(c.unresolvedContinuityQuestions),provisionalSuggestions:a(c.provisionalSuggestions),continuityConsequenceEnvelope:envelope,confidence:Number(c.confidence||0),provenance:{...(c.provenance||{}),source:"movie-mentor-continuity-agent",contractVersion:CONTINUITY_CONTRACT_VERSION},authority:CONTINUITY_AUTHORITY,derivedAuthority:DERIVED_CONTINUITY_AUTHORITY,creatorFacing:false,mayAdvanceJourney:false,mayOverwriteCreatorTruth:false,mayCreateCanon:false,mayPromoteInferenceToCanon:false,requiresMentorSynthesis:true}};}
async function executeMovieMentorContinuityAgent(w={}){const pre=validateContinuityWorkOrder(w);if(!pre.valid){const e=new Error("Continuity Agent work order failed current-creator authority preflight.");e.code="CONTINUITY_WORK_ORDER_INVALID";e.validationIssues=pre.issues;throw e;}const raw=await executeStructuredAI({task:"movie-mentor-specialist:continuity",systemInstructions:CONTINUITY_INSTRUCTIONS,input:{agentId:CONTINUITY_AGENT_ID,purpose:w?.purpose||null,creatorMessage:w?.input?.creatorMessage||null,semanticIntelligence:clone(w?.input?.semanticIntelligence||{}),currentCreatorTruth:clone(w?.input?.currentCreatorTruth||[]),projectJourney:clone(w?.input?.projectJourney||null),memoryContext:clone(w?.input?.memoryContext||null),currentScene:clone(w?.input?.currentScene||null),previousScenes:clone(w?.input?.previousScenes||[])},schema:CONTINUITY_OUTPUT_SCHEMA,schemaName:"movie_mentor_continuity_contribution",metadata:{continuityAgentVersion:MOVIE_MENTOR_CONTINUITY_AGENT_VERSION,continuityContractVersion:CONTINUITY_CONTRACT_VERSION,creatorTruthDominates:true,derivedContinuityIsNotCanon:true}});if(!raw?.structured){const e=new Error("Continuity Agent provider did not return structured intelligence.");e.code="CONTINUITY_STRUCTURED_OUTPUT_INVALID";throw e;}raw.structured.provenance={source:"movie-mentor-continuity-agent",model:raw?.metadata?.model||null,contractVersion:CONTINUITY_CONTRACT_VERSION};const v=validateAndBuildContribution(raw.structured,w);if(!v.valid){const e=new Error("Continuity Agent contribution failed authority validation.");e.code="CONTINUITY_CONTRIBUTION_INVALID";e.validationIssues=v.issues;throw e;}return{success:true,contribution:v.contribution,usage:raw.usage||null,metadata:{...(raw.metadata||{}),continuityAgentVersion:MOVIE_MENTOR_CONTINUITY_AGENT_VERSION,continuityContractVersion:CONTINUITY_CONTRACT_VERSION}};}
function getContinuityAgentManifest(){return{id:CONTINUITY_AGENT_ID,name:"Movie Mentor Continuity Agent",version:MOVIE_MENTOR_CONTINUITY_AGENT_VERSION,contractVersion:CONTINUITY_CONTRACT_VERSION,status:"standalone-authority-migrated-not-live",authority:CONTINUITY_AUTHORITY,derivedAuthority:DERIVED_CONTINUITY_AUTHORITY,creatorFacing:false,restrictions:["current-creator-truth-only","cannot-create-canon","derived-continuity-is-not-creator-confirmed","cannot-overwrite-creator-truth","cannot-advance-journey","cannot-speak-directly-to-creator","cannot-resolve-ambiguity-by-invention"]};}
export{MOVIE_MENTOR_CONTINUITY_AGENT_VERSION,CONTINUITY_CONTRACT_VERSION,CONTINUITY_AGENT_ID,CONTINUITY_AUTHORITY,CONTINUITY_CATEGORIES,CONTINUITY_OUTPUT_SCHEMA,validateContinuityWorkOrder,createContinuityWorkOrder,validateAndBuildContribution,executeMovieMentorContinuityAgent,getContinuityAgentManifest};
export default executeMovieMentorContinuityAgent;
