import {createMovieMentorCommercialPaymentEvidenceAuthority} from "./MovieMentorCommercialPaymentEvidenceAuthority.js";
import {createMovieMentorCommercialProviderIngressRegistry} from "./MovieMentorCommercialProviderIngressRegistry.js";

const VERSION="2.1.0";
const DOMAIN="iband.movie-mentor.commercial-provider-ingress-authority";
const REGISTRY_DOMAIN="iband.movie-mentor.commercial-provider-ingress-registry";
const ADAPTER_DOMAIN="iband.movie-mentor.commercial-provider-adapter";
const PURCHASE_INTENT_DOMAIN="iband.movie-mentor.production-commercial-purchase-intent-authority";
const CHECKOUT_DOMAIN="iband.movie-mentor.production-commercial-checkout-authority";
const ISSUANCE_DOMAIN="iband.movie-mentor.production-entitlement-issuance-authority";
const REVERSAL_DOMAIN="iband.movie-mentor.production-commercial-reversal-authority";
function text(value){return typeof value==="string"?value.trim():"";}
function fail(code,message){const error=new Error(message);error.code=code;throw error;}
function ownedStatus(authority){if(typeof authority?.getStatus!=="function")return null;try{const status=authority.getStatus();return status&&typeof status==="object"?status:null;}catch{return null;}}
function purchaseIntentProven(status){return status?.domain===PURCHASE_INTENT_DOMAIN&&status?.production===true&&status?.durablePurchaseIntent===true&&status?.immutableCommercialTerms===true&&status?.serverOwnedPolicy===true&&status?.processLocalFallback===false;}
function checkoutProven(status){return status?.domain===CHECKOUT_DOMAIN&&status?.production===true&&status?.durableCheckoutBinding===true&&status?.checkoutBindingResolution===true&&status?.providerPaymentReferenceBinding===true&&status?.providerPaymentReferenceResolution===true&&status?.openCheckoutRevocation===true&&status?.serverOwnedIdempotency===true&&status?.purchaseIntentProvenanceRequired===true&&status?.explicitProviderRequired===true&&status?.processLocalFallback===false;}
function issuanceProven(status){return status?.domain===ISSUANCE_DOMAIN&&status?.production===true&&status?.durableAtomicIssuance===true&&status?.evidenceIdentityUnique===true&&status?.issuanceReceiptDurable===true&&status?.processLocalFallback===false;}
function reversalProven(status){return status?.domain===REVERSAL_DOMAIN&&status?.production===true&&status?.durableAtomicSuspension===true&&status?.reversalIdentityUnique===true&&status?.currentEntitlementSuspension===true&&status?.reversalReceiptDurable===true&&status?.pendingReversalHistoryDurable===true&&status?.pendingReversalIdentityUnique===true&&status?.pendingReversalReconciliation===true&&status?.processLocalFallback===false;}
function adapterProven(provider,status){return status?.domain===ADAPTER_DOMAIN&&text(status?.provider)===provider&&status?.productionCommercialProviderAdapter===true&&status?.rawBodyDeliveryVerification===true&&status?.signatureVerification===true&&status?.normalizesCommercialEvidence===true&&status?.checkoutReferenceEvidence===true&&status?.creatorPayloadIsNotPaymentAuthority===true&&status?.processLocalFallback===false;}
function registryProven(status){if(status?.domain!==REGISTRY_DOMAIN||status?.providerAdapterProvenanceRequired!==true||status?.rawBodyDeliveryVerificationRequired!==true||status?.signatureVerificationRequired!==true||status?.evidenceNormalizationRequired!==true||status?.creatorPayloadIsNotPaymentAuthority!==true||status?.processLocalFallback!==false)return false;const providers=Array.isArray(status?.configuredProviders)?status.configuredProviders:[],providerStatuses=status?.providerStatuses&&typeof status.providerStatuses==="object"?status.providerStatuses:null;return providers.length>0&&providerStatuses!==null&&providers.every(provider=>adapterProven(provider,providerStatuses[provider]));}
function createMovieMentorCommercialProviderIngressAuthority({providers={},purchaseIntentAuthority,checkoutBindingAuthority,issuanceAuthority,reversalAuthority}={}){
 const purchaseIntentStatus=ownedStatus(purchaseIntentAuthority),checkoutBindingStatus=ownedStatus(checkoutBindingAuthority),issuanceStatus=ownedStatus(issuanceAuthority),reversalStatus=ownedStatus(reversalAuthority);
 if(typeof purchaseIntentAuthority?.resolvePurchaseIntent!=="function"||!purchaseIntentProven(purchaseIntentStatus))fail("MOVIE_MENTOR_COMMERCIAL_PROVIDER_INGRESS_PURCHASE_INTENT_REQUIRED","Verified commercial ingress requires production-proven durable purchase-intent authority.");
 if(typeof checkoutBindingAuthority?.resolveCheckoutBinding!=="function"||typeof checkoutBindingAuthority?.bindProviderPaymentReference!=="function"||typeof checkoutBindingAuthority?.resolveCheckoutBindingByProviderPaymentReference!=="function"||typeof checkoutBindingAuthority?.revokeOpenCheckoutsForPrincipal!=="function"||!checkoutProven(checkoutBindingStatus))fail("MOVIE_MENTOR_COMMERCIAL_PROVIDER_INGRESS_CHECKOUT_BINDING_REQUIRED","Verified commercial ingress requires production-proven durable checkout, provider-payment lineage and open-checkout revocation authority.");
 if(typeof issuanceAuthority?.issueVerifiedEvidence!=="function"||!issuanceProven(issuanceStatus))fail("MOVIE_MENTOR_COMMERCIAL_PROVIDER_INGRESS_ISSUANCE_REQUIRED","Verified commercial ingress requires production-proven durable entitlement issuance authority.");
 if(typeof reversalAuthority?.suspendVerifiedReversal!=="function"||typeof reversalAuthority?.preserveVerifiedReversalHistory!=="function"||typeof reversalAuthority?.reconcilePendingReversals!=="function"||!reversalProven(reversalStatus))fail("MOVIE_MENTOR_COMMERCIAL_PROVIDER_INGRESS_REVERSAL_REQUIRED","Verified commercial ingress requires production-proven durable reversal suspension and pending-history reconciliation authority.");
 const registry=createMovieMentorCommercialProviderIngressRegistry({providers});if(registry.configuredProviders.length===0)fail("MOVIE_MENTOR_COMMERCIAL_PROVIDER_INGRESS_NOT_CONFIGURED","Verified commercial ingress requires at least one explicit provider adapter.");const providerRegistryStatus=ownedStatus(registry);if(!registryProven(providerRegistryStatus))fail("MOVIE_MENTOR_COMMERCIAL_PROVIDER_INGRESS_REGISTRY_CAPABILITY_NOT_PROVEN","Verified commercial ingress requires registry-owned provider-adapter provenance.");
 async function resolvePaymentLineageIntent({provider,paymentReference,bindingCode,intentCode}){const binding=await checkoutBindingAuthority.resolveCheckoutBindingByProviderPaymentReference({provider,providerPaymentReference:paymentReference});if(!binding||text(binding.provider)!==provider||text(binding.providerPaymentReference)!==paymentReference||text(binding.status)!=="completed"||!text(binding.commercialIntentId))fail(bindingCode,"Provider payment lineage could not be durably reread as exact completed checkout authority.");const intent=await purchaseIntentAuthority.resolvePurchaseIntent({commercialIntentId:text(binding.commercialIntentId)});if(!intent||text(intent.commercialIntentId)!==text(binding.commercialIntentId)||!text(intent.principalId)||text(intent.provider)!==provider)fail(intentCode,"Provider payment lineage could not re-earn exact durable commercial intent authority.");return Object.freeze({binding,intent});}
 async function processProviderDelivery({provider,delivery=null}={}){const selectedProvider=text(provider),adapter=registry.resolveProvider({provider:selectedProvider}),verified=await adapter.verifyDelivery({delivery});if(verified?.verified!==true)fail("MOVIE_MENTOR_COMMERCIAL_EVIDENCE_DELIVERY_UNVERIFIED","Provider delivery authenticity could not be verified.");const normalized=await adapter.normalizeEvent({verifiedDelivery:verified});if(text(normalized?.provider)!==selectedProvider)fail("MOVIE_MENTOR_COMMERCIAL_PROVIDER_INGRESS_PROVIDER_MISMATCH","Verified provider delivery normalized to a different commercial provider.");
  if(normalized?.commercialReversal===true){const paymentReference=text(normalized.providerPaymentReference),evidenceId=text(normalized.eventId),evidenceKind=text(normalized.eventKind);if(!paymentReference||!evidenceId||!evidenceKind)fail("MOVIE_MENTOR_COMMERCIAL_REVERSAL_EVIDENCE_INVALID","Provider reversal lacks durable payment identity or evidence coordinates.");const providerHistory=Object.freeze({verified:true,evidenceId,evidenceSource:selectedProvider,evidenceKind,providerPaymentReference:paymentReference,reversalAmountMinor:Number.isSafeInteger(normalized.reversalAmountMinor)?normalized.reversalAmountMinor:null,currency:text(normalized.currency).toUpperCase()||null,verifiedAt:new Date().toISOString()});const binding=await checkoutBindingAuthority.resolveCheckoutBindingByProviderPaymentReference({provider:selectedProvider,providerPaymentReference:paymentReference});if(!binding)return reversalAuthority.preserveVerifiedReversalHistory({reversal:providerHistory});if(text(binding.provider)!==selectedProvider||text(binding.providerPaymentReference)!==paymentReference||text(binding.status)!=="completed"||!text(binding.commercialIntentId))fail("MOVIE_MENTOR_COMMERCIAL_REVERSAL_CHECKOUT_BINDING_NOT_FOUND","Verified reversal resolves to malformed or contradictory Movie Mentor checkout payment lineage.");const intent=await purchaseIntentAuthority.resolvePurchaseIntent({commercialIntentId:text(binding.commercialIntentId)});if(!intent||text(intent.commercialIntentId)!==text(binding.commercialIntentId)||!text(intent.principalId)||text(intent.provider)!==selectedProvider)fail("MOVIE_MENTOR_COMMERCIAL_REVERSAL_INTENT_NOT_FOUND","Verified reversal cannot resolve its durable commercial intent.");try{const result=await reversalAuthority.suspendVerifiedReversal({reversal:Object.freeze({...providerHistory,commercialReference:text(binding.commercialIntentId),principalId:text(intent.principalId)})});if(result?.suspended===true)await checkoutBindingAuthority.revokeOpenCheckoutsForPrincipal({principalId:text(intent.principalId)});return result;}catch(error){if(error?.code!=="MOVIE_MENTOR_COMMERCIAL_REVERSAL_ENTITLEMENT_NOT_FOUND")throw error;return reversalAuthority.preserveVerifiedReversalHistory({reversal:providerHistory});}}
  const evidenceAuthority=createMovieMentorCommercialPaymentEvidenceAuthority({verifyDelivery:async()=>verified,normalizeEvent:async()=>normalized,resolvePurchaseIntent:purchaseIntentAuthority.resolvePurchaseIntent,resolveCheckoutBinding:checkoutBindingAuthority.resolveCheckoutBinding});const evidence=await evidenceAuthority.verifyCommercialDelivery({delivery});if(evidence?.verified!==true)fail("MOVIE_MENTOR_COMMERCIAL_EVIDENCE_UNVERIFIED","Only verified commercial evidence may mint payment lineage or reach entitlement issuance.");let paymentReference="";if(normalized?.commerciallyFinal===true){paymentReference=text(normalized.providerPaymentReference);if(Number.isSafeInteger(normalized.amountMinor)&&normalized.amountMinor>0&&!paymentReference)fail("MOVIE_MENTOR_COMMERCIAL_PAYMENT_REFERENCE_REQUIRED","Paid provider evidence must carry durable provider payment identity for reversal authority.");if(paymentReference)await checkoutBindingAuthority.bindProviderPaymentReference({commercialIntentId:text(normalized.commercialIntentId),provider:selectedProvider,checkoutReference:text(normalized.checkoutReference),providerPaymentReference:paymentReference});}
  let result;try{result=await issuanceAuthority.issueVerifiedEvidence({evidence});}catch(error){if(error?.code!=="MOVIE_MENTOR_ENTITLEMENT_ISSUANCE_IDEMPOTENT_STATUS_FENCED"||!paymentReference)throw error;const {binding,intent}=await resolvePaymentLineageIntent({provider:selectedProvider,paymentReference,bindingCode:"MOVIE_MENTOR_COMMERCIAL_ISSUANCE_FENCE_RECOVERY_BINDING_INVALID",intentCode:"MOVIE_MENTOR_COMMERCIAL_ISSUANCE_FENCE_RECOVERY_INTENT_INVALID"});if(text(binding.commercialIntentId)!==text(normalized.commercialIntentId))fail("MOVIE_MENTOR_COMMERCIAL_ISSUANCE_FENCE_RECOVERY_BINDING_INVALID","Fenced historical issuance retry does not bind the same commercially-verified intent.");const principal=text(intent.principalId);await checkoutBindingAuthority.revokeOpenCheckoutsForPrincipal({principalId:principal});return Object.freeze({authorized:false,status:"historical-issuance-current-authority-fenced",principalId:principal,commercialIntentId:text(binding.commercialIntentId),providerPaymentReference:paymentReference,issuanceId:text(error.issuanceId)||null,idempotent:true,checkoutRevocationRecovered:true});}
  if(paymentReference){const {binding,intent}=await resolvePaymentLineageIntent({provider:selectedProvider,paymentReference,bindingCode:"MOVIE_MENTOR_COMMERCIAL_REVERSAL_RECONCILIATION_BINDING_INVALID",intentCode:"MOVIE_MENTOR_COMMERCIAL_REVERSAL_RECONCILIATION_INTENT_INVALID"});const reconciliation=await reversalAuthority.reconcilePendingReversals({evidenceSource:selectedProvider,providerPaymentReference:paymentReference,commercialReference:text(binding.commercialIntentId),principalId:text(intent.principalId)});if(reconciliation?.reconciled!==true||!Number.isSafeInteger(reconciliation.count)||reconciliation.count<0)fail("MOVIE_MENTOR_COMMERCIAL_REVERSAL_RECONCILIATION_RESULT_INVALID","Pending reversal reconciliation returned malformed durable authority evidence.");if(reconciliation.count>0){const principal=text(intent.principalId),results=Array.isArray(reconciliation.results)?reconciliation.results:[];if(text(reconciliation.principalId)!==principal||results.length!==reconciliation.count||results.some(item=>item?.suspended!==true||text(item.principalId)!==principal))fail("MOVIE_MENTOR_COMMERCIAL_REVERSAL_RECONCILIATION_RESULT_INVALID","Pending reversal reconciliation did not prove exact current entitlement suspension for the durable principal.");await checkoutBindingAuthority.revokeOpenCheckoutsForPrincipal({principalId:principal});if(typeof reversalAuthority.acknowledgePendingReversals==="function")await reversalAuthority.acknowledgePendingReversals({evidenceSource:selectedProvider,results});}}
  return result;}
 const status=Object.freeze({version:VERSION,domain:DOMAIN,providerNeutral:true,providerRegistryStatus,providerRegistryProvenanceRequired:true,purchaseIntentStatus,checkoutBindingStatus,issuanceStatus,reversalStatus,purchaseIntentProvenanceRequired:true,checkoutBindingProvenanceRequired:true,providerPaymentLineageRequired:true,openCheckoutRevocationRequired:true,pendingReversalReconciliationCheckoutRevocation:true,pendingReversalAcknowledgementAfterCheckoutRevocation:true,reconciledRevocationRetryRecovery:true,commercialVerificationBeforePaymentLineage:true,issuanceProvenanceRequired:true,reversalProvenanceRequired:true,pendingReversalHistoryRequired:true,pendingReversalReconciliationRequired:true,reversalDuringIssuancePreserved:true,processLocalFallback:false});return Object.freeze({processProviderDelivery,ingest:processProviderDelivery,configuredProviders:registry.configuredProviders,getStatus:()=>status});
}
export{VERSION as MOVIE_MENTOR_COMMERCIAL_PROVIDER_INGRESS_AUTHORITY_VERSION,DOMAIN as MOVIE_MENTOR_COMMERCIAL_PROVIDER_INGRESS_AUTHORITY_DOMAIN,createMovieMentorCommercialProviderIngressAuthority};export default createMovieMentorCommercialProviderIngressAuthority;
