import mongoose from "mongoose";
const VERSION="1.0.0";
const COLLECTION_NAME="movie_mentor_journey_recovery";
let connectionPromise=null;
let model=null;
function s(v){return typeof v==="string"?v.trim():"";}
function n(v){return Number.isSafeInteger(v)&&v>=0?v:null;}
function clone(v){if(v===undefined)return undefined;try{return JSON.parse(JSON.stringify(v));}catch{return v;}}
function mongoUri(){return s(process.env.MONGO_URI||process.env.MONGODB_URI||"");}
function err(code,message,{retryable=false}={}){const e=new Error(message);e.code=code;e.retryable=retryable;return e;}
function getModel(){if(model)return model;const schema=new mongoose.Schema({projectId:{type:String,trim:true,required:true,index:true},lineageId:{type:String,trim:true,required:true},recoveryRevision:{type:Number,min:1,required:true},recoveryGeneration:{type:Number,min:1,required:true},recoveryReference:{type:String,trim:true,required:true},recoveryFingerprint:{type:String,trim:true,required:true},authorityGeneration:{type:Number,min:0,required:true},progressionRevision:{type:Number,min:0,required:true},envelopeFingerprint:{type:String,trim:true,required:true},envelope:{type:mongoose.Schema.Types.Mixed,required:true},capturedAt:{type:Date,required:true}},{collection:COLLECTION_NAME,timestamps:true,minimize:false,strict:true});schema.index({projectId:1},{unique:true});model=mongoose.models.MovieMentorJourneyRecovery||mongoose.model("MovieMentorJourneyRecovery",schema);return model;}
async function ensureConnection(){const uri=mongoUri();if(!uri)throw err("MOVIE_MENTOR_JOURNEY_RECOVERY_STORE_NOT_CONFIGURED","Journey recovery store requires MONGO_URI or MONGODB_URI.");if(mongoose.connection.readyState===1)return mongoose.connection;if(!connectionPromise){connectionPromise=mongoose.connect(uri,{serverSelectionTimeoutMS:5000,maxPoolSize:10}).catch(error=>{connectionPromise=null;throw err("MOVIE_MENTOR_JOURNEY_RECOVERY_STORE_UNAVAILABLE",`Journey recovery store unavailable: ${error instanceof Error?error.message:"Mongo connection failed."}`,{retryable:true});});}await connectionPromise;return mongoose.connection;}
function normalize(doc){if(!doc)return null;const recoveryRevision=n(doc.recoveryRevision),recoveryGeneration=n(doc.recoveryGeneration),authorityGeneration=n(doc.authorityGeneration),progressionRevision=n(doc.progressionRevision);if(!s(doc.projectId)||!s(doc.lineageId)||recoveryRevision===null||recoveryGeneration===null||!s(doc.recoveryReference)||!s(doc.recoveryFingerprint)||authorityGeneration===null||progressionRevision===null||!s(doc.envelopeFingerprint)||!doc.envelope||!doc.capturedAt)throw err("MOVIE_MENTOR_JOURNEY_RECOVERY_STORE_RECORD_INVALID","Journey recovery record is malformed.");return{projectId:s(doc.projectId),lineageId:s(doc.lineageId),recoveryRevision,recoveryGeneration,recoveryReference:s(doc.recoveryReference),recoveryFingerprint:s(doc.recoveryFingerprint),authorityGeneration,progressionRevision,envelopeFingerprint:s(doc.envelopeFingerprint),envelope:clone(doc.envelope),capturedAt:new Date(doc.capturedAt).toISOString(),updatedAt:doc.updatedAt?new Date(doc.updatedAt).toISOString():null};}
async function readMovieMentorJourneyRecovery({projectId}={}){await ensureConnection();const pid=s(projectId);if(!pid)throw err("MOVIE_MENTOR_JOURNEY_RECOVERY_PROJECT_REQUIRED","Journey recovery read requires projectId.");const doc=await getModel().findOne({projectId:pid}).lean().exec();if(!doc)throw err("MOVIE_MENTOR_JOURNEY_RECOVERY_NOT_FOUND","No Journey recovery checkpoint exists for this project.");return normalize(doc);}
async function writeMovieMentorJourneyRecovery(state={},options={}){await ensureConnection();const expected=n(options.expectedRecoveryRevision),pid=s(state.projectId);if(expected===null||!pid)throw err("MOVIE_MENTOR_JOURNEY_RECOVERY_EXPECTED_REVISION_REQUIRED","Journey recovery write requires projectId and exact expected recovery revision.");const doc={projectId:pid,lineageId:s(state.lineageId),recoveryRevision:n(state.recoveryRevision),recoveryGeneration:n(state.recoveryGeneration),recoveryReference:s(state.recoveryReference),recoveryFingerprint:s(state.recoveryFingerprint),authorityGeneration:n(state.authorityGeneration),progressionRevision:n(state.progressionRevision),envelopeFingerprint:s(state.envelopeFingerprint),envelope:clone(state.envelope),capturedAt:new Date(state.capturedAt)};if(!doc.lineageId||doc.recoveryRevision===null||doc.recoveryGeneration===null||!doc.recoveryReference||!doc.recoveryFingerprint||doc.authorityGeneration===null||doc.progressionRevision===null||!doc.envelopeFingerprint||!doc.envelope||Number.isNaN(doc.capturedAt.getTime()))throw err("MOVIE_MENTOR_JOURNEY_RECOVERY_STORE_RECORD_INVALID","Journey recovery write is missing required server fields.");let result;if(expected===0){try{result=await getModel().create(doc);}catch(error){if(error?.code===11000)throw err("MOVIE_MENTOR_JOURNEY_RECOVERY_REVISION_CONFLICT","Journey recovery checkpoint already exists; refresh before writing.");throw error;}}else{result=await getModel().findOneAndUpdate({projectId:pid,recoveryRevision:expected},{$set:doc},{new:true,runValidators:true}).lean().exec();if(!result)throw err("MOVIE_MENTOR_JOURNEY_RECOVERY_REVISION_CONFLICT","Journey recovery checkpoint changed before this write.");}return normalize(result.toObject?result.toObject():result);}
function getMovieMentorJourneyRecoveryStoreStatus(){const configured=Boolean(mongoUri());return{version:VERSION,configured,readiness:configured?"configured":"configuration-required",collection:COLLECTION_NAME,authority:"recovery-evidence-only",atomicWrites:true,cas:"recoveryRevision"};}
export{VERSION as MOVIE_MENTOR_JOURNEY_RECOVERY_STORE_VERSION,COLLECTION_NAME,getMovieMentorJourneyRecoveryStoreStatus,readMovieMentorJourneyRecovery,writeMovieMentorJourneyRecovery};
export default readMovieMentorJourneyRecovery;
