import { createMovieMentorInferenceExecutionMongoStore, getMovieMentorInferenceExecutionMongoStoreStatus } from "./MovieMentorInferenceExecutionMongoStore.js";
import { createMovieMentorInferenceExecutionLeaseAuthority } from "./MovieMentorInferenceExecutionLeaseAuthority.js";
import { createMovieMentorProviderEffectMongoStore, getMovieMentorProviderEffectMongoStoreStatus } from "./MovieMentorProviderEffectMongoStore.js";
import { createMovieMentorProviderEffectAuthority } from "./MovieMentorProviderEffectAuthority.js";
import { createMovieMentorInferenceExecutionClosureAuthority } from "./MovieMentorInferenceExecutionClosureAuthority.js";

const VERSION="1.2.0";
function createMovieMentorProductionInferenceExecutionComposition({store=null,effectStore=null}={}){const status=store?{configured:true,readiness:"injected"}:getMovieMentorInferenceExecutionMongoStoreStatus();if(status.configured!==true)return Object.freeze({ready:false,reason:"inference-execution-store-not-configured",version:VERSION,authority:null,storeStatus:status});try{const durableStore=store||createMovieMentorInferenceExecutionMongoStore(),leaseAuthority=createMovieMentorInferenceExecutionLeaseAuthority({store:durableStore}),effectStatus=effectStore?{configured:true,readiness:"injected"}:getMovieMentorProviderEffectMongoStoreStatus();if(effectStatus.configured!==true&&!store)return Object.freeze({ready:false,reason:"provider-effect-store-not-configured",version:VERSION,authority:null,storeStatus:status,effectStoreStatus:effectStatus});if(effectStatus.configured!==true)return Object.freeze({ready:true,reason:"durable-inference-execution-authority-composed-without-injected-effect-store",version:VERSION,authority:leaseAuthority,storeStatus:status,effectStoreStatus:effectStatus});const durableEffectStore=effectStore||createMovieMentorProviderEffectMongoStore(),providerEffectAuthority=createMovieMentorProviderEffectAuthority({store:durableEffectStore}),closureAuthority=createMovieMentorInferenceExecutionClosureAuthority({store:durableStore,effectStore:durableEffectStore});const authority=Object.freeze({...leaseAuthority,beginProviderDispatch:providerEffectAuthority.beginDispatch,contributeProviderEffectEvidence:providerEffectAuthority.contributeEvidence,readProviderEffectReality:providerEffectAuthority.readReality,beginExecutionClosing:closureAuthority.beginClosing,recoverExpiredExecutionIntoClosing:closureAuthority.recoverExpiredIntoClosing,reconcileExecutionClosure:closureAuthority.reconcile});return Object.freeze({ready:true,reason:"durable-inference-execution-provider-effect-and-closure-authority-composed",version:VERSION,authority,storeStatus:status,effectStoreStatus:effectStatus});}catch(error){return Object.freeze({ready:false,reason:error?.code||"inference-execution-composition-failed",version:VERSION,authority:null,storeStatus:status});}}
export{VERSION as MOVIE_MENTOR_PRODUCTION_INFERENCE_EXECUTION_COMPOSITION_VERSION,createMovieMentorProductionInferenceExecutionComposition};export default createMovieMentorProductionInferenceExecutionComposition;
