import { createHash } from "node:crypto";
import { assertCurrentCreatorTruthOnly } from "./MovieMentorCreatorTruthViewControl.js";
import { validateDerivedContinuityConstraint } from "./MovieMentorContinuityConsequenceAuthority.js";

const MOVIE_MENTOR_CONTINUITY_DERIVED_CACHE_VERSION="1.0.0";
const CONTINUITY_CACHE_DOMAIN="iband.movie-mentor.continuity-derived-cache";
const CONTINUITY_CACHE_SCHEMA=1;
const CONTINUITY_CACHE_AUTHORITY="derived-continuity-cache";
function s(v){return typeof v==="string"?v.trim():"";}
function n(v){return Number.isSafeInteger(v)&&v>=0?v:null;}
function a(v){return Array.isArray(v)?v:[];}
function clone(v){if(v===undefined)return undefined;try{return JSON.parse(JSON.stringify(v));}catch{return v;}}
function stable(v){if(Array.isArray(v))return v.map(stable);if(v&&typeof v==="object")return Object.keys(v).sort().reduce((o,k)=>(o[k]=stable(v[k]),o),{});return v;}
function digest(v){return createHash("sha256").update(JSON.stringify(stable(v))).digest("hex");}
function fail(code,message,issues=[]){const e=new Error(message);e.code=code;e.validationIssues=issues;return e;}
function authoritySnapshot(source={}){const projectId=s(source.projectId);const revision=n(source.revision),generation=n(source.creatorStateGeneration);const fingerprint=s(source.creatorStateFingerprint),snapshotReference=s(source.snapshotReference);if(!projectId)throw fail("CONTINUITY_CACHE_PROJECT_REQUIRED","Derived continuity cache requires canonical project identity.");if(revision===null||generation===null||!fingerprint||!snapshotReference)throw fail("CONTINUITY_CACHE_CREATOR_AUTHORITY_REQUIRED","Derived continuity cache requires the authoritative creator-state revision, generation, fingerprint and snapshot reference.");return{projectId,revision,creatorStateGeneration:generation,creatorStateFingerprint:fingerprint,snapshotReference};}
function buildDependencyDigest(constraints=[]){return digest(a(constraints).map(c=>({constraintId:s(c?.constraintId),constraintDigest:s(c?.constraintDigest),dependencies:a(c?.dependencies).map(d=>({key:s(d?.key),value:clone(d?.value),decisionId:s(d?.decisionId)||null,decisionKey:s(d?.decisionKey)||null,decisionFingerprint:s(d?.decisionFingerprint)||null}))})));}
function createContinuityDerivedCacheRecord({sourceState={},creatorConfirmedContext=[],constraints=[]}={}){assertCurrentCreatorTruthOnly(creatorConfirmedContext);const source=authoritySnapshot(sourceState);const validated=[];for(const constraint of a(constraints)){const result=validateDerivedContinuityConstraint(constraint,creatorConfirmedContext);if(!result.valid)throw fail("CONTINUITY_CACHE_CONSTRAINT_INVALID","Only currently valid derived continuity constraints may enter the cache.",result.issues);validated.push(clone(constraint));}const dependencyDigest=buildDependencyDigest(validated);const body={domain:CONTINUITY_CACHE_DOMAIN,schema:CONTINUITY_CACHE_SCHEMA,version:MOVIE_MENTOR_CONTINUITY_DERIVED_CACHE_VERSION,authority:CONTINUITY_CACHE_AUTHORITY,projectId:source.projectId,sourceRevision:source.revision,sourceCreatorStateGeneration:source.creatorStateGeneration,sourceCreatorStateFingerprint:source.creatorStateFingerprint,sourceSnapshotReference:source.snapshotReference,dependencyDigest,constraints:validated,creatorConfirmed:false,mayCreateCanon:false};return{...body,cacheKey:`${source.projectId}:${source.creatorStateFingerprint}`,cacheFingerprint:digest(body),createdAt:new Date().toISOString()};}
function validateContinuityDerivedCacheRecord(record={},currentState={},currentCreatorTruth=[]){const reasons=[];let source=null;try{source=authoritySnapshot(currentState);assertCurrentCreatorTruthOnly(currentCreatorTruth);}catch(error){return{valid:false,stale:true,reasons:[error?.code||"continuity_cache_current_authority_invalid"]};}if(record?.domain!==CONTINUITY_CACHE_DOMAIN)reasons.push("continuity_cache_domain_mismatch");if(record?.schema!==CONTINUITY_CACHE_SCHEMA)reasons.push("continuity_cache_schema_mismatch");if(record?.authority!==CONTINUITY_CACHE_AUTHORITY)reasons.push("continuity_cache_authority_mismatch");if(record?.creatorConfirmed!==false||record?.mayCreateCanon!==false)reasons.push("continuity_cache_canon_promotion_forbidden");if(s(record?.projectId)!==source.projectId)reasons.push("continuity_cache_project_mismatch");if(n(record?.sourceRevision)!==source.revision)reasons.push("continuity_cache_source_revision_stale");if(n(record?.sourceCreatorStateGeneration)!==source.creatorStateGeneration)reasons.push("continuity_cache_source_generation_stale");if(s(record?.sourceCreatorStateFingerprint)!==source.creatorStateFingerprint)reasons.push("continuity_cache_source_fingerprint_stale");if(s(record?.sourceSnapshotReference)!==source.snapshotReference)reasons.push("continuity_cache_snapshot_stale");for(const constraint of a(record?.constraints)){const result=validateDerivedContinuityConstraint(constraint,currentCreatorTruth);if(!result.valid)reasons.push(...result.issues.map(issue=>`continuity_cache_${issue}`));}const dependencyDigest=buildDependencyDigest(record?.constraints);if(s(record?.dependencyDigest)!==dependencyDigest)reasons.push("continuity_cache_dependency_digest_mismatch");const body={domain:record?.domain,schema:record?.schema,version:record?.version,authority:record?.authority,projectId:record?.projectId,sourceRevision:record?.sourceRevision,sourceCreatorStateGeneration:record?.sourceCreatorStateGeneration,sourceCreatorStateFingerprint:record?.sourceCreatorStateFingerprint,sourceSnapshotReference:record?.sourceSnapshotReference,dependencyDigest:record?.dependencyDigest,constraints:clone(a(record?.constraints)),creatorConfirmed:record?.creatorConfirmed,mayCreateCanon:record?.mayCreateCanon};if(s(record?.cacheFingerprint)!==digest(body))reasons.push("continuity_cache_fingerprint_mismatch");if(s(record?.cacheKey)!==`${source.projectId}:${source.creatorStateFingerprint}`)reasons.push("continuity_cache_key_mismatch");return{valid:reasons.length===0,stale:reasons.length>0,reasons,constraints:reasons.length?[]:clone(a(record?.constraints))};}
function selectReusableContinuityConstraints(record,currentState,currentCreatorTruth){const result=validateContinuityDerivedCacheRecord(record,currentState,currentCreatorTruth);return result.valid?result.constraints:[];}
export{MOVIE_MENTOR_CONTINUITY_DERIVED_CACHE_VERSION,CONTINUITY_CACHE_DOMAIN,CONTINUITY_CACHE_SCHEMA,CONTINUITY_CACHE_AUTHORITY,buildDependencyDigest,createContinuityDerivedCacheRecord,validateContinuityDerivedCacheRecord,selectReusableContinuityConstraints};
export default validateContinuityDerivedCacheRecord;
