const VERSION="1.6.0";
const ADAPTER_DOMAIN="iband.movie-mentor.commercial-provider-adapter";
function text(v){return typeof v==="string"?v.trim():"";}
function fail(code,message){const e=new Error(message);e.code=code;throw e;}
function ownedStatus(adapter){if(typeof adapter?.getStatus!=="function")return null;try{const status=adapter.getStatus();return status&&typeof status==="object"?status:null;}catch{return null;}}
function checkoutCapabilityProven(name,status){return status?.domain===ADAPTER_DOMAIN&&text(status?.provider)===name&&status?.productionCommercialProviderAdapter===true&&status?.checkoutTransport===true&&status?.checkoutRevocation===true&&status?.checkoutRevocationRecovery===true&&status?.currentCheckoutReality===true&&status?.serverOwnedIdempotencyRequired===true&&status?.creatorPayloadIsNotPaymentAuthority===true&&status?.processLocalFallback===false;}
function createMovieMentorCommercialCheckoutProviderRegistry({providers={}}={}){const entries=new Map();for(const [name,adapter] of Object.entries(providers||{})){const key=text(name),status=ownedStatus(adapter);if(!key||!adapter||typeof adapter.createCheckout!=="function"||typeof adapter.resolveCheckout!=="function"||typeof adapter.revokeCheckout!=="function"||!checkoutCapabilityProven(key,status))fail("MOVIE_MENTOR_CHECKOUT_PROVIDER_INVALID","Every configured checkout provider must own production checkout transport, server idempotency, current checkout reality, explicit checkout revocation and uncertain-revocation recovery capability.");entries.set(key,Object.freeze({createCheckout:adapter.createCheckout,resolveCheckout:adapter.resolveCheckout,revokeCheckout:adapter.revokeCheckout,status}));}
 async function createProviderCheckout({intent,idempotencyKey}={}){const provider=text(intent?.provider),entry=entries.get(provider),key=text(idempotencyKey);if(!provider||!entry)fail("MOVIE_MENTOR_CHECKOUT_PROVIDER_NOT_CONFIGURED","Purchase intent names a checkout provider that is not explicitly configured.");if(!key)fail("MOVIE_MENTOR_CHECKOUT_IDEMPOTENCY_AUTHORITY_REQUIRED","Provider checkout requires a server-owned durable idempotency key.");return entry.createCheckout({intent:Object.freeze({...intent}),idempotencyKey:key});}
 async function resolveProviderCheckout({provider,checkoutReference}={}){const key=text(provider),entry=entries.get(key),ref=text(checkoutReference);if(!key||!entry||!ref)fail("MOVIE_MENTOR_CHECKOUT_PROVIDER_REALITY_INVALID","Checkout reality requires an explicitly configured provider and exact checkout reference.");const result=await entry.resolveCheckout({checkoutReference:ref});if(text(result?.provider)!==key||text(result?.checkoutReference)!==ref||!text(result?.status))fail("MOVIE_MENTOR_CHECKOUT_PROVIDER_REALITY_UNCERTAIN","Provider did not certify exact current checkout reality.");return result;}
 async function revokeProviderCheckout({provider,checkoutReference}={}){const key=text(provider),entry=entries.get(key),ref=text(checkoutReference);if(!key||!entry||!ref)fail("MOVIE_MENTOR_CHECKOUT_REVOCATION_INVALID","Checkout revocation requires an explicitly configured provider and exact checkout reference.");const result=await entry.revokeCheckout({checkoutReference:ref});if(result?.revoked!==true||text(result.provider)!==key||text(result.checkoutReference)!==ref)fail("MOVIE_MENTOR_CHECKOUT_REVOCATION_UNCERTAIN","Provider did not certify exact checkout revocation.");return result;}
 return Object.freeze({createProviderCheckout,resolveProviderCheckout,revokeProviderCheckout,configuredProviders:Object.freeze([...entries.keys()]),providerStatuses:Object.freeze(Object.fromEntries([...entries].map(([name,entry])=>[name,entry.status])))});}
export{VERSION as MOVIE_MENTOR_COMMERCIAL_CHECKOUT_PROVIDER_REGISTRY_VERSION,createMovieMentorCommercialCheckoutProviderRegistry};export default createMovieMentorCommercialCheckoutProviderRegistry;
