import mongoose from "mongoose";

const VERSION="1.0.0",DOMAIN="iband.movie-mentor.commercial-purchase-intent",SCHEMA=1,COLLECTION="movie_mentor_commercial_purchase_intent";
let connectionPromise=null,model=null;
function text(v){return typeof v==="string"?v.trim():"";}
function fail(code,message,extras={}){const e=new Error(message);e.code=code;Object.assign(e,extras);throw e;}
function uri(){return text(process.env.MONGO_URI||process.env.MONGODB_URI||"");}
function plain(v){return v&&typeof v.toObject==="function"?v.toObject():v;}
function getModel(){if(model)return model;const schema=new mongoose.Schema({domain:{type:String,required:true,immutable:true},schema:{type:Number,required:true,immutable:true},commercialIntentId:{type:String,required:true,trim:true,immutable:true},principalId:{type:String,required:true,trim:true,immutable:true},packageId:{type:String,required:true,trim:true,immutable:true},provider:{type:String,required:true,trim:true,immutable:true},providerProductId:{type:String,required:true,trim:true,immutable:true},amountMinor:{type:Number,min:0,required:true,immutable:true},currency:{type:String,required:true,trim:true,immutable:true},environment:{type:String,required:true,trim:true,immutable:true},units:{type:Number,min:1,required:true,immutable:true},policyVersion:{type:String,required:true,trim:true,immutable:true},policyDigest:{type:String,required:true,trim:true,immutable:true},status:{type:String,enum:["created"],required:true,immutable:true},createdAtAuthority:{type:Date,required:true,immutable:true}},{collection:COLLECTION,timestamps:true,minimize:false,strict:true});schema.index({commercialIntentId:1},{unique:true});model=mongoose.models.MovieMentorCommercialPurchaseIntent||mongoose.model("MovieMentorCommercialPurchaseIntent",schema);return model;}
async function connect(){const u=uri();if(!u)fail("MOVIE_MENTOR_PURCHASE_INTENT_STORE_NOT_CONFIGURED","Purchase-intent store requires MONGO_URI or MONGODB_URI.");if(mongoose.connection.readyState===1)return;if(!connectionPromise)connectionPromise=mongoose.connect(u,{serverSelectionTimeoutMS:5000,maxPoolSize:10}).catch(error=>{connectionPromise=null;fail("MOVIE_MENTOR_PURCHASE_INTENT_AUTHORITY_UNAVAILABLE",`Purchase-intent store unavailable: ${error instanceof Error?error.message:"Mongo connection failed."}`,{retryable:true});});await connectionPromise;}
function normalize(v){v=plain(v);if(!v||v.domain!==DOMAIN||v.schema!==SCHEMA||!text(v.commercialIntentId)||!text(v.principalId)||!text(v.packageId)||!text(v.provider)||!text(v.providerProductId)||!Number.isSafeInteger(v.amountMinor)||v.amountMinor<0||!text(v.currency)||!text(v.environment)||!Number.isSafeInteger(v.units)||v.units<=0||!text(v.policyVersion)||!text(v.policyDigest)||text(v.status)!=="created")fail("MOVIE_MENTOR_PURCHASE_INTENT_RECORD_INVALID","Durable purchase intent is malformed.");return Object.freeze({commercialIntentId:text(v.commercialIntentId),principalId:text(v.principalId),packageId:text(v.packageId),provider:text(v.provider),providerProductId:text(v.providerProductId),amountMinor:v.amountMinor,currency:text(v.currency).toUpperCase(),environment:text(v.environment),units:v.units,policyVersion:text(v.policyVersion),policyDigest:text(v.policyDigest),status:"created",createdAt:v.createdAtAuthority?new Date(v.createdAtAuthority).toISOString():null});}
function createMovieMentorCommercialPurchaseIntentMongoStore({modelRef=null,connectStore=connect,now=()=>new Date()}={}){const M=()=>modelRef||getModel();async function ready(){if(!modelRef)await connectStore();}
 async function create(record={}){await ready();try{const created=await M().create([{domain:DOMAIN,schema:SCHEMA,...record,status:"created",createdAtAuthority:now()}]);return normalize(created[0]);}catch(error){if(error?.code===11000)fail("MOVIE_MENTOR_PURCHASE_INTENT_ID_CONFLICT","Purchase-intent identity already exists.",{retryable:true});if(error?.code?.startsWith?.("MOVIE_MENTOR_PURCHASE_INTENT_"))throw error;fail("MOVIE_MENTOR_PURCHASE_INTENT_AUTHORITY_UNAVAILABLE",`Purchase-intent creation failed: ${error instanceof Error?error.message:"write failed"}`,{retryable:true});}}
 async function resolve({commercialIntentId}={}){const id=text(commercialIntentId);if(!id)return null;await ready();const found=await M().findOne({domain:DOMAIN,schema:SCHEMA,commercialIntentId:id}).lean().exec();return found?normalize(found):null;}
 return Object.freeze({create,resolve});}
function getMovieMentorCommercialPurchaseIntentMongoStoreStatus(){const configured=Boolean(uri());return Object.freeze({version:VERSION,configured,readiness:configured?"configured":"configuration-required",collection:COLLECTION,durable:true,processLocalFallback:false});}
export{VERSION as MOVIE_MENTOR_COMMERCIAL_PURCHASE_INTENT_MONGO_STORE_VERSION,COLLECTION as MOVIE_MENTOR_COMMERCIAL_PURCHASE_INTENT_COLLECTION,createMovieMentorCommercialPurchaseIntentMongoStore,getMovieMentorCommercialPurchaseIntentMongoStoreStatus};export default createMovieMentorCommercialPurchaseIntentMongoStore;
