import {createMovieMentorCommercialCheckoutProviderRegistry} from "./MovieMentorCommercialCheckoutProviderRegistry.js";
import {createMovieMentorCommercialCheckoutInitiationAuthority} from "./MovieMentorCommercialCheckoutInitiationAuthority.js";
import {createMovieMentorCommercialCheckoutBindingMongoStore,getMovieMentorCommercialCheckoutBindingMongoStoreStatus} from "./MovieMentorCommercialCheckoutBindingMongoStore.js";
import {isMovieMentorProductionCommercialPurchaseIntentAuthorityOwnedProof} from "./MovieMentorProductionCommercialPurchaseIntentComposition.js";
import {isMovieMentorProductionEntitlementIssuanceAuthorityOwnedProof} from "./MovieMentorProductionEntitlementIssuanceComposition.js";

const VERSION="2.1.0";
const PURCHASE_INTENT_DOMAIN="iband.movie-mentor.production-commercial-purchase-intent-authority";
const ENTITLEMENT_DOMAIN="iband.movie-mentor.production-entitlement-issuance-authority";
const AUTHORITY_DOMAIN="iband.movie-mentor.production-commercial-checkout-authority";
const productionAuthorityProofs=new WeakMap();
function fail(code,message){const e=new Error(message);e.code=code;throw e;}
function ownedStatus(authority){if(typeof authority?.getStatus!=="function")return null;try{const status=authority.getStatus();return status&&typeof status==="object"?status:null;}catch{return null;}}
function purchaseIntentProven(authority,status){return isMovieMentorProductionCommercialPurchaseIntentAuthorityOwnedProof(authority,status)&&status?.domain===PURCHASE_INTENT_DOMAIN&&status?.production===true&&status?.durablePurchaseIntent===true&&status?.immutableCommercialTerms===true&&status?.serverOwnedPolicy===true&&status?.ownerBoundProof===true&&status?.processLocalFallback===false;}
function entitlementProven(authority,status){return isMovieMentorProductionEntitlementIssuanceAuthorityOwnedProof(authority,status)&&status?.domain===ENTITLEMENT_DOMAIN&&status?.production===true&&status?.durableAtomicIssuance===true&&status?.currentEntitlementRead===true&&status?.ownerBoundProof===true&&status?.processLocalFallback===false;}
function checkoutStoreProven(status){return status?.configured===true&&status?.durable===true&&status?.providerPaymentReferenceBinding===true&&status?.providerPaymentReferenceResolution===true&&status?.unpaidCompletedCheckoutDiscovery===true&&status?.uniquenessReadinessRequired===true&&status?.physicalUniqueIndexReadiness===true&&status?.processLocalFallback===false;}
function checkoutStatus(entitlementStatus,storeStatus){return Object.freeze({version:VERSION,domain:AUTHORITY_DOMAIN,production:true,durableCheckoutBinding:true,checkoutBindingResolution:true,currentProviderCheckoutReality:true,providerPaymentReferenceBinding:true,providerPaymentReferenceResolution:true,openCheckoutRevocation:true,postProviderOrphanCheckoutRevocation:true,serverOwnedIdempotency:true,checkoutBindingUniquenessReadinessRequired:true,checkoutBindingPhysicalUniqueIndexReadiness:true,checkoutBindingStoreStatus:storeStatus,purchaseIntentProvenanceRequired:true,purchaseIntentOwnerProofRequired:true,currentEntitlementProvenanceRequired:true,currentEntitlementOwnerProofRequired:true,currentEntitlementStatus:entitlementStatus,explicitProviderRequired:true,ownerBoundProof:true,processLocalFallback:false});}
function getMovieMentorProductionCommercialCheckoutAuthorityOwnedStatus(authority){const expected=productionAuthorityProofs.get(authority)||null;if(!expected)return null;const actual=ownedStatus(authority);return actual===expected?expected:null;}
function isMovieMentorProductionCommercialCheckoutAuthorityOwnedProof(authority,status=null){const expected=getMovieMentorProductionCommercialCheckoutAuthorityOwnedStatus(authority);return expected!==null&&(status===null||status===expected);}
function createMovieMentorProductionCommercialCheckoutComposition({purchaseIntentAuthority,entitlementAuthority,providers={}}={}){
 const purchaseStatus=ownedStatus(purchaseIntentAuthority);
 if(typeof purchaseIntentAuthority?.resolvePurchaseIntent!=="function"||!purchaseIntentProven(purchaseIntentAuthority,purchaseStatus))fail("MOVIE_MENTOR_CHECKOUT_PURCHASE_INTENT_AUTHORITY_REQUIRED","Production checkout requires owner-proven production durable purchase-intent authority.");
 const entitlementStatus=ownedStatus(entitlementAuthority);
 if(typeof entitlementAuthority?.resolveCurrentEntitlement!=="function"||!entitlementProven(entitlementAuthority,entitlementStatus))fail("MOVIE_MENTOR_CHECKOUT_ENTITLEMENT_AUTHORITY_REQUIRED","Production checkout requires owner-proven current durable entitlement authority.");
 const storeStatus=getMovieMentorCommercialCheckoutBindingMongoStoreStatus();
 if(!checkoutStoreProven(storeStatus))fail("MOVIE_MENTOR_CHECKOUT_BINDING_STORE_NOT_CONFIGURED","Production checkout requires durable Mongo-backed checkout binding with explicit physical unique-index readiness, provider-payment binding and open-checkout discovery authority.");
 const registry=createMovieMentorCommercialCheckoutProviderRegistry({providers});
 if(registry.configuredProviders.length===0)fail("MOVIE_MENTOR_CHECKOUT_PROVIDER_NOT_CONFIGURED","Production checkout requires at least one explicit provider adapter; no provider is selected by accident.");
 const checkoutBindingStore=createMovieMentorCommercialCheckoutBindingMongoStore();
 const rawAuthority=createMovieMentorCommercialCheckoutInitiationAuthority({resolvePurchaseIntent:purchaseIntentAuthority.resolvePurchaseIntent,resolveCurrentEntitlement:entitlementAuthority.resolveCurrentEntitlement,createProviderCheckout:registry.createProviderCheckout,resolveProviderCheckout:registry.resolveProviderCheckout,revokeProviderCheckout:registry.revokeProviderCheckout,checkoutBindingStore});
 const resolveCheckoutBinding=({commercialIntentId}={})=>checkoutBindingStore.resolve({commercialIntentId});
 const bindProviderPaymentReference=({commercialIntentId,provider,checkoutReference,providerPaymentReference}={})=>checkoutBindingStore.bindProviderPaymentReference({commercialIntentId,provider,checkoutReference,providerPaymentReference});
 const resolveCheckoutBindingByProviderPaymentReference=({provider,providerPaymentReference,paymentReference}={})=>checkoutBindingStore.resolveByProviderPaymentReference({provider,providerPaymentReference,paymentReference});
 async function revokeOpenCheckoutsForPrincipal({principalId}={}){const principal=typeof principalId==="string"?principalId.trim():"";if(!principal)fail("MOVIE_MENTOR_CHECKOUT_REVOCATION_PRINCIPAL_REQUIRED","Open checkout revocation requires an exact principal.");const candidates=await checkoutBindingStore.listUnpaidCompleted();let count=0;for(const binding of candidates){const intent=await purchaseIntentAuthority.resolvePurchaseIntent({commercialIntentId:binding.commercialIntentId});if(!intent||intent.principalId!==principal)continue;await registry.revokeProviderCheckout({provider:binding.provider,checkoutReference:binding.checkoutReference});count++;}return Object.freeze({revoked:true,count});}
 const status=checkoutStatus(entitlementStatus,storeStatus);
 const authority=Object.freeze({initiateCheckout:rawAuthority.initiateCheckout,resolveCheckoutBinding,bindProviderPaymentReference,resolveCheckoutBindingByProviderPaymentReference,revokeOpenCheckoutsForPrincipal,getStatus:()=>status});
 productionAuthorityProofs.set(authority,status);
 return Object.freeze({ready:true,authority,authorityStatus:status,registry,checkoutBindingStore,checkoutBindingStoreStatus:storeStatus,publicRoute:false,providerIngress:false,durableCheckoutBinding:true});
}
function getMovieMentorProductionCommercialCheckoutCompositionStatus(){const store=getMovieMentorCommercialCheckoutBindingMongoStoreStatus();return Object.freeze({version:VERSION,providerNeutral:true,publicRoute:false,providerIngress:false,implicitProvider:false,durableCheckoutBinding:true,checkoutBindingResolution:true,currentProviderCheckoutReality:true,providerPaymentReferenceBinding:true,providerPaymentReferenceResolution:true,openCheckoutRevocation:true,postProviderOrphanCheckoutRevocation:true,checkoutBindingUniquenessReadinessRequired:true,checkoutBindingPhysicalUniqueIndexReadiness:true,purchaseIntentProvenanceRequired:true,purchaseIntentOwnerProofRequired:true,currentEntitlementProvenanceRequired:true,currentEntitlementOwnerProofRequired:true,ownerBoundProof:true,configured:checkoutStoreProven(store)});}
export{VERSION as MOVIE_MENTOR_PRODUCTION_COMMERCIAL_CHECKOUT_COMPOSITION_VERSION,AUTHORITY_DOMAIN as MOVIE_MENTOR_PRODUCTION_COMMERCIAL_CHECKOUT_AUTHORITY_DOMAIN,createMovieMentorProductionCommercialCheckoutComposition,getMovieMentorProductionCommercialCheckoutCompositionStatus,getMovieMentorProductionCommercialCheckoutAuthorityOwnedStatus,isMovieMentorProductionCommercialCheckoutAuthorityOwnedProof};export default createMovieMentorProductionCommercialCheckoutComposition;
