/** Movie Mentor Recovery Reality Digest Control v2.0.0 — canonical, domain-separated recovery-universe digest authority. */
import{createHash}from"node:crypto";
const VERSION="2.0.0";
const CONTROL_ID="recovery-reality-digest-control";
const AUTHORITY="recovery-reality-digest-contract-only";
const RECOVERY_REALITY_HASH_DOMAIN="iband.movie-mentor.operations.reconciliation-recovery-reality";
const RECOVERY_REALITY_HASH_SCHEMA=2;
const s=v=>typeof v==="string"?v.trim():"";
const stable=v=>Array.isArray(v)?v.map(stable):v&&typeof v==="object"?Object.keys(v).sort().reduce((o,k)=>(o[k]=stable(v[k]),o),{}):v;
function canonicalizeRecoveryReality(r={}){return{gauntletApprovalHash:s(r.gauntletApprovalHash)||null,creatorStateGeneration:Number.isInteger(r.creatorStateGeneration)?r.creatorStateGeneration:null,creatorStateFingerprint:s(r.creatorStateFingerprint)||null,creatorAuthorityReference:s(r.creatorAuthorityReference)||null,authorityTerm:Number.isInteger(r.authorityTerm)?r.authorityTerm:null,recoveryEpoch:Number.isInteger(r.recoveryEpoch)?r.recoveryEpoch:null,fencingToken:Number.isInteger(r.fencingToken)?r.fencingToken:null}}
function isCompleteRecoveryReality(r={}){const c=canonicalizeRecoveryReality(r);return!!(s(c.gauntletApprovalHash)&&Number.isInteger(c.creatorStateGeneration)&&s(c.creatorStateFingerprint)&&s(c.creatorAuthorityReference)&&Number.isInteger(c.authorityTerm)&&Number.isInteger(c.recoveryEpoch)&&Number.isInteger(c.fencingToken))}
function createRecoveryRealityEnvelope(r={}){return{domain:RECOVERY_REALITY_HASH_DOMAIN,schema:RECOVERY_REALITY_HASH_SCHEMA,payload:canonicalizeRecoveryReality(r)}}
function deriveRecoveryRealityDigest(r={}){const envelope=createRecoveryRealityEnvelope(r);return createHash("sha256").update(JSON.stringify(stable(envelope))).digest("hex")}
function verifyRecoveryRealityDigest({recoveryReality,recoveryRealityHash,domain=RECOVERY_REALITY_HASH_DOMAIN,schema=RECOVERY_REALITY_HASH_SCHEMA}={}){const reasons=[];if(domain!==RECOVERY_REALITY_HASH_DOMAIN)reasons.push("recovery_reality_hash_domain_invalid");if(schema!==RECOVERY_REALITY_HASH_SCHEMA)reasons.push("recovery_reality_hash_schema_invalid");if(!isCompleteRecoveryReality(recoveryReality))reasons.push("recovery_reality_binding_incomplete");const expected=deriveRecoveryRealityDigest(recoveryReality);if(!/^[a-f0-9]{64}$/i.test(s(recoveryRealityHash))||s(recoveryRealityHash)!==expected)reasons.push("recovery_reality_hash_invalid");return{valid:reasons.length===0,reasons,domain:RECOVERY_REALITY_HASH_DOMAIN,schema:RECOVERY_REALITY_HASH_SCHEMA,recoveryReality:canonicalizeRecoveryReality(recoveryReality),recoveryRealityHash:expected}}
function sameRecoveryReality(a,b){return isCompleteRecoveryReality(a)&&isCompleteRecoveryReality(b)&&deriveRecoveryRealityDigest(a)===deriveRecoveryRealityDigest(b)}
function getRecoveryRealityDigestManifest(){return{id:CONTROL_ID,name:"Movie Mentor Recovery Reality Digest Control",version:VERSION,status:"standalone-dormant-not-wired",authority:AUTHORITY,deterministicControl:true,aiAgent:false,failClosed:true,domain:RECOVERY_REALITY_HASH_DOMAIN,schema:RECOVERY_REALITY_HASH_SCHEMA,purpose:"Give one recovery universe one canonical protocol-scoped digest so valid hashes from legacy or foreign protocols cannot become recovery authority.",restrictions:["complete-seven-field-recovery-reality-required","hash-domain-is-fixed","hash-schema-is-fixed","legacy-unscoped-sha256-denied","cross-protocol-domain-substitution-denied","canonical-key-order-does-not-change-digest","single-field-reality-mutation-changes-digest"]}}
export{VERSION as RECOVERY_REALITY_DIGEST_VERSION,CONTROL_ID as RECOVERY_REALITY_DIGEST_CONTROL_ID,AUTHORITY as RECOVERY_REALITY_DIGEST_AUTHORITY,RECOVERY_REALITY_HASH_DOMAIN,RECOVERY_REALITY_HASH_SCHEMA,canonicalizeRecoveryReality,isCompleteRecoveryReality,createRecoveryRealityEnvelope,deriveRecoveryRealityDigest,verifyRecoveryRealityDigest,sameRecoveryReality,getRecoveryRealityDigestManifest};
export default deriveRecoveryRealityDigest;
