import crypto from "node:crypto";
const VERSION="1.4.0",DOMAIN="iband.movie-mentor.inference-spend-authority",OPERATION="movie-mentor-turn",DEFAULT_TURN_UNITS=1;
function text(v){return typeof v==="string"?v.trim():"";} function fail(code,message,extras={}){const e=new Error(message);e.code=code;Object.assign(e,extras);throw e;}
function createMovieMentorInferenceSpendAuthority({store=null,createReservationId=()=>crypto.randomUUID()}={}){
 if(typeof store?.reserve!=="function")fail("MOVIE_MENTOR_INFERENCE_SPEND_AUTHORITY_REQUIRED","Inference spend authority requires a durable atomic reservation store.");
 function evidence(r,{rehydrated=false,idempotent=false}={}){if(!r||!text(r.reservationId)||!text(r.principalId)||!text(r.projectId)||text(r.operation)!==OPERATION||!Number.isSafeInteger(r.units)||r.units<1||!["reserved","consumed","released"].includes(text(r.status)))fail("MOVIE_MENTOR_INFERENCE_SPEND_RESERVATION_INVALID","Durable inference spend reservation is malformed.");return Object.freeze({authorized:true,domain:DOMAIN,reservationId:text(r.reservationId),principalId:text(r.principalId),projectId:text(r.projectId),operation:OPERATION,units:r.units,entitlementRevision:r.entitlementRevision??null,status:text(r.status),rehydrated,idempotent});}
 async function reserveTurn({serverAuthority=null,projectId=null,units=DEFAULT_TURN_UNITS}={}){const principalId=text(serverAuthority?.principalId),authorizedProjectId=text(serverAuthority?.projectId),durableProjectId=text(projectId);if(!principalId)fail("MOVIE_MENTOR_INFERENCE_SPEND_PRINCIPAL_REQUIRED","Authenticated principal authority is required before paid inference.");if(!authorizedProjectId||!durableProjectId)fail("MOVIE_MENTOR_INFERENCE_SPEND_PROJECT_REQUIRED","Authorized and durable project identity are required before paid inference.");if(authorizedProjectId!==durableProjectId)fail("MOVIE_MENTOR_INFERENCE_SPEND_PROJECT_CONFLICT","Authenticated project authority does not match durable creator state.");if(serverAuthority?.authenticated!==true||serverAuthority?.projectAuthorized!==true)fail("MOVIE_MENTOR_INFERENCE_SPEND_AUTHORITY_REQUIRED","Paid inference requires server-created authenticated project authority.");if(!Number.isSafeInteger(units)||units<1)fail("MOVIE_MENTOR_INFERENCE_SPEND_RESERVATION_INVALID","Inference spend units must be a positive safe integer.");const reservationId=text(createReservationId());if(!reservationId)fail("MOVIE_MENTOR_INFERENCE_SPEND_RESERVATION_INVALID","Server reservation identity could not be created.");const decision=await store.reserve({reservationId,principalId,projectId:durableProjectId,operation:OPERATION,units});if(decision?.granted!==true)fail("MOVIE_MENTOR_INFERENCE_SPEND_RESERVATION_DENIED","Creator has no active inference entitlement with sufficient reserved capacity.",{retryable:false,reason:decision?.reason||"reservation-denied"});const r=decision.reservation;if(!r||text(r.reservationId)!==reservationId||text(r.principalId)!==principalId||text(r.projectId)!==durableProjectId||text(r.operation)!==OPERATION||r.units!==units||text(r.status)!=="reserved")fail("MOVIE_MENTOR_INFERENCE_SPEND_RESERVATION_INVALID","Durable inference spend reservation does not bind the requested creator, project and operation.");return evidence(r,{idempotent:decision.idempotent===true});}
 async function readReservation({reservationId=null,principalId=null,projectId=null}={}){if(typeof store?.readReservation!=="function")fail("MOVIE_MENTOR_INFERENCE_SPEND_RESERVATION_READER_REQUIRED","Inference spend authority requires durable reservation rehydration.");const id=text(reservationId),principal=text(principalId),project=text(projectId);if(!id||!principal||!project)fail("MOVIE_MENTOR_INFERENCE_SPEND_RESERVATION_REHYDRATION_BINDING_REQUIRED","Reservation rehydration requires reservation, principal and project identity.");const r=await store.readReservation(id);if(!r)return Object.freeze({authorized:false,reason:"reservation-not-found",reservationId:id});if(text(r.reservationId)!==id||text(r.principalId)!==principal||text(r.projectId)!==project||text(r.operation)!==OPERATION)fail("MOVIE_MENTOR_INFERENCE_SPEND_RESERVATION_REHYDRATION_CONFLICT","Durable reservation does not match the requested immutable creator binding.");return evidence(r,{rehydrated:true,idempotent:true});}
 return Object.freeze({reserveTurn,readReservation});
}
export{VERSION as MOVIE_MENTOR_INFERENCE_SPEND_AUTHORITY_VERSION,DOMAIN as MOVIE_MENTOR_INFERENCE_SPEND_AUTHORITY_DOMAIN,OPERATION as MOVIE_MENTOR_INFERENCE_SPEND_OPERATION,DEFAULT_TURN_UNITS as MOVIE_MENTOR_INFERENCE_SPEND_DEFAULT_TURN_UNITS,createMovieMentorInferenceSpendAuthority};export default createMovieMentorInferenceSpendAuthority;
