import {isMovieMentorJourneyRecoveryProductionBootAuthenticationOwnedProof} from "./MovieMentorJourneyRecoveryProductionBootAuthentication.js";
import {isMovieMentorJourneyRecoveryProductionBootActivationOwnedProof} from "./MovieMentorJourneyRecoveryProductionBootActivation.js";
const VERSION="1.1.0",DOMAIN="iband.movie-mentor.journey-recovery-production-exposure-authority",EXPOSURE_ENV="MOVIE_MENTOR_RECOVERY_EXPOSURE_ENABLED",ENABLED_VALUE="true";
const ownedExposureProofs=new WeakSet();
function text(value){return typeof value==="string"?value.trim():"";} function freeze(value){return Object.freeze(value);}
function closed(reason,extras={}){return freeze({version:VERSION,domain:DOMAIN,authorized:false,reason,exposureEnabled:false,authenticationReady:false,activationReady:false,bootWired:false,...extras});}
function authShape(v){return Boolean(v&&v.ready===true&&v.bootWired===true&&typeof v.verifyCredential==="function"&&text(v.expectedIssuer)&&text(v.expectedAudience));}
function activationShape(v){return Boolean(v&&v.ready===true&&v.bootWired===true&&typeof v.activationAuthority==="function"&&typeof v.renewActivation==="function"&&typeof v.assertFence==="function"&&text(v.processInstanceId)&&text(v.deploymentId));}
function isMovieMentorJourneyRecoveryProductionExposureOwnedProof(value){return Boolean(value&&ownedExposureProofs.has(value));}
function authorizeMovieMentorJourneyRecoveryProductionExposure({env=process.env,bootAuthentication=null,bootActivation=null,isBootAuthenticationOwnedProof=isMovieMentorJourneyRecoveryProductionBootAuthenticationOwnedProof,isBootActivationOwnedProof=isMovieMentorJourneyRecoveryProductionBootActivationOwnedProof}={}){
 const rawExposure=text(env?.[EXPOSURE_ENV]),exposureEnabled=rawExposure===ENABLED_VALUE;const authenticationReady=authShape(bootAuthentication)&&isBootAuthenticationOwnedProof(bootAuthentication)===true;const activationReady=activationShape(bootActivation)&&isBootActivationOwnedProof(bootActivation)===true;
 if(!exposureEnabled)return closed(rawExposure?"production-recovery-exposure-not-explicitly-enabled":"production-recovery-exposure-unconfigured",{exposureEnabled:false,authenticationReady,activationReady});
 if(!authenticationReady)return closed("production-recovery-boot-authentication-not-ready",{exposureEnabled:true,authenticationReady:false,activationReady});
 if(!activationReady)return closed("production-recovery-boot-activation-not-ready",{exposureEnabled:true,authenticationReady:true,activationReady:false});
 const proof=freeze({version:VERSION,domain:DOMAIN,authorized:true,reason:"production-recovery-exposure-authorized",exposureEnabled:true,authenticationReady:true,activationReady:true,bootWired:false,bootAuthentication,bootActivation,ownerBoundProof:true});ownedExposureProofs.add(proof);return proof;
}
function getMovieMentorJourneyRecoveryProductionExposureAuthorityStatus({env=process.env}={}){const rawExposure=text(env?.[EXPOSURE_ENV]);return freeze({version:VERSION,domain:DOMAIN,configured:Boolean(rawExposure),enabled:rawExposure===ENABLED_VALUE,exposureEnv:EXPOSURE_ENV,requiredValue:ENABLED_VALUE,bootWired:false});}
export {VERSION as MOVIE_MENTOR_JOURNEY_RECOVERY_PRODUCTION_EXPOSURE_AUTHORITY_VERSION,DOMAIN as MOVIE_MENTOR_JOURNEY_RECOVERY_PRODUCTION_EXPOSURE_AUTHORITY_DOMAIN,EXPOSURE_ENV as MOVIE_MENTOR_JOURNEY_RECOVERY_PRODUCTION_EXPOSURE_ENV,ENABLED_VALUE as MOVIE_MENTOR_JOURNEY_RECOVERY_PRODUCTION_EXPOSURE_ENABLED_VALUE,authorizeMovieMentorJourneyRecoveryProductionExposure,getMovieMentorJourneyRecoveryProductionExposureAuthorityStatus,isMovieMentorJourneyRecoveryProductionExposureOwnedProof};export default authorizeMovieMentorJourneyRecoveryProductionExposure;
