const VERSION="1.7.0";
const PROVIDER="stripe";
const DOMAIN="iband.movie-mentor.commercial-provider-adapter";
function text(v){return typeof v==="string"?v.trim():"";}
function fail(code,message){const e=new Error(message);e.code=code;throw e;}
function capabilityStatus(){return Object.freeze({version:VERSION,domain:DOMAIN,provider:PROVIDER,productionCommercialProviderAdapter:true,checkoutTransport:true,serverOwnedIdempotencyRequired:true,rawBodyDeliveryVerification:true,signatureVerification:true,normalizesCommercialEvidence:true,checkoutReferenceEvidence:true,providerPaymentReferenceEvidence:true,commercialReversalEvidence:true,creatorPayloadIsNotPaymentAuthority:true,processLocalFallback:false});}
function createMovieMentorStripeCommercialProviderAdapter({stripe,webhookSecret,successUrl,cancelUrl}={}){
 if(!stripe||typeof stripe.checkout?.sessions?.create!=="function"||typeof stripe.webhooks?.constructEvent!=="function")fail("MOVIE_MENTOR_STRIPE_CLIENT_REQUIRED","Stripe adapter requires an explicit Stripe client with Checkout and webhook verification.");
 const secret=text(webhookSecret),success=text(successUrl),cancel=text(cancelUrl);if(!secret||!success||!cancel)fail("MOVIE_MENTOR_STRIPE_CONFIGURATION_REQUIRED","Stripe webhook secret and server-owned success/cancel URLs are required.");
 async function createCheckout({intent,idempotencyKey}={}){if(text(intent?.provider)!==PROVIDER)fail("MOVIE_MENTOR_STRIPE_PROVIDER_MISMATCH","Stripe adapter received an intent for another provider.");const id=text(intent.commercialIntentId),product=text(intent.providerProductId),currency=text(intent.currency).toLowerCase(),key=text(idempotencyKey);if(!id||!product||!Number.isSafeInteger(intent.amountMinor)||intent.amountMinor<0||!currency||key!==`movie-mentor:${id}`)fail("MOVIE_MENTOR_STRIPE_INTENT_INVALID","Stripe checkout requires complete immutable commercial terms and the certified server idempotency key.");const metadata={commercialIntentId:id,providerProductId:product};const session=await stripe.checkout.sessions.create({mode:"payment",line_items:[{price:product,quantity:1}],success_url:success,cancel_url:cancel,client_reference_id:id,metadata,payment_intent_data:{metadata}}, {idempotencyKey:key});if(!text(session?.id)||!text(session?.url))fail("MOVIE_MENTOR_STRIPE_CHECKOUT_RESPONSE_INVALID","Stripe did not return a checkout session id and URL.");return Object.freeze({authorized:true,commercialIntentId:id,provider:PROVIDER,checkoutReference:text(session.id),checkoutUrl:text(session.url),expiresAt:Number.isFinite(session.expires_at)?new Date(session.expires_at*1000).toISOString():null});}
 async function verifyDelivery({delivery}={}){const raw=delivery?.rawBody,signature=text(delivery?.signature);if(!raw||!signature)fail("MOVIE_MENTOR_STRIPE_DELIVERY_INVALID","Stripe webhook verification requires raw request body and Stripe-Signature header.");let event;try{event=stripe.webhooks.constructEvent(raw,signature,secret);}catch(cause){const e=new Error("Stripe webhook signature verification failed.");e.code="MOVIE_MENTOR_STRIPE_SIGNATURE_INVALID";e.cause=cause;throw e;}return Object.freeze({verified:true,provider:PROVIDER,event});}
 async function normalizeEvent({verifiedDelivery}={}){const event=verifiedDelivery?.event;if(!event||verifiedDelivery?.verified!==true||verifiedDelivery?.provider!==PROVIDER)fail("MOVIE_MENTOR_STRIPE_VERIFIED_DELIVERY_INVALID","Verified Stripe delivery is required.");const object=event.data?.object||{},eventId=text(event.id),eventKind=text(event.type),environment=event.livemode===true?"live":"test";
  if(eventKind==="checkout.session.completed"||eventKind==="checkout.session.async_payment_succeeded"){const commercialIntentId=text(object.client_reference_id)||text(object.metadata?.commercialIntentId),paid=text(object.payment_status)==="paid";return Object.freeze({provider:PROVIDER,eventId,eventKind,providerEventId:eventId,eventType:eventKind,commercialIntentId,checkoutReference:text(object.id),providerPaymentReference:text(object.payment_intent),providerProductId:text(object.metadata?.providerProductId),amountMinor:Number.isSafeInteger(object.amount_total)?object.amount_total:null,currency:text(object.currency).toUpperCase(),environment,commerciallyFinal:paid,commercialReversal:false});}
  if(eventKind==="charge.refunded"){return Object.freeze({provider:PROVIDER,eventId,eventKind,providerEventId:eventId,eventType:eventKind,providerPaymentReference:text(object.payment_intent),reversalAmountMinor:Number.isSafeInteger(object.amount_refunded)?object.amount_refunded:null,currency:text(object.currency).toUpperCase(),environment,commerciallyFinal:false,commercialReversal:object.refunded===true||Number.isSafeInteger(object.amount_refunded)&&object.amount_refunded>0,reversalKind:"refund"});}
  if(eventKind==="charge.dispute.created"||eventKind==="charge.dispute.funds_withdrawn"){return Object.freeze({provider:PROVIDER,eventId,eventKind,providerEventId:eventId,eventType:eventKind,providerPaymentReference:text(object.payment_intent),reversalAmountMinor:Number.isSafeInteger(object.amount)?object.amount:null,currency:text(object.currency).toUpperCase(),environment,commerciallyFinal:false,commercialReversal:true,reversalKind:"dispute"});}
  return Object.freeze({provider:PROVIDER,eventId,eventKind,providerEventId:eventId,eventType:eventKind,commercialIntentId:text(object.client_reference_id)||text(object.metadata?.commercialIntentId),checkoutReference:text(object.id),providerPaymentReference:text(object.payment_intent),providerProductId:text(object.metadata?.providerProductId),amountMinor:Number.isSafeInteger(object.amount_total)?object.amount_total:null,currency:text(object.currency).toUpperCase(),environment,commerciallyFinal:false,commercialReversal:false});}
 return Object.freeze({provider:PROVIDER,createCheckout,verifyDelivery,normalizeEvent,getStatus:capabilityStatus});
}
export{VERSION as MOVIE_MENTOR_STRIPE_COMMERCIAL_PROVIDER_ADAPTER_VERSION,PROVIDER as MOVIE_MENTOR_STRIPE_COMMERCIAL_PROVIDER,DOMAIN as MOVIE_MENTOR_COMMERCIAL_PROVIDER_ADAPTER_DOMAIN,createMovieMentorStripeCommercialProviderAdapter};export default createMovieMentorStripeCommercialProviderAdapter;
