/**
 * DEPRECATED COMPATIBILITY BRIDGE
 * Canonical implementation: ./MovieMentorOperationsSupervisor.js
 */
import executeOperationsSupervisor,{OPERATIONS_SUPERVISOR_VERSION,OPERATIONS_SUPERVISOR_CONTRACT_VERSION,OPERATIONS_SUPERVISOR_ID,OPERATIONS_SUPERVISOR_AUTHORITY,OPERATIONS_SUPERVISOR_OUTPUT_SCHEMA,OPERATIONS_SUPERVISOR_INSTRUCTIONS,createOperationsSupervisorWorkOrder,validateOperationsSupervisorWorkOrder,executeOperationsSupervisor as executeCanonicalOperationsSupervisor,getOperationsSupervisorManifest as getCanonicalOperationsSupervisorManifest}from"./MovieMentorOperationsSupervisor.js";
const OPERATIONS_SUPERVISOR_AGENT_ID=OPERATIONS_SUPERVISOR_ID;
function validateOperationsSupervisorContribution(contribution={}){const valid=contribution?.supervisorId===OPERATIONS_SUPERVISOR_ID&&contribution?.readOnly===true;return{valid,issues:valid?[]:["legacy_supervisor_contribution_not_canonical"],contribution:valid?contribution:null}}
async function executeOperationsSupervisorAgent(workOrder={},options={}){return executeCanonicalOperationsSupervisor(workOrder,options)}
function getOperationsSupervisorManifest(){return{...getCanonicalOperationsSupervisorManifest(),legacyBridge:true,deprecatedPath:"ai/MovieMentorOperationsSupervisorAgent.js",canonicalPath:"ai/MovieMentorOperationsSupervisor.js",restrictions:[...(getCanonicalOperationsSupervisorManifest().restrictions||[]),"legacy-bridge-cannot-bypass-canonical-runtime-admission"]}}
export{OPERATIONS_SUPERVISOR_VERSION,OPERATIONS_SUPERVISOR_CONTRACT_VERSION,OPERATIONS_SUPERVISOR_AGENT_ID,OPERATIONS_SUPERVISOR_AUTHORITY,OPERATIONS_SUPERVISOR_OUTPUT_SCHEMA,OPERATIONS_SUPERVISOR_INSTRUCTIONS,validateOperationsSupervisorWorkOrder,validateOperationsSupervisorContribution,createOperationsSupervisorWorkOrder,executeOperationsSupervisorAgent,getOperationsSupervisorManifest};export default executeOperationsSupervisor;
