const VERSION="1.0.0";
const PROVIDER="stripe";
function text(v){return typeof v==="string"?v.trim():"";}
function fail(code,message){const e=new Error(message);e.code=code;throw e;}
function createMovieMentorStripeCommercialProviderAdapter({stripe,webhookSecret,successUrl,cancelUrl}={}){
 if(!stripe||typeof stripe.checkout?.sessions?.create!=="function"||typeof stripe.webhooks?.constructEvent!=="function")fail("MOVIE_MENTOR_STRIPE_CLIENT_REQUIRED","Stripe adapter requires an explicit Stripe client with Checkout and webhook verification.");
 const secret=text(webhookSecret),success=text(successUrl),cancel=text(cancelUrl);if(!secret||!success||!cancel)fail("MOVIE_MENTOR_STRIPE_CONFIGURATION_REQUIRED","Stripe webhook secret and server-owned success/cancel URLs are required.");
 async function createCheckout({intent}={}){if(text(intent?.provider)!==PROVIDER)fail("MOVIE_MENTOR_STRIPE_PROVIDER_MISMATCH","Stripe adapter received an intent for another provider.");const id=text(intent.commercialIntentId),product=text(intent.providerProductId),currency=text(intent.currency).toLowerCase();if(!id||!product||!Number.isSafeInteger(intent.amountMinor)||intent.amountMinor<0||!currency)fail("MOVIE_MENTOR_STRIPE_INTENT_INVALID","Stripe checkout requires complete immutable commercial terms.");const session=await stripe.checkout.sessions.create({mode:"payment",line_items:[{price:product,quantity:1}],success_url:success,cancel_url:cancel,client_reference_id:id,metadata:{commercialIntentId:id,providerProductId:product}}, {idempotencyKey:`movie-mentor:${id}`});if(!text(session?.id)||!text(session?.url))fail("MOVIE_MENTOR_STRIPE_CHECKOUT_RESPONSE_INVALID","Stripe did not return a checkout session id and URL.");return Object.freeze({authorized:true,commercialIntentId:id,provider:PROVIDER,checkoutReference:text(session.id),checkoutUrl:text(session.url),expiresAt:Number.isFinite(session.expires_at)?new Date(session.expires_at*1000).toISOString():null});}
 async function verifyDelivery({delivery}={}){const raw=delivery?.rawBody,signature=text(delivery?.signature);if(!raw||!signature)fail("MOVIE_MENTOR_STRIPE_DELIVERY_INVALID","Stripe webhook verification requires raw request body and Stripe-Signature header.");let event;try{event=stripe.webhooks.constructEvent(raw,signature,secret);}catch(cause){const e=new Error("Stripe webhook signature verification failed.");e.code="MOVIE_MENTOR_STRIPE_SIGNATURE_INVALID";e.cause=cause;throw e;}return Object.freeze({provider:PROVIDER,event});}
 async function normalizeEvent({verifiedDelivery}={}){const event=verifiedDelivery?.event;if(!event||verifiedDelivery?.provider!==PROVIDER)fail("MOVIE_MENTOR_STRIPE_VERIFIED_DELIVERY_INVALID","Verified Stripe delivery is required.");const session=event.data?.object||{};const id=text(session.client_reference_id)||text(session.metadata?.commercialIntentId);const paid=event.type==="checkout.session.completed"&&text(session.payment_status)==="paid";return Object.freeze({provider:PROVIDER,providerEventId:text(event.id),eventType:text(event.type),commercialIntentId:id,providerProductId:text(session.metadata?.providerProductId),amountMinor:Number.isSafeInteger(session.amount_total)?session.amount_total:null,currency:text(session.currency).toUpperCase(),environment:event.livemode===true?"live":"test",commerciallyFinal:paid});}
 return Object.freeze({provider:PROVIDER,createCheckout,verifyDelivery,normalizeEvent});
}
export{VERSION as MOVIE_MENTOR_STRIPE_COMMERCIAL_PROVIDER_ADAPTER_VERSION,PROVIDER as MOVIE_MENTOR_STRIPE_COMMERCIAL_PROVIDER,createMovieMentorStripeCommercialProviderAdapter};export default createMovieMentorStripeCommercialProviderAdapter;
