import { createHash } from "node:crypto";
import { assertCurrentCreatorTruthOnly } from "./MovieMentorCreatorTruthViewControl.js";

const MOVIE_MENTOR_CONTINUITY_CONSEQUENCE_AUTHORITY_VERSION="1.0.0";
const DERIVED_CONTINUITY_AUTHORITY="derived-continuity";
const CONTINUITY_STATUSES=Object.freeze(["consistent","contradiction","unresolved"]);
function s(v){return typeof v==="string"?v.trim():"";}
function a(v){return Array.isArray(v)?v:[];}
function clone(v){if(v===undefined)return undefined;try{return JSON.parse(JSON.stringify(v));}catch{return v;}}
function stable(v){if(v===null||typeof v!=="object")return JSON.stringify(v);if(Array.isArray(v))return `[${v.map(stable).join(",")}]`;return `{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${stable(v[k])}`).join(",")}}`;}
function digest(v){return createHash("sha256").update(stable(v)).digest("hex");}
function currentCanonIndex(context=[]){assertCurrentCreatorTruthOnly(context);const map=new Map();for(const item of a(context)){if(!item||typeof item!=="object"||!s(item.key))continue;map.set(s(item.key),item);}return map;}
function normaliseDependency(dep={},canon){const key=s(dep.key);const source=canon.get(key);if(!source)throw Object.assign(new Error("Derived continuity dependency is not current creator truth."),{code:"CONTINUITY_DEPENDENCY_NOT_CURRENT_CREATOR_TRUTH",validationIssues:[`continuity_dependency_not_current:${key||"missing"}`]});if(dep.value!==undefined&&stable(dep.value)!==stable(source.value))throw Object.assign(new Error("Derived continuity dependency value drifted from current creator truth."),{code:"CONTINUITY_DEPENDENCY_VALUE_DRIFT",validationIssues:[`continuity_dependency_value_drift:${key}`]});return {key,value:clone(source.value),decisionId:s(source.decisionId)||null,decisionKey:s(source.decisionKey)||null,decisionFingerprint:s(source.decisionFingerprint)||null,authority:source.authority||null,confidenceSource:source.confidenceSource||null};}
function createDerivedContinuityConstraint({category="other",key=null,value=null,reason=null,confidence=0,dependencies=[]}={},creatorConfirmedContext=[]){const canon=currentCanonIndex(creatorConfirmedContext);const deps=a(dependencies).map(dep=>normaliseDependency(dep,canon));if(!deps.length)throw Object.assign(new Error("Derived continuity constraint requires current creator-truth dependency proof."),{code:"CONTINUITY_DERIVATION_DEPENDENCY_REQUIRED"});const body={category:s(category)||"other",key:s(key)||null,value:clone(value),reason:s(reason)||null,confidence:Number.isFinite(Number(confidence))?Math.max(0,Math.min(1,Number(confidence))):0,dependencies:deps,authority:DERIVED_CONTINUITY_AUTHORITY,creatorConfirmed:false,mayCreateCanon:false};return {...body,constraintId:`continuity-${digest(body).slice(0,24)}`,constraintDigest:digest(body)};}
function validateDerivedContinuityConstraint(constraint={},creatorConfirmedContext=[]){const issues=[];if(constraint?.authority!==DERIVED_CONTINUITY_AUTHORITY)issues.push("continuity_constraint_authority_invalid");if(constraint?.creatorConfirmed!==false)issues.push("derived_continuity_must_not_be_creator_confirmed");if(constraint?.mayCreateCanon!==false)issues.push("derived_continuity_may_not_create_canon");try{const rebuilt=createDerivedContinuityConstraint(constraint,creatorConfirmedContext);if(s(constraint.constraintId)!==rebuilt.constraintId)issues.push("continuity_constraint_identity_invalid");if(s(constraint.constraintDigest)!==rebuilt.constraintDigest)issues.push("continuity_constraint_digest_invalid");}catch(error){issues.push(...a(error?.validationIssues).length?a(error.validationIssues):[error?.code||"continuity_constraint_invalid"]);}return {valid:issues.length===0,issues};}
function buildContinuityConsequenceEnvelope({creatorConfirmedContext=[],constraints=[],conflicts=[],unresolvedQuestions=[]}={}){assertCurrentCreatorTruthOnly(creatorConfirmedContext);const validated=[];for(const constraint of a(constraints)){const result=validateDerivedContinuityConstraint(constraint,creatorConfirmedContext);if(!result.valid)throw Object.assign(new Error("Derived continuity constraint failed authority validation."),{code:"CONTINUITY_CONSTRAINT_INVALID",validationIssues:result.issues});validated.push(clone(constraint));}const materialConflicts=a(conflicts).filter(item=>item?.requiresCreatorDecision===true||["high","critical"].includes(s(item?.severity)));const unresolved=a(unresolvedQuestions);const status=materialConflicts.length?"contradiction":unresolved.length?"unresolved":"consistent";return {version:MOVIE_MENTOR_CONTINUITY_CONSEQUENCE_AUTHORITY_VERSION,status,authority:DERIVED_CONTINUITY_AUTHORITY,currentCreatorTruth:clone(a(creatorConfirmedContext)),constraints:validated,conflicts:clone(a(conflicts)),unresolvedQuestions:clone(unresolved),requiresClarification:status!=="consistent",mayAdvanceJourney:status==="consistent",creatorTruthDominates:true,derivedConstraintsAreNotCanon:true};}
function assertContinuityMayAdvance(envelope={}){if(!CONTINUITY_STATUSES.includes(envelope?.status)||envelope?.status!=="consistent"||envelope?.requiresClarification===true){const error=new Error("Continuity consequence authority requires creator clarification before advancement.");error.code="CONTINUITY_CONSEQUENCE_CLARIFICATION_REQUIRED";throw error;}return true;}
export{MOVIE_MENTOR_CONTINUITY_CONSEQUENCE_AUTHORITY_VERSION,DERIVED_CONTINUITY_AUTHORITY,CONTINUITY_STATUSES,createDerivedContinuityConstraint,validateDerivedContinuityConstraint,buildContinuityConsequenceEnvelope,assertContinuityMayAdvance};
export default buildContinuityConsequenceEnvelope;
