import mongoose from "mongoose";

const VERSION="1.3.0",DOMAIN="iband.movie-mentor.commercial-checkout-binding",SCHEMA=1,COLLECTION="movie_mentor_commercial_checkout_binding";
let connectionPromise=null,model=null;
function text(v){return typeof v==="string"?v.trim():"";}
function fail(code,message,extras={}){const e=new Error(message);e.code=code;Object.assign(e,extras);throw e;}
function uri(){return text(process.env.MONGO_URI||process.env.MONGODB_URI||"");}
function plain(v){return v&&typeof v.toObject==="function"?v.toObject():v;}
function getModel(){if(model)return model;const schema=new mongoose.Schema({domain:{type:String,required:true,immutable:true},schema:{type:Number,required:true,immutable:true},commercialIntentId:{type:String,required:true,trim:true,immutable:true},provider:{type:String,required:true,trim:true,immutable:true},idempotencyKey:{type:String,required:true,trim:true,immutable:true},status:{type:String,enum:["pending","completed"],required:true},checkoutReference:{type:String,trim:true,default:null},checkoutUrl:{type:String,trim:true,default:null},expiresAt:{type:String,trim:true,default:null},providerPaymentReference:{type:String,trim:true,default:null},createdAtAuthority:{type:Date,required:true,immutable:true},completedAtAuthority:{type:Date,default:null},paymentBoundAtAuthority:{type:Date,default:null}},{collection:COLLECTION,timestamps:true,minimize:false,strict:true});schema.index({commercialIntentId:1},{unique:true});schema.index({provider:1,checkoutReference:1},{unique:true,partialFilterExpression:{checkoutReference:{$type:"string"}}});schema.index({provider:1,providerPaymentReference:1},{unique:true,partialFilterExpression:{providerPaymentReference:{$type:"string"}}});model=mongoose.models.MovieMentorCommercialCheckoutBinding||mongoose.model("MovieMentorCommercialCheckoutBinding",schema);return model;}
async function connect(){const u=uri();if(!u)fail("MOVIE_MENTOR_CHECKOUT_BINDING_STORE_NOT_CONFIGURED","Checkout binding store requires MONGO_URI or MONGODB_URI.");if(mongoose.connection.readyState===1)return;if(!connectionPromise)connectionPromise=mongoose.connect(u,{serverSelectionTimeoutMS:5000,maxPoolSize:10}).catch(error=>{connectionPromise=null;fail("MOVIE_MENTOR_CHECKOUT_BINDING_AUTHORITY_UNAVAILABLE",`Checkout binding store unavailable: ${error instanceof Error?error.message:"Mongo connection failed."}`,{retryable:true});});await connectionPromise;}
function normalize(v){v=plain(v);if(!v||v.domain!==DOMAIN||v.schema!==SCHEMA||!text(v.commercialIntentId)||!text(v.provider)||!text(v.idempotencyKey)||!["pending","completed"].includes(text(v.status)))fail("MOVIE_MENTOR_CHECKOUT_BINDING_RECORD_INVALID","Durable checkout binding is malformed.");if(v.status==="completed"&&(!text(v.checkoutReference)||!text(v.checkoutUrl)))fail("MOVIE_MENTOR_CHECKOUT_BINDING_RECORD_INVALID","Completed checkout binding requires provider reference and URL.");return Object.freeze({commercialIntentId:text(v.commercialIntentId),provider:text(v.provider),idempotencyKey:text(v.idempotencyKey),status:text(v.status),checkoutReference:text(v.checkoutReference)||null,checkoutUrl:text(v.checkoutUrl)||null,expiresAt:text(v.expiresAt)||null,providerPaymentReference:text(v.providerPaymentReference)||null,createdAt:v.createdAtAuthority?new Date(v.createdAtAuthority).toISOString():null,completedAt:v.completedAtAuthority?new Date(v.completedAtAuthority).toISOString():null,paymentBoundAt:v.paymentBoundAtAuthority?new Date(v.paymentBoundAtAuthority).toISOString():null});}
function createMovieMentorCommercialCheckoutBindingMongoStore({modelRef=null,connectStore=connect,now=()=>new Date()}={}){const M=()=>modelRef||getModel();let indexReadinessPromise=null;async function ready(){if(!modelRef)await connectStore();if(!indexReadinessPromise){const target=M();indexReadinessPromise=(async()=>{if(typeof target?.createIndexes==="function"){await target.createIndexes();return;}if(modelRef)return;fail("MOVIE_MENTOR_CHECKOUT_BINDING_INDEX_AUTHORITY_UNAVAILABLE","Checkout binding model cannot prove physical unique-index readiness.",{retryable:true});})().catch(error=>{indexReadinessPromise=null;if(error?.code?.startsWith?.("MOVIE_MENTOR_CHECKOUT_BINDING_"))throw error;fail("MOVIE_MENTOR_CHECKOUT_BINDING_INDEX_AUTHORITY_UNAVAILABLE",`Checkout binding unique-index readiness failed: ${error instanceof Error?error.message:"index initialization failed"}`,{retryable:true});});}await indexReadinessPromise;}
 async function begin({commercialIntentId,provider,idempotencyKey}={}){const id=text(commercialIntentId),p=text(provider),key=text(idempotencyKey);if(!id||!p||!key)fail("MOVIE_MENTOR_CHECKOUT_BINDING_REQUEST_INVALID","Checkout binding identity, provider and idempotency key are required.");await ready();try{const record=await M().findOneAndUpdate({domain:DOMAIN,schema:SCHEMA,commercialIntentId:id},{$setOnInsert:{domain:DOMAIN,schema:SCHEMA,commercialIntentId:id,provider:p,idempotencyKey:key,status:"pending",createdAtAuthority:now()}},{upsert:true,new:true,setDefaultsOnInsert:true}).lean().exec();const result=normalize(record);if(result.provider!==p||result.idempotencyKey!==key)fail("MOVIE_MENTOR_CHECKOUT_BINDING_CONFLICT","Existing checkout binding does not match provider operation authority.");return result;}catch(error){if(error?.code===11000){const existing=await resolve({commercialIntentId:id});if(existing&&existing.provider===p&&existing.idempotencyKey===key)return existing;fail("MOVIE_MENTOR_CHECKOUT_BINDING_CONFLICT","Checkout binding identity conflicts with durable reality.");}if(error?.code?.startsWith?.("MOVIE_MENTOR_CHECKOUT_BINDING_"))throw error;fail("MOVIE_MENTOR_CHECKOUT_BINDING_AUTHORITY_UNAVAILABLE",`Checkout binding reservation failed: ${error instanceof Error?error.message:"write failed"}`,{retryable:true});}}
 async function complete({commercialIntentId,provider,idempotencyKey,checkoutReference,checkoutUrl,expiresAt=null}={}){const id=text(commercialIntentId),p=text(provider),key=text(idempotencyKey),ref=text(checkoutReference),url=text(checkoutUrl);if(!id||!p||!key||!ref||!url)fail("MOVIE_MENTOR_CHECKOUT_BINDING_COMPLETION_INVALID","Checkout completion requires durable operation identity and provider session evidence.");await ready();try{const record=await M().findOneAndUpdate({domain:DOMAIN,schema:SCHEMA,commercialIntentId:id,provider:p,idempotencyKey:key,status:"pending"},{$set:{status:"completed",checkoutReference:ref,checkoutUrl:url,expiresAt:text(expiresAt)||null,completedAtAuthority:now()}},{new:true}).lean().exec();if(record)return normalize(record);const existing=await resolve({commercialIntentId:id});if(existing?.status==="completed"&&existing.provider===p&&existing.idempotencyKey===key&&existing.checkoutReference===ref)return existing;fail("MOVIE_MENTOR_CHECKOUT_BINDING_CONFLICT","Checkout completion lost durable operation authority.");}catch(error){if(error?.code===11000)fail("MOVIE_MENTOR_CHECKOUT_BINDING_PROVIDER_REFERENCE_CONFLICT","Provider checkout reference is already bound to another commercial intent.");if(error?.code?.startsWith?.("MOVIE_MENTOR_CHECKOUT_BINDING_"))throw error;fail("MOVIE_MENTOR_CHECKOUT_BINDING_AUTHORITY_UNAVAILABLE",`Checkout binding completion failed: ${error instanceof Error?error.message:"write failed"}`,{retryable:true});}}
 async function bindProviderPaymentReference({commercialIntentId,provider,checkoutReference,providerPaymentReference}={}){const id=text(commercialIntentId),p=text(provider),checkout=text(checkoutReference),payment=text(providerPaymentReference);if(!id||!p||!checkout||!payment)fail("MOVIE_MENTOR_CHECKOUT_PAYMENT_BINDING_INVALID","Payment binding requires commercial intent, provider, checkout and provider payment identities.");await ready();try{const record=await M().findOneAndUpdate({domain:DOMAIN,schema:SCHEMA,commercialIntentId:id,provider:p,status:"completed",checkoutReference:checkout,$or:[{providerPaymentReference:null},{providerPaymentReference:""},{providerPaymentReference:payment}]},{$set:{providerPaymentReference:payment,paymentBoundAtAuthority:now()}},{new:true}).lean().exec();if(record)return normalize(record);const existing=await resolve({commercialIntentId:id});if(existing?.status==="completed"&&existing.provider===p&&existing.checkoutReference===checkout&&existing.providerPaymentReference===payment)return existing;fail("MOVIE_MENTOR_CHECKOUT_PAYMENT_BINDING_CONFLICT","Provider payment identity conflicts with durable checkout reality.");}catch(error){if(error?.code===11000)fail("MOVIE_MENTOR_CHECKOUT_PAYMENT_REFERENCE_CONFLICT","Provider payment identity is already bound to another checkout.");if(error?.code?.startsWith?.("MOVIE_MENTOR_CHECKOUT_"))throw error;fail("MOVIE_MENTOR_CHECKOUT_BINDING_AUTHORITY_UNAVAILABLE",`Provider payment binding failed: ${error instanceof Error?error.message:"write failed"}`,{retryable:true});}}
 async function resolve({commercialIntentId}={}){const id=text(commercialIntentId);if(!id)return null;await ready();const found=await M().findOne({domain:DOMAIN,schema:SCHEMA,commercialIntentId:id}).lean().exec();return found?normalize(found):null;}
 async function resolveByProviderPaymentReference({provider,providerPaymentReference,paymentReference}={}){const p=text(provider),payment=text(providerPaymentReference)||text(paymentReference);if(!p||!payment)return null;await ready();const found=await M().findOne({domain:DOMAIN,schema:SCHEMA,provider:p,providerPaymentReference:payment,status:"completed"}).lean().exec();return found?normalize(found):null;}
 async function listUnpaidCompleted(){await ready();const found=await M().find({domain:DOMAIN,schema:SCHEMA,status:"completed",$or:[{providerPaymentReference:null},{providerPaymentReference:""}]}).lean().exec();return Object.freeze((found||[]).map(normalize));}
 return Object.freeze({begin,complete,bindProviderPaymentReference,resolve,resolveByProviderPaymentReference,listUnpaidCompleted});}
function getMovieMentorCommercialCheckoutBindingMongoStoreStatus(){const configured=Boolean(uri());return Object.freeze({version:VERSION,configured,readiness:configured?"configured":"configuration-required",collection:COLLECTION,durable:true,providerPaymentReferenceBinding:true,providerPaymentReferenceResolution:true,unpaidCompletedCheckoutDiscovery:true,uniquenessReadinessRequired:true,physicalUniqueIndexReadiness:true,processLocalFallback:false});}
export{VERSION as MOVIE_MENTOR_COMMERCIAL_CHECKOUT_BINDING_MONGO_STORE_VERSION,COLLECTION as MOVIE_MENTOR_COMMERCIAL_CHECKOUT_BINDING_COLLECTION,createMovieMentorCommercialCheckoutBindingMongoStore,getMovieMentorCommercialCheckoutBindingMongoStoreStatus};export default createMovieMentorCommercialCheckoutBindingMongoStore;
