name: CI (Backend)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install deps
        run: npm ci || npm i --no-audit --no-fund

      # 👉 Auto-format the working tree so ESLint stops complaining
      - name: Format code (Prettier --write)
        run: npx prettier . --write

      - name: Print versions
        run: |
          node -v
          npm -v

      - name: Lint (ESLint)
        run: npm run lint

      - name: Check formatting (Prettier)
        run: npx prettier . --check

      - name: Run tests (Jest)
        run: npm test --silent