name: CI (Backend)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'     # keep simple; no npm cache until we add a lockfile

      - name: Install deps
        run: npm install --no-audit --no-fund

      - name: Print versions
        run: |
          node -v
          npm -v

      - name: Lint (ESLint)
        run: npm run lint

      - name: Check formatting (Prettier)
        run: npm run format:check

      - name: Run tests (Jest)
        run: npm test -- --ci